#0 building with "default" instance using docker driver

#1 [internal] load build definition from Dockerfile
#1 transferring dockerfile: 1.26kB done
#1 DONE 0.0s

#2 [internal] load metadata for docker.io/library/python:3.10
#2 DONE 0.0s

#3 [internal] load .dockerignore
#3 transferring context: 2B done
#3 DONE 0.0s

#4 [1/5] FROM docker.io/library/python:3.10
#4 DONE 0.0s

#5 [2/5] RUN mkdir -p ~/.pip && touch ~/.pip/pip.conf &&     echo "[global]" >> ~/.pip/pip.conf && echo "index-url=http://simple/" >> ~/.pip/pip.conf && echo "[install]" >> ~/.pip/pip.conf && echo "trusted-host=pypi..org" >> ~/.pip/pip.conf &&     apt-get update && apt-get install -y curl &&     curl -sSL https://install.python-poetry.org | python -
#5 CACHED

#6 [3/5] RUN pip install pytest pytest-xdist &&     pip install pipdeptree &&     git clone https://github.com/taketwo/llm-ollama.git &&     mkdir /repo &&     git config --global --add safe.directory /repo &&     cp -r /llm-ollama/. /repo && rm -rf /llm-ollama/ &&     rm -rf /llm-ollama &&     cd /repo && git checkout dd616e755568e70457943c069ef197becd914cd9 &&     pip install llm==0.19.1 &&     pip install ollama==0.4.4 &&     pip install pydantic==2.10.3 &&     pip install pytest==8.3.4 &&     pip install pytest-asyncio==0.25.0 &&     pip install black==24.10.0
#6 1.705 Looking in indexes: http://simple/
#6 1.871 Collecting pytest
#6 1.894   Downloading http://packages/pytest/pytest-8.3.4-py3-none-any.whl (343 kB)
#6 1.922      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 343.1/343.1 kB 15.4 MB/s eta 0:00:00
#6 1.995 Collecting pytest-xdist
#6 2.017   Downloading http://packages/pytest-xdist/pytest_xdist-3.6.1-py3-none-any.whl (46 kB)
#6 2.029      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 46.1/46.1 kB 4.9 MB/s eta 0:00:00
#6 2.080 Collecting iniconfig
#6 2.098   Downloading http://packages/iniconfig/iniconfig-2.0.0-py3-none-any.whl (5.9 kB)
#6 2.169 Collecting packaging
#6 2.191   Downloading http://packages/packaging/packaging-24.2-py3-none-any.whl (65 kB)
#6 2.204      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 65.5/65.5 kB 6.8 MB/s eta 0:00:00
#6 2.262 Collecting tomli>=1
#6 2.281   Downloading http://packages/tomli/tomli-2.2.1-py3-none-any.whl (14 kB)
#6 2.330 Collecting exceptiongroup>=1.0.0rc8
#6 2.348   Downloading http://packages/exceptiongroup/exceptiongroup-1.2.2-py3-none-any.whl (16 kB)
#6 2.405 Collecting pluggy<2,>=1.5
#6 2.428   Downloading http://packages/pluggy/pluggy-1.5.0-py3-none-any.whl (20 kB)
#6 2.502 Collecting execnet>=2.1
#6 2.520   Downloading http://packages/execnet/execnet-2.1.1-py3-none-any.whl (40 kB)
#6 2.529      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 40.6/40.6 kB 7.2 MB/s eta 0:00:00
#6 2.659 Installing collected packages: tomli, pluggy, packaging, iniconfig, execnet, exceptiongroup, pytest, pytest-xdist
#6 3.223 Successfully installed exceptiongroup-1.2.2 execnet-2.1.1 iniconfig-2.0.0 packaging-24.2 pluggy-1.5.0 pytest-8.3.4 pytest-xdist-3.6.1 tomli-2.2.1
#6 3.224 WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
#6 3.351 
#6 3.351 [notice] A new release of pip is available: 23.0.1 -> 24.3.1
#6 3.351 [notice] To update, run: pip install --upgrade pip
#6 4.144 Looking in indexes: http://simple/
#6 4.231 Collecting pipdeptree
#6 4.249   Downloading http://packages/pipdeptree/pipdeptree-2.24.0-py3-none-any.whl (32 kB)
#6 4.281 Requirement already satisfied: packaging>=24.1 in /usr/local/lib/python3.10/site-packages (from pipdeptree) (24.2)
#6 4.395 Collecting pip>=24.2
#6 4.406   Using cached http://packages/pip/pip-24.3.1-py3-none-any.whl (1.8 MB)
#6 4.524 Installing collected packages: pip, pipdeptree
#6 4.525   Attempting uninstall: pip
#6 4.526     Found existing installation: pip 23.0.1
#6 4.687     Uninstalling pip-23.0.1:
#6 4.839       Successfully uninstalled pip-23.0.1
#6 6.045 Successfully installed pip-24.3.1 pipdeptree-2.24.0
#6 6.046 WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
#6 6.198 Cloning into 'llm-ollama'...
#6 8.009 Note: switching to 'dd616e755568e70457943c069ef197becd914cd9'.
#6 8.009 
#6 8.009 You are in 'detached HEAD' state. You can look around, make experimental
#6 8.009 changes and commit them, and you can discard any commits you make in this
#6 8.009 state without impacting any branches by switching back to a branch.
#6 8.009 
#6 8.009 If you want to create a new branch to retain commits you create, you may
#6 8.009 do so (now or later) by using -c with the switch command. Example:
#6 8.009 
#6 8.009   git switch -c <new-branch-name>
#6 8.009 
#6 8.009 Or undo this operation with:
#6 8.009 
#6 8.009   git switch -
#6 8.009 
#6 8.009 Turn off this advice by setting config variable advice.detachedHead to false
#6 8.009 
#6 8.009 HEAD is now at dd616e7 Reword section about async models
#6 8.565 Looking in indexes: http://simple/
#6 8.686 Collecting llm==0.19.1
#6 8.790   Downloading http://packages/llm/llm-0.19.1-py3-none-any.whl (44 kB)
#6 8.856 Collecting click (from llm==0.19.1)
#6 8.875   Downloading http://packages/click/click-8.1.8-py3-none-any.whl (98 kB)
#6 9.064 Collecting openai>=1.0 (from llm==0.19.1)
#6 9.081   Downloading http://packages/openai/openai-1.59.4-py3-none-any.whl (454 kB)
#6 9.136 Collecting click-default-group>=1.2.3 (from llm==0.19.1)
#6 9.227   Downloading http://packages/click-default-group/click_default_group-1.2.4-py2.py3-none-any.whl (4.1 kB)
#6 9.356 Collecting sqlite-utils>=3.37 (from llm==0.19.1)
#6 9.445   Downloading http://packages/sqlite-utils/sqlite_utils-3.38-py3-none-any.whl (68 kB)
#6 9.485 Collecting sqlite-migrate>=0.1a2 (from llm==0.19.1)
#6 9.505   Downloading http://packages/sqlite-migrate/sqlite_migrate-0.1b0-py3-none-any.whl (10.0 kB)
#6 9.786 Collecting pydantic>=1.10.2 (from llm==0.19.1)
#6 9.803   Downloading http://packages/pydantic/pydantic-2.10.4-py3-none-any.whl (431 kB)
#6 9.918 Collecting PyYAML (from llm==0.19.1)
#6 9.940   Downloading http://packages/pyyaml/PyYAML-6.0.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (751 kB)
#6 9.971      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 751.2/751.2 kB 38.8 MB/s eta 0:00:00
#6 9.976 Requirement already satisfied: pluggy in /usr/local/lib/python3.10/site-packages (from llm==0.19.1) (1.5.0)
#6 10.00 Collecting python-ulid (from llm==0.19.1)
#6 10.11   Downloading http://packages/python-ulid/python_ulid-3.0.0-py3-none-any.whl (11 kB)
#6 10.12 Requirement already satisfied: setuptools in /usr/local/lib/python3.10/site-packages (from llm==0.19.1) (65.5.1)
#6 10.12 Requirement already satisfied: pip in /usr/local/lib/python3.10/site-packages (from llm==0.19.1) (24.3.1)
#6 10.14 Collecting puremagic (from llm==0.19.1)
#6 10.16   Downloading http://packages/puremagic/puremagic-1.28-py3-none-any.whl (43 kB)
#6 10.23 Collecting anyio<5,>=3.5.0 (from openai>=1.0->llm==0.19.1)
#6 10.25   Downloading http://packages/anyio/anyio-4.8.0-py3-none-any.whl (96 kB)
#6 10.29 Collecting distro<2,>=1.7.0 (from openai>=1.0->llm==0.19.1)
#6 10.31   Downloading http://packages/distro/distro-1.9.0-py3-none-any.whl (20 kB)
#6 10.39 Collecting httpx<1,>=0.23.0 (from openai>=1.0->llm==0.19.1)
#6 10.41   Downloading http://packages/httpx/httpx-0.28.1-py3-none-any.whl (73 kB)
#6 10.54 Collecting jiter<1,>=0.4.0 (from openai>=1.0->llm==0.19.1)
#6 10.57   Downloading http://packages/jiter/jiter-0.8.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (345 kB)
#6 10.65 Collecting sniffio (from openai>=1.0->llm==0.19.1)
#6 10.66   Downloading http://packages/sniffio/sniffio-1.3.1-py3-none-any.whl (10 kB)
#6 10.78 Collecting tqdm>4 (from openai>=1.0->llm==0.19.1)
#6 10.80   Downloading http://packages/tqdm/tqdm-4.67.1-py3-none-any.whl (78 kB)
#6 10.86 Collecting typing-extensions<5,>=4.11 (from openai>=1.0->llm==0.19.1)
#6 10.88   Downloading http://packages/typing-extensions/typing_extensions-4.12.2-py3-none-any.whl (37 kB)
#6 10.91 Collecting annotated-types>=0.6.0 (from pydantic>=1.10.2->llm==0.19.1)
#6 10.93   Downloading http://packages/annotated-types/annotated_types-0.7.0-py3-none-any.whl (13 kB)
#6 12.20 Collecting pydantic-core==2.27.2 (from pydantic>=1.10.2->llm==0.19.1)
#6 12.22   Downloading http://packages/pydantic-core/pydantic_core-2.27.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (2.0 MB)
#6 12.26      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.0/2.0 MB 73.4 MB/s eta 0:00:00
#6 12.41 Collecting sqlite-fts4 (from sqlite-utils>=3.37->llm==0.19.1)
#6 12.43   Downloading http://packages/sqlite-fts4/sqlite_fts4-1.0.3-py3-none-any.whl (10.0 kB)
#6 12.46 Collecting tabulate (from sqlite-utils>=3.37->llm==0.19.1)
#6 12.47   Downloading http://packages/tabulate/tabulate-0.9.0-py3-none-any.whl (35 kB)
#6 12.51 Collecting python-dateutil (from sqlite-utils>=3.37->llm==0.19.1)
#6 12.53   Downloading http://packages/python-dateutil/python_dateutil-2.9.0.post0-py2.py3-none-any.whl (229 kB)
#6 12.58 Requirement already satisfied: exceptiongroup>=1.0.2 in /usr/local/lib/python3.10/site-packages (from anyio<5,>=3.5.0->openai>=1.0->llm==0.19.1) (1.2.2)
#6 12.61 Collecting idna>=2.8 (from anyio<5,>=3.5.0->openai>=1.0->llm==0.19.1)
#6 12.61   Using cached http://packages/idna/idna-3.10-py3-none-any.whl (70 kB)
#6 12.67 Collecting certifi (from httpx<1,>=0.23.0->openai>=1.0->llm==0.19.1)
#6 12.67   Using cached http://packages/certifi/certifi-2024.12.14-py3-none-any.whl (164 kB)
#6 12.74 Collecting httpcore==1.* (from httpx<1,>=0.23.0->openai>=1.0->llm==0.19.1)
#6 12.75   Downloading http://packages/httpcore/httpcore-1.0.7-py3-none-any.whl (78 kB)
#6 12.79 Collecting h11<0.15,>=0.13 (from httpcore==1.*->httpx<1,>=0.23.0->openai>=1.0->llm==0.19.1)
#6 12.81   Downloading http://packages/h11/h11-0.14.0-py3-none-any.whl (58 kB)
#6 12.86 Collecting six>=1.5 (from python-dateutil->sqlite-utils>=3.37->llm==0.19.1)
#6 12.88   Downloading http://packages/six/six-1.17.0-py2.py3-none-any.whl (11 kB)
#6 12.98 Installing collected packages: sqlite-fts4, puremagic, typing-extensions, tqdm, tabulate, sniffio, six, PyYAML, python-ulid, jiter, idna, h11, distro, click, certifi, annotated-types, python-dateutil, pydantic-core, httpcore, click-default-group, anyio, sqlite-utils, pydantic, httpx, sqlite-migrate, openai, llm
#6 15.08 Successfully installed PyYAML-6.0.2 annotated-types-0.7.0 anyio-4.8.0 certifi-2024.12.14 click-8.1.8 click-default-group-1.2.4 distro-1.9.0 h11-0.14.0 httpcore-1.0.7 httpx-0.28.1 idna-3.10 jiter-0.8.2 llm-0.19.1 openai-1.59.4 puremagic-1.28 pydantic-2.10.4 pydantic-core-2.27.2 python-dateutil-2.9.0.post0 python-ulid-3.0.0 six-1.17.0 sniffio-1.3.1 sqlite-fts4-1.0.3 sqlite-migrate-0.1b0 sqlite-utils-3.38 tabulate-0.9.0 tqdm-4.67.1 typing-extensions-4.12.2
#6 15.08 WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager, possibly rendering your system unusable.It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv. Use the --root-user-action option if you know what you are doing and want to suppress this warning.
#6 16.26 Looking in indexes: http://simple/
#6 16.30 Collecting ollama==0.4.4
#6 16.39   Downloading http://packages/ollama/ollama-0.4.4-py3-none-any.whl (13 kB)
#6 16.45 Collecting httpx<0.28.0,>=0.27.0 (from ollama==0.4.4)
#6 16.47   Downloading http://packages/httpx/httpx-0.27.2-py3-none-any.whl (76 kB)
#6 16.49 Requirement already satisfied: pydantic<3.0.0,>=2.9.0 in /usr/local/lib/python3.10/site-packages (from ollama==0.4.4) (2.10.4)
#6 16.49 Requirement already satisfied: anyio in /usr/local/lib/python3.10/site-packages (from httpx<0.28.0,>=0.27.0->ollama==0.4.4) (4.8.0)
#6 16.49 Requirement already satisfied: certifi in /usr/local/lib/python3.10/site-packages (from httpx<0.28.0,>=0.27.0->ollama==0.4.4) (2024.12.14)
#6 16.49 Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.10/site-packages (from httpx<0.28.0,>=0.27.0->ollama==0.4.4) (1.0.7)
#6 16.50 Requirement already satisfied: idna in /usr/local/lib/python3.10/site-packages (from httpx<0.28.0,>=0.27.0->ollama==0.4.4) (3.10)
#6 16.50 Requirement already satisfied: sniffio in /usr/local/lib/python3.10/site-packages (from httpx<0.28.0,>=0.27.0->ollama==0.4.4) (1.3.1)
#6 16.50 Requirement already satisfied: h11<0.15,>=0.13 in /usr/local/lib/python3.10/site-packages (from httpcore==1.*->httpx<0.28.0,>=0.27.0->ollama==0.4.4) (0.14.0)
#6 16.51 Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.10/site-packages (from pydantic<3.0.0,>=2.9.0->ollama==0.4.4) (0.7.0)
#6 16.51 Requirement already satisfied: pydantic-core==2.27.2 in /usr/local/lib/python3.10/site-packages (from pydantic<3.0.0,>=2.9.0->ollama==0.4.4) (2.27.2)
#6 16.51 Requirement already satisfied: typing-extensions>=4.12.2 in /usr/local/lib/python3.10/site-packages (from pydantic<3.0.0,>=2.9.0->ollama==0.4.4) (4.12.2)
#6 16.52 Requirement already satisfied: exceptiongroup>=1.0.2 in /usr/local/lib/python3.10/site-packages (from anyio->httpx<0.28.0,>=0.27.0->ollama==0.4.4) (1.2.2)
#6 16.64 Installing collected packages: httpx, ollama
#6 16.64   Attempting uninstall: httpx
#6 16.65     Found existing installation: httpx 0.28.1
#6 16.65     Uninstalling httpx-0.28.1:
#6 16.65       Successfully uninstalled httpx-0.28.1
#6 16.79 Successfully installed httpx-0.27.2 ollama-0.4.4
#6 16.79 WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager, possibly rendering your system unusable.It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv. Use the --root-user-action option if you know what you are doing and want to suppress this warning.
#6 17.64 Looking in indexes: http://simple/
#6 17.98 Collecting pydantic==2.10.3
#6 18.00   Downloading http://packages/pydantic/pydantic-2.10.3-py3-none-any.whl (456 kB)
#6 18.05 Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.10/site-packages (from pydantic==2.10.3) (0.7.0)
#6 19.37 Collecting pydantic-core==2.27.1 (from pydantic==2.10.3)
#6 19.40   Downloading http://packages/pydantic-core/pydantic_core-2.27.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (2.1 MB)
#6 19.52      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.1/2.1 MB 102.4 MB/s eta 0:00:00
#6 19.53 Requirement already satisfied: typing-extensions>=4.12.2 in /usr/local/lib/python3.10/site-packages (from pydantic==2.10.3) (4.12.2)
#6 19.62 Installing collected packages: pydantic-core, pydantic
#6 19.62   Attempting uninstall: pydantic-core
#6 19.63     Found existing installation: pydantic_core 2.27.2
#6 19.63     Uninstalling pydantic_core-2.27.2:
#6 19.63       Successfully uninstalled pydantic_core-2.27.2
#6 19.71   Attempting uninstall: pydantic
#6 19.71     Found existing installation: pydantic 2.10.4
#6 19.73     Uninstalling pydantic-2.10.4:
#6 19.73       Successfully uninstalled pydantic-2.10.4
#6 20.13 Successfully installed pydantic-2.10.3 pydantic-core-2.27.1
#6 20.13 WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager, possibly rendering your system unusable.It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv. Use the --root-user-action option if you know what you are doing and want to suppress this warning.
#6 21.13 Looking in indexes: http://simple/
#6 21.13 Requirement already satisfied: pytest==8.3.4 in /usr/local/lib/python3.10/site-packages (8.3.4)
#6 21.14 Requirement already satisfied: exceptiongroup>=1.0.0rc8 in /usr/local/lib/python3.10/site-packages (from pytest==8.3.4) (1.2.2)
#6 21.14 Requirement already satisfied: iniconfig in /usr/local/lib/python3.10/site-packages (from pytest==8.3.4) (2.0.0)
#6 21.14 Requirement already satisfied: packaging in /usr/local/lib/python3.10/site-packages (from pytest==8.3.4) (24.2)
#6 21.14 Requirement already satisfied: pluggy<2,>=1.5 in /usr/local/lib/python3.10/site-packages (from pytest==8.3.4) (1.5.0)
#6 21.14 Requirement already satisfied: tomli>=1 in /usr/local/lib/python3.10/site-packages (from pytest==8.3.4) (2.2.1)
#6 21.22 WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager, possibly rendering your system unusable.It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv. Use the --root-user-action option if you know what you are doing and want to suppress this warning.
#6 21.90 Looking in indexes: http://simple/
#6 21.96 Collecting pytest-asyncio==0.25.0
#6 21.98   Downloading http://packages/pytest-asyncio/pytest_asyncio-0.25.0-py3-none-any.whl (19 kB)
#6 22.00 Requirement already satisfied: pytest<9,>=8.2 in /usr/local/lib/python3.10/site-packages (from pytest-asyncio==0.25.0) (8.3.4)
#6 22.00 Requirement already satisfied: exceptiongroup>=1.0.0rc8 in /usr/local/lib/python3.10/site-packages (from pytest<9,>=8.2->pytest-asyncio==0.25.0) (1.2.2)
#6 22.00 Requirement already satisfied: iniconfig in /usr/local/lib/python3.10/site-packages (from pytest<9,>=8.2->pytest-asyncio==0.25.0) (2.0.0)
#6 22.01 Requirement already satisfied: packaging in /usr/local/lib/python3.10/site-packages (from pytest<9,>=8.2->pytest-asyncio==0.25.0) (24.2)
#6 22.01 Requirement already satisfied: pluggy<2,>=1.5 in /usr/local/lib/python3.10/site-packages (from pytest<9,>=8.2->pytest-asyncio==0.25.0) (1.5.0)
#6 22.01 Requirement already satisfied: tomli>=1 in /usr/local/lib/python3.10/site-packages (from pytest<9,>=8.2->pytest-asyncio==0.25.0) (2.2.1)
#6 22.11 Installing collected packages: pytest-asyncio
#6 22.13 Successfully installed pytest-asyncio-0.25.0
#6 22.14 WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager, possibly rendering your system unusable.It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv. Use the --root-user-action option if you know what you are doing and want to suppress this warning.
#6 22.83 Looking in indexes: http://simple/
#6 22.96 Collecting black==24.10.0
#6 22.98   Downloading http://packages/black/black-24.10.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.manylinux_2_28_x86_64.whl (1.8 MB)
#6 23.02      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.8/1.8 MB 63.9 MB/s eta 0:00:00
#6 23.05 Requirement already satisfied: click>=8.0.0 in /usr/local/lib/python3.10/site-packages (from black==24.10.0) (8.1.8)
#6 23.07 Collecting mypy-extensions>=0.4.3 (from black==24.10.0)
#6 23.08   Downloading http://packages/mypy-extensions/mypy_extensions-1.0.0-py3-none-any.whl (4.7 kB)
#6 23.09 Requirement already satisfied: packaging>=22.0 in /usr/local/lib/python3.10/site-packages (from black==24.10.0) (24.2)
#6 23.12 Collecting pathspec>=0.9.0 (from black==24.10.0)
#6 23.14   Downloading http://packages/pathspec/pathspec-0.12.1-py3-none-any.whl (31 kB)
#6 23.22 Collecting platformdirs>=2 (from black==24.10.0)
#6 23.22   Using cached http://packages/platformdirs/platformdirs-4.3.6-py3-none-any.whl (18 kB)
#6 23.23 Requirement already satisfied: tomli>=1.1.0 in /usr/local/lib/python3.10/site-packages (from black==24.10.0) (2.2.1)
#6 23.23 Requirement already satisfied: typing-extensions>=4.0.1 in /usr/local/lib/python3.10/site-packages (from black==24.10.0) (4.12.2)
#6 23.33 Installing collected packages: platformdirs, pathspec, mypy-extensions, black
#6 23.57 Successfully installed black-24.10.0 mypy-extensions-1.0.0 pathspec-0.12.1 platformdirs-4.3.6
#6 23.57 WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager, possibly rendering your system unusable.It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv. Use the --root-user-action option if you know what you are doing and want to suppress this warning.
#6 DONE 24.0s

#7 [4/5] RUN cd /repo && pytest --collect-only -q
#7 1.049 /usr/local/lib/python3.10/site-packages/pytest_asyncio/plugin.py:207: PytestDeprecationWarning: The configuration option "asyncio_default_fixture_loop_scope" is unset.
#7 1.049 The event loop scope for asynchronous fixtures will default to the fixture caching scope. Future versions of pytest-asyncio will default the loop scope for asynchronous fixtures to function scope. Set the default fixture loop scope explicitly in order to avoid unexpected behavior in the future. Valid fixture loop scopes are: "function", "class", "module", "package", "session"
#7 1.049 
#7 1.049   warnings.warn(PytestDeprecationWarning(_DEFAULT_FIXTURE_LOOP_SCOPE_UNSET))
#7 1.655 tests/test_ollama.py::test_plugin_is_installed
#7 1.655 tests/test_ollama.py::test_registered_chat_models
#7 1.655 tests/test_ollama.py::test_registered_embedding_models
#7 1.655 tests/test_ollama.py::test_model_embed[None-True]
#7 1.655 tests/test_ollama.py::test_model_embed[True-True]
#7 1.655 tests/test_ollama.py::test_model_embed[true-True]
#7 1.655 tests/test_ollama.py::test_model_embed[yes-True]
#7 1.655 tests/test_ollama.py::test_model_embed[y-True]
#7 1.655 tests/test_ollama.py::test_model_embed[on-True]
#7 1.655 tests/test_ollama.py::test_model_embed[False-False]
#7 1.655 tests/test_ollama.py::test_model_embed[false-False]
#7 1.655 tests/test_ollama.py::test_model_embed[no-False]
#7 1.655 tests/test_ollama.py::test_model_embed[n-False]
#7 1.655 tests/test_ollama.py::test_model_embed[off-False]
#7 1.655 tests/test_ollama.py::test_registered_models_when_ollama_is_down
#7 1.655 tests/test_ollama.py::test_actual_run
#7 1.655 tests/test_ollama.py::test_async_ollama_call
#7 1.655 
#7 1.655 =============================== warnings summary ===============================
#7 1.655 ../usr/local/lib/python3.10/site-packages/pydantic/_internal/_config.py:295
#7 1.655 ../usr/local/lib/python3.10/site-packages/pydantic/_internal/_config.py:295
#7 1.655   /usr/local/lib/python3.10/site-packages/pydantic/_internal/_config.py:295: PydanticDeprecatedSince20: Support for class-based `config` is deprecated, use ConfigDict instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.10/migration/
#7 1.655     warnings.warn(DEPRECATION_MESSAGE, DeprecationWarning)
#7 1.655 
#7 1.655 -- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
#7 1.655 17 tests collected in 0.57s
#7 DONE 2.0s

#8 exporting to image
#8 exporting layers
#8 exporting layers 0.7s done
#8 writing image sha256:38704634ffd6fb70a45909acb329d4c0102e9e5209d06164cf676599ff04a1c8 done
#8 naming to docker.io/library/tmp:tmp done
#8 DONE 0.7s
