#0 building with "default" instance using docker driver

#1 [internal] load build definition from Dockerfile
#1 transferring dockerfile: 1.04kB done
#1 DONE 0.0s

#2 [internal] load metadata for docker.io/library/python:3.10
#2 DONE 0.0s

#3 [internal] load .dockerignore
#3 transferring context: 2B done
#3 DONE 0.0s

#4 [1/5] FROM docker.io/library/python:3.10
#4 DONE 0.0s

#5 [2/5] RUN mkdir -p ~/.pip && touch ~/.pip/pip.conf &&     echo "[global]" >> ~/.pip/pip.conf && echo "index-url=http://simple/" >> ~/.pip/pip.conf && echo "[install]" >> ~/.pip/pip.conf && echo "trusted-host=pypi..org" >> ~/.pip/pip.conf &&     apt-get update && apt-get install -y curl &&     curl -sSL https://install.python-poetry.org | python -
#5 CACHED

#6 [3/5] RUN pip install pytest pytest-xdist &&     pip install pipdeptree &&     git clone https://github.com/ucbepic/docetl.git &&     mkdir /repo &&     git config --global --add safe.directory /repo &&     cp -r /docetl/. /repo && rm -rf /docetl/ &&     rm -rf /docetl &&     cd /repo && git checkout 00a761fb5bd3e4af2668dd5f2e5c8dc5fe0837d6 &&     cd /repo && poetry install
#6 1.643 Looking in indexes: http://simple/
#6 1.799 Collecting pytest
#6 1.819   Downloading http://packages/pytest/pytest-8.3.4-py3-none-any.whl (343 kB)
#6 1.843      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 343.1/343.1 kB 16.8 MB/s eta 0:00:00
#6 1.918 Collecting pytest-xdist
#6 1.940   Downloading http://packages/pytest-xdist/pytest_xdist-3.6.1-py3-none-any.whl (46 kB)
#6 1.956      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 46.1/46.1 kB 3.3 MB/s eta 0:00:00
#6 2.028 Collecting tomli>=1
#6 2.046   Downloading http://packages/tomli/tomli-2.2.1-py3-none-any.whl (14 kB)
#6 2.109 Collecting packaging
#6 2.128   Downloading http://packages/packaging/packaging-24.2-py3-none-any.whl (65 kB)
#6 2.139      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 65.5/65.5 kB 7.4 MB/s eta 0:00:00
#6 2.186 Collecting pluggy<2,>=1.5
#6 2.205   Downloading http://packages/pluggy/pluggy-1.5.0-py3-none-any.whl (20 kB)
#6 2.256 Collecting exceptiongroup>=1.0.0rc8
#6 2.276   Downloading http://packages/exceptiongroup/exceptiongroup-1.2.2-py3-none-any.whl (16 kB)
#6 2.311 Collecting iniconfig
#6 2.334   Downloading http://packages/iniconfig/iniconfig-2.0.0-py3-none-any.whl (5.9 kB)
#6 2.413 Collecting execnet>=2.1
#6 2.433   Downloading http://packages/execnet/execnet-2.1.1-py3-none-any.whl (40 kB)
#6 2.442      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 40.6/40.6 kB 6.7 MB/s eta 0:00:00
#6 2.572 Installing collected packages: tomli, pluggy, packaging, iniconfig, execnet, exceptiongroup, pytest, pytest-xdist
#6 3.101 Successfully installed exceptiongroup-1.2.2 execnet-2.1.1 iniconfig-2.0.0 packaging-24.2 pluggy-1.5.0 pytest-8.3.4 pytest-xdist-3.6.1 tomli-2.2.1
#6 3.101 WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
#6 3.228 
#6 3.228 [notice] A new release of pip is available: 23.0.1 -> 24.3.1
#6 3.228 [notice] To update, run: pip install --upgrade pip
#6 3.998 Looking in indexes: http://simple/
#6 4.077 Collecting pipdeptree
#6 4.097   Downloading http://packages/pipdeptree/pipdeptree-2.24.0-py3-none-any.whl (32 kB)
#6 4.249 Collecting pip>=24.2
#6 4.261   Using cached http://packages/pip/pip-24.3.1-py3-none-any.whl (1.8 MB)
#6 4.282 Requirement already satisfied: packaging>=24.1 in /usr/local/lib/python3.10/site-packages (from pipdeptree) (24.2)
#6 4.403 Installing collected packages: pip, pipdeptree
#6 4.403   Attempting uninstall: pip
#6 4.404     Found existing installation: pip 23.0.1
#6 4.593     Uninstalling pip-23.0.1:
#6 4.750       Successfully uninstalled pip-23.0.1
#6 5.996 Successfully installed pip-24.3.1 pipdeptree-2.24.0
#6 5.997 WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
#6 6.161 Cloning into 'docetl'...
#6 13.91 fatal: reference is not a tree: 00a761fb5bd3e4af2668dd5f2e5c8dc5fe0837d6
#6 ERROR: process "/bin/sh -c pip install pytest pytest-xdist &&     pip install pipdeptree &&     git clone https://github.com/ucbepic/docetl.git &&     mkdir /repo &&     git config --global --add safe.directory /repo &&     cp -r /docetl/. /repo && rm -rf /docetl/ &&     rm -rf /docetl &&     cd /repo && git checkout 00a761fb5bd3e4af2668dd5f2e5c8dc5fe0837d6 &&     cd /repo && poetry install" did not complete successfully: exit code: 128
------
 > [3/5] RUN pip install pytest pytest-xdist &&     pip install pipdeptree &&     git clone https://github.com/ucbepic/docetl.git &&     mkdir /repo &&     git config --global --add safe.directory /repo &&     cp -r /docetl/. /repo && rm -rf /docetl/ &&     rm -rf /docetl &&     cd /repo && git checkout 00a761fb5bd3e4af2668dd5f2e5c8dc5fe0837d6 &&     cd /repo && poetry install:
4.282 Requirement already satisfied: packaging>=24.1 in /usr/local/lib/python3.10/site-packages (from pipdeptree) (24.2)
4.403 Installing collected packages: pip, pipdeptree
4.403   Attempting uninstall: pip
4.404     Found existing installation: pip 23.0.1
4.593     Uninstalling pip-23.0.1:
4.750       Successfully uninstalled pip-23.0.1
5.996 Successfully installed pip-24.3.1 pipdeptree-2.24.0
5.997 WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
6.161 Cloning into 'docetl'...
13.91 fatal: reference is not a tree: 00a761fb5bd3e4af2668dd5f2e5c8dc5fe0837d6
------
Dockerfile:11
--------------------
  10 |     ENV PATH="/root/.local/bin:$PATH"
  11 | >>> RUN pip install pytest pytest-xdist && \
  12 | >>>     pip install pipdeptree && \
  13 | >>>     git clone https://github.com/ucbepic/docetl.git && \
  14 | >>>     mkdir /repo && \
  15 | >>>     git config --global --add safe.directory /repo && \
  16 | >>>     cp -r /docetl/. /repo && rm -rf /docetl/ && \
  17 | >>>     rm -rf /docetl && \
  18 | >>>     cd /repo && git checkout 00a761fb5bd3e4af2668dd5f2e5c8dc5fe0837d6 && \
  19 | >>>     cd /repo && poetry install
  20 |     RUN cd /repo && pytest --collect-only -q
--------------------
ERROR: failed to solve: process "/bin/sh -c pip install pytest pytest-xdist &&     pip install pipdeptree &&     git clone https://github.com/ucbepic/docetl.git &&     mkdir /repo &&     git config --global --add safe.directory /repo &&     cp -r /docetl/. /repo && rm -rf /docetl/ &&     rm -rf /docetl &&     cd /repo && git checkout 00a761fb5bd3e4af2668dd5f2e5c8dc5fe0837d6 &&     cd /repo && poetry install" did not complete successfully: exit code: 128
