#0 building with "default" instance using docker driver

#1 [internal] load build definition from Dockerfile
#1 transferring dockerfile: 1.09kB done
#1 DONE 0.0s

#2 [internal] load metadata for docker.io/library/python:3.10
#2 DONE 0.0s

#3 [internal] load .dockerignore
#3 transferring context: 2B done
#3 DONE 0.0s

#4 [1/5] FROM docker.io/library/python:3.10
#4 DONE 0.0s

#5 [2/5] RUN mkdir -p ~/.pip && touch ~/.pip/pip.conf &&     echo "[global]" >> ~/.pip/pip.conf && echo "index-url=http://simple/" >> ~/.pip/pip.conf && echo "[install]" >> ~/.pip/pip.conf && echo "trusted-host=pypi..org" >> ~/.pip/pip.conf &&     apt-get update && apt-get install -y curl &&     curl -sSL https://install.python-poetry.org | python -
#5 CACHED

#6 [3/5] RUN pip install pytest pytest-xdist &&     pip install pipdeptree &&     git clone https://github.com/SpecterOps/cred1py.git &&     mkdir /repo &&     git config --global --add safe.directory /repo &&     cp -r /cred1py/. /repo && rm -rf /cred1py/ &&     rm -rf /cred1py &&     cd /repo && git checkout 432f9107b8ac501a743b487de182e3ba0bd3023f &&     pip install pycryptodome==3.21.0 &&     pip install scapy==2.6.0
#6 1.676 Looking in indexes: http://simple/
#6 1.833 Collecting pytest
#6 1.852   Downloading http://packages/pytest/pytest-8.3.4-py3-none-any.whl (343 kB)
#6 1.877      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 343.1/343.1 kB 17.1 MB/s eta 0:00:00
#6 1.949 Collecting pytest-xdist
#6 1.967   Downloading http://packages/pytest-xdist/pytest_xdist-3.6.1-py3-none-any.whl (46 kB)
#6 1.980      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 46.1/46.1 kB 4.3 MB/s eta 0:00:00
#6 2.042 Collecting pluggy<2,>=1.5
#6 2.061   Downloading http://packages/pluggy/pluggy-1.5.0-py3-none-any.whl (20 kB)
#6 2.094 Collecting iniconfig
#6 2.113   Downloading http://packages/iniconfig/iniconfig-2.0.0-py3-none-any.whl (5.9 kB)
#6 2.176 Collecting packaging
#6 2.198   Downloading http://packages/packaging/packaging-24.2-py3-none-any.whl (65 kB)
#6 2.214      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 65.5/65.5 kB 4.7 MB/s eta 0:00:00
#6 2.259 Collecting exceptiongroup>=1.0.0rc8
#6 2.283   Downloading http://packages/exceptiongroup/exceptiongroup-1.2.2-py3-none-any.whl (16 kB)
#6 2.346 Collecting tomli>=1
#6 2.370   Downloading http://packages/tomli/tomli-2.2.1-py3-none-any.whl (14 kB)
#6 2.443 Collecting execnet>=2.1
#6 2.461   Downloading http://packages/execnet/execnet-2.1.1-py3-none-any.whl (40 kB)
#6 2.469      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 40.6/40.6 kB 7.5 MB/s eta 0:00:00
#6 2.588 Installing collected packages: tomli, pluggy, packaging, iniconfig, execnet, exceptiongroup, pytest, pytest-xdist
#6 3.103 Successfully installed exceptiongroup-1.2.2 execnet-2.1.1 iniconfig-2.0.0 packaging-24.2 pluggy-1.5.0 pytest-8.3.4 pytest-xdist-3.6.1 tomli-2.2.1
#6 3.103 WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
#6 3.221 
#6 3.221 [notice] A new release of pip is available: 23.0.1 -> 24.3.1
#6 3.221 [notice] To update, run: pip install --upgrade pip
#6 3.897 Looking in indexes: http://simple/
#6 3.986 Collecting pipdeptree
#6 4.009   Downloading http://packages/pipdeptree/pipdeptree-2.24.0-py3-none-any.whl (32 kB)
#6 4.033 Requirement already satisfied: packaging>=24.1 in /usr/local/lib/python3.10/site-packages (from pipdeptree) (24.2)
#6 4.150 Collecting pip>=24.2
#6 4.161   Using cached http://packages/pip/pip-24.3.1-py3-none-any.whl (1.8 MB)
#6 4.285 Installing collected packages: pip, pipdeptree
#6 4.285   Attempting uninstall: pip
#6 4.286     Found existing installation: pip 23.0.1
#6 4.446     Uninstalling pip-23.0.1:
#6 4.592       Successfully uninstalled pip-23.0.1
#6 5.858 Successfully installed pip-24.3.1 pipdeptree-2.24.0
#6 5.859 WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
#6 6.030 Cloning into 'cred1py'...
#6 7.886 Note: switching to '432f9107b8ac501a743b487de182e3ba0bd3023f'.
#6 7.886 
#6 7.886 You are in 'detached HEAD' state. You can look around, make experimental
#6 7.886 changes and commit them, and you can discard any commits you make in this
#6 7.886 state without impacting any branches by switching back to a branch.
#6 7.886 
#6 7.886 If you want to create a new branch to retain commits you create, you may
#6 7.886 do so (now or later) by using -c with the switch command. Example:
#6 7.886 
#6 7.886   git switch -c <new-branch-name>
#6 7.886 
#6 7.886 Or undo this operation with:
#6 7.886 
#6 7.886   git switch -
#6 7.886 
#6 7.886 Turn off this advice by setting config variable advice.detachedHead to false
#6 7.886 
#6 7.886 HEAD is now at 432f910 Another... README update
#6 8.415 Looking in indexes: http://simple/
#6 8.706 Collecting pycryptodome==3.21.0
#6 8.724   Downloading http://packages/pycryptodome/pycryptodome-3.21.0-cp36-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (2.3 MB)
#6 8.772      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.3/2.3 MB 67.1 MB/s eta 0:00:00
#6 8.835 Installing collected packages: pycryptodome
#6 9.579 Successfully installed pycryptodome-3.21.0
#6 9.579 WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager, possibly rendering your system unusable.It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv. Use the --root-user-action option if you know what you are doing and want to suppress this warning.
#6 10.44 Looking in indexes: http://simple/
#6 10.48 Collecting scapy==2.6.0
#6 10.64   Downloading http://packages/scapy/scapy-2.6.0-py3-none-any.whl (2.4 MB)
#6 10.69      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.4/2.4 MB 66.0 MB/s eta 0:00:00
#6 10.74 Installing collected packages: scapy
#6 12.59 Successfully installed scapy-2.6.0
#6 12.59 WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager, possibly rendering your system unusable.It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv. Use the --root-user-action option if you know what you are doing and want to suppress this warning.
#6 DONE 13.0s

#7 [4/5] RUN cd /repo && pytest --collect-only -q
#7 0.901 tests/test_socks.py::test_init
#7 0.901 tests/test_socks.py::test_is_ip
#7 0.901 tests/test_socks.py::test_is_domain
#7 0.901 tests/test_socks.py::test_connect_no_auth
#7 0.901 tests/test_socks.py::test_connect_error_auth_required
#7 0.901 
#7 0.901 5 tests collected in 0.02s
#7 DONE 1.1s

#8 exporting to image
#8 exporting layers
#8 exporting layers 0.6s done
#8 writing image sha256:dee65891634cd81e8165b913dc887de2cd1f3736881c9b327cfed2900070a01b done
#8 naming to docker.io/library/tmp:tmp done
#8 DONE 0.6s
