#0 building with "default" instance using docker driver

#1 [internal] load build definition from Dockerfile
#1 transferring dockerfile: 1.17kB done
#1 DONE 0.0s

#2 [internal] load metadata for docker.io/library/python:3.10
#2 DONE 0.0s

#3 [internal] load .dockerignore
#3 transferring context: 2B done
#3 DONE 0.0s

#4 [1/5] FROM docker.io/library/python:3.10
#4 DONE 0.0s

#5 [2/5] RUN mkdir -p ~/.pip && touch ~/.pip/pip.conf &&     echo "[global]" >> ~/.pip/pip.conf && echo "index-url=http://simple/" >> ~/.pip/pip.conf && echo "[install]" >> ~/.pip/pip.conf && echo "trusted-host=pypi..org" >> ~/.pip/pip.conf &&     apt-get update && apt-get install -y curl &&     curl -sSL https://install.python-poetry.org | python -
#5 CACHED

#6 [3/5] RUN pip install pytest pytest-xdist &&     pip install pipdeptree &&     git clone https://github.com/reka-ai/reka-vibe-eval.git &&     mkdir /repo &&     git config --global --add safe.directory /repo &&     cp -r /reka-vibe-eval/. /repo && rm -rf /reka-vibe-eval/ &&     rm -rf /reka-vibe-eval &&     cd /repo && git checkout 93ecd92fec87ebda5263affba744df40cc233609 &&     pip install reka-api==1.0.6 &&     pip install requests==2.32.3 &&     pip install tqdm==4.67.1
#6 1.738 Looking in indexes: http://simple/
#6 1.893 Collecting pytest
#6 1.912   Downloading http://packages/pytest/pytest-8.3.4-py3-none-any.whl (343 kB)
#6 1.936      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 343.1/343.1 kB 17.3 MB/s eta 0:00:00
#6 2.006 Collecting pytest-xdist
#6 2.030   Downloading http://packages/pytest-xdist/pytest_xdist-3.6.1-py3-none-any.whl (46 kB)
#6 2.042      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 46.1/46.1 kB 4.8 MB/s eta 0:00:00
#6 2.104 Collecting pluggy<2,>=1.5
#6 2.128   Downloading http://packages/pluggy/pluggy-1.5.0-py3-none-any.whl (20 kB)
#6 2.161 Collecting iniconfig
#6 2.183   Downloading http://packages/iniconfig/iniconfig-2.0.0-py3-none-any.whl (5.9 kB)
#6 2.243 Collecting packaging
#6 2.261   Downloading http://packages/packaging/packaging-24.2-py3-none-any.whl (65 kB)
#6 2.273      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 65.5/65.5 kB 6.7 MB/s eta 0:00:00
#6 2.315 Collecting exceptiongroup>=1.0.0rc8
#6 2.332   Downloading http://packages/exceptiongroup/exceptiongroup-1.2.2-py3-none-any.whl (16 kB)
#6 2.393 Collecting tomli>=1
#6 2.412   Downloading http://packages/tomli/tomli-2.2.1-py3-none-any.whl (14 kB)
#6 2.482 Collecting execnet>=2.1
#6 2.502   Downloading http://packages/execnet/execnet-2.1.1-py3-none-any.whl (40 kB)
#6 2.511      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 40.6/40.6 kB 8.2 MB/s eta 0:00:00
#6 2.638 Installing collected packages: tomli, pluggy, packaging, iniconfig, execnet, exceptiongroup, pytest, pytest-xdist
#6 3.205 Successfully installed exceptiongroup-1.2.2 execnet-2.1.1 iniconfig-2.0.0 packaging-24.2 pluggy-1.5.0 pytest-8.3.4 pytest-xdist-3.6.1 tomli-2.2.1
#6 3.206 WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
#6 3.348 
#6 3.348 [notice] A new release of pip is available: 23.0.1 -> 24.3.1
#6 3.348 [notice] To update, run: pip install --upgrade pip
#6 4.092 Looking in indexes: http://simple/
#6 4.182 Collecting pipdeptree
#6 4.200   Downloading http://packages/pipdeptree/pipdeptree-2.24.0-py3-none-any.whl (32 kB)
#6 4.230 Requirement already satisfied: packaging>=24.1 in /usr/local/lib/python3.10/site-packages (from pipdeptree) (24.2)
#6 4.367 Collecting pip>=24.2
#6 4.380   Using cached http://packages/pip/pip-24.3.1-py3-none-any.whl (1.8 MB)
#6 4.529 Installing collected packages: pip, pipdeptree
#6 4.530   Attempting uninstall: pip
#6 4.531     Found existing installation: pip 23.0.1
#6 4.741     Uninstalling pip-23.0.1:
#6 4.932       Successfully uninstalled pip-23.0.1
#6 6.393 Successfully installed pip-24.3.1 pipdeptree-2.24.0
#6 6.393 WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
#6 6.674 Cloning into 'reka-vibe-eval'...
#6 9.098 Note: switching to '93ecd92fec87ebda5263affba744df40cc233609'.
#6 9.098 
#6 9.098 You are in 'detached HEAD' state. You can look around, make experimental
#6 9.098 changes and commit them, and you can discard any commits you make in this
#6 9.098 state without impacting any branches by switching back to a branch.
#6 9.098 
#6 9.098 If you want to create a new branch to retain commits you create, you may
#6 9.098 do so (now or later) by using -c with the switch command. Example:
#6 9.098 
#6 9.098   git switch -c <new-branch-name>
#6 9.098 
#6 9.098 Or undo this operation with:
#6 9.098 
#6 9.098   git switch -
#6 9.098 
#6 9.098 Turn off this advice by setting config variable advice.detachedHead to false
#6 9.098 
#6 9.098 HEAD is now at 93ecd92 Merge pull request #7 from reka-ai/matthen/fix-reka-api-dep
#6 9.716 Looking in indexes: http://simple/
#6 9.906 Collecting reka-api==1.0.6
#6 10.03   Downloading http://packages/reka-api/reka_api-1.0.6-py3-none-any.whl (15 kB)
#6 10.11 Collecting requests<3.0.0,>=2.31.0 (from reka-api==1.0.6)
#6 10.11   Using cached http://packages/requests/requests-2.32.3-py3-none-any.whl (64 kB)
#6 10.32 Collecting charset-normalizer<4,>=2 (from requests<3.0.0,>=2.31.0->reka-api==1.0.6)
#6 10.32   Using cached http://packages/charset-normalizer/charset_normalizer-3.4.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (146 kB)
#6 10.36 Collecting idna<4,>=2.5 (from requests<3.0.0,>=2.31.0->reka-api==1.0.6)
#6 10.36   Using cached http://packages/idna/idna-3.10-py3-none-any.whl (70 kB)
#6 10.45 Collecting urllib3<3,>=1.21.1 (from requests<3.0.0,>=2.31.0->reka-api==1.0.6)
#6 10.46   Using cached http://packages/urllib3/urllib3-2.3.0-py3-none-any.whl (128 kB)
#6 10.50 Collecting certifi>=2017.4.17 (from requests<3.0.0,>=2.31.0->reka-api==1.0.6)
#6 10.50   Using cached http://packages/certifi/certifi-2024.12.14-py3-none-any.whl (164 kB)
#6 10.55 Installing collected packages: urllib3, idna, charset-normalizer, certifi, requests, reka-api
#6 10.90 Successfully installed certifi-2024.12.14 charset-normalizer-3.4.1 idna-3.10 reka-api-1.0.6 requests-2.32.3 urllib3-2.3.0
#6 10.90 WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager, possibly rendering your system unusable.It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv. Use the --root-user-action option if you know what you are doing and want to suppress this warning.
#6 11.70 Looking in indexes: http://simple/
#6 11.70 Requirement already satisfied: requests==2.32.3 in /usr/local/lib/python3.10/site-packages (2.32.3)
#6 11.71 Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/site-packages (from requests==2.32.3) (3.4.1)
#6 11.71 Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/site-packages (from requests==2.32.3) (3.10)
#6 11.71 Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/site-packages (from requests==2.32.3) (2.3.0)
#6 11.71 Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/site-packages (from requests==2.32.3) (2024.12.14)
#6 11.75 WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager, possibly rendering your system unusable.It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv. Use the --root-user-action option if you know what you are doing and want to suppress this warning.
#6 12.47 Looking in indexes: http://simple/
#6 12.61 Collecting tqdm==4.67.1
#6 12.63   Downloading http://packages/tqdm/tqdm-4.67.1-py3-none-any.whl (78 kB)
#6 12.72 Installing collected packages: tqdm
#6 12.78 Successfully installed tqdm-4.67.1
#6 12.78 WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager, possibly rendering your system unusable.It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv. Use the --root-user-action option if you know what you are doing and want to suppress this warning.
#6 DONE 13.1s

#7 [4/5] RUN cd /repo && pytest --collect-only -q
#7 1.015 tests/test_data.py::test__vibe_eval_format
#7 1.015 tests/test_evaluate.py::test__make_evaluator_prompt__no_include_image
#7 1.015 tests/test_evaluate.py::test__make_evaluator_prompt__include_image
#7 1.015 
#7 1.015 3 tests collected in 0.18s
#7 DONE 1.2s

#8 exporting to image
#8 exporting layers
#8 exporting layers 0.3s done
#8 writing image sha256:f915cfb6146dbd6cdf80e7371e32a28c53447c980f11768ed23261cf4dd14b5f done
#8 naming to docker.io/library/tmp:tmp done
#8 DONE 0.3s
