2024-12-25T07:18:12.144072767Z [?2004hroot@b3426fc537fa:/# [7mexport http_proxy= https_proxy= no_proxy=.by[27m[7mt[27m[7med.org[27m[A[C[C[C[C[C[C[C[C[C[C[C[C[C[Cexport http_proxy= https_proxy= no_proxy=.d.org
2024-12-25T07:18:14.198514113Z [?2004l
[?2004hroot@b3426fc537fa:/# [7mmkdir -p ~/.pip && touch ~/.pip/pip.conf[27m
2024-12-25T07:18:14.566694885Z 
[7mecho "[global]" >> ~/.pip/pip.conf && echo "index-url=/simple/" >> ~/.pip/pip.conf && echo "[install]" >> ~/.pip/pip.co[27m[7mn[27m[7mf && echo "trusted-host=dpypi.d.org" >> ~/.pip/pip.conf[27m[A[A
[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[Cmkdir -p ~/.pip && touch ~/.pip/pip.conf
2024-12-25T07:18:14.566726508Z 
echo "[global]" >> ~/.pip/pip.conf && echo "index-url=/simple/" >> ~/.pip/pip.conf && echo "[install]" >> ~/.pip/pip.conf && echo "trusted-host=dpypi.d.org" >> ~/.pip/pip.conf
2024-12-25T07:18:17.285216139Z [?2004l
[?2004hroot@b3426fc537fa:/# [7mapt-get update && apt-get install -y curl[27m
[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[Capt-get update && apt-get install -y curl
2024-12-25T07:18:17.478006877Z [?2004l

0% [Working]
            
Get:1 http://deb.debian.org/debian bookworm InRelease [151 kB]
2024-12-25T07:18:17.849853357Z 
0% [1 InRelease 2676 B/151 kB 2%]
                                 
0% [Working]
0% [Waiting for headers]
                        
Get:2 http://deb.debian.org/debian bookworm-updates InRelease [55.4 kB]
2024-12-25T07:18:18.010584521Z 
0% [2 InRelease 821 B/55.4 kB 1%]
                                 
0% [Working]
0% [Waiting for headers]
                        
Get:3 http://deb.debian.org/debian-security bookworm-security InRelease [48.0 kB]
2024-12-25T07:18:18.111833755Z 
0% [3 InRelease 2011 B/48.0 kB 4%]
                                  
0% [Working]
16% [Waiting for headers]
                         
Get:4 http://deb.debian.org/debian bookworm/main amd64 Packages [8789 kB]
2024-12-25T07:18:18.660116113Z 
16% [4 Packages 2676 B/8789 kB 0%]
                                  
91% [Waiting for headers]
91% [4 Packages store 0 B] [Waiting for headers]
                                                
Get:5 http://deb.debian.org/debian bookworm-updates/main amd64 Packages [8856 B]
2024-12-25T07:18:18.818045031Z 
91% [4 Packages store 0 B] [5 Packages 8248 B/8856 B 93%]
                                                         
91% [4 Packages store 0 B] [Waiting for headers]
                                                
Get:6 http://deb.debian.org/debian-security bookworm-security/main amd64 Packages [236 kB]
2024-12-25T07:18:19.645106281Z 
92% [4 Packages store 0 B] [6 Packages 64.9 kB/236 kB 27%]
                                                          
93% [4 Packages store 0 B]
93% [4 Packages store 0 B]
                          
96% [Working]
96% [5 Packages store 0 B]
                          
98% [Working]
98% [6 Packages store 0 B]
                          
100% [Working]
              
Fetched 9288 kB in 2s (3958 kB/s)
2024-12-25T07:18:20.181054314Z 
Reading package lists... 0%

Reading package lists... 0%

Reading package lists... 0%

Reading package lists... 96%

Reading package lists... 96%

Reading package lists... 96%

Reading package lists... 96%

Reading package lists... 99%

Reading package lists... 99%

Reading package lists... Done

2024-12-25T07:18:20.710144992Z 
Reading package lists... 0%

Reading package lists... 0%

Reading package lists... 0%

Reading package lists... 96%

Reading package lists... 96%

Reading package lists... 96%

Reading package lists... 96%

Reading package lists... 99%

Reading package lists... 99%

Reading package lists... Done

2024-12-25T07:18:20.857161772Z 
Building dependency tree... 0%

Building dependency tree... 0%

Building dependency tree... 50%

Building dependency tree... 50%

Building dependency tree... Done

2024-12-25T07:18:20.857402863Z 
Reading state information... 0% 

Reading state information... 0%

Reading state information... Done

2024-12-25T07:18:20.861976552Z curl is already the newest version (7.88.1-10+deb12u8).
2024-12-25T07:18:21.004346966Z 0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
2024-12-25T07:18:21.887660754Z [?2004hroot@b3426fc537fa:/# [7mpip install pytest[27mpip install pytest
2024-12-25T07:18:23.504763456Z [?2004l
Looking in indexes: /simple/
2024-12-25T07:18:23.641113179Z Collecting pytest
2024-12-25T07:18:23.658233334Z   Downloading /packages/pytest/pytest-8.3.4-py3-none-any.whl (343 kB)
2024-12-25T07:18:23.680837621Z [?25l     [90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━[0m [32m0.0/343.1 kB[0m [31m?[0m eta [36m-:--:--[0m
[2K     [90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━[0m [32m343.1/343.1 kB[0m [31m19.1 MB/s[0m eta [36m0:00:00[0m
2024-12-25T07:18:23.751630118Z [?25hCollecting packaging
2024-12-25T07:18:23.781159897Z   Downloading /packages/packaging/packaging-24.2-py3-none-any.whl (65 kB)
2024-12-25T07:18:23.791985435Z [?25l     [90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━[0m [32m0.0/65.5 kB[0m [31m?[0m eta [36m-:--:--[0m
[2K     [90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━[0m [32m65.5/65.5 kB[0m [31m8.4 MB/s[0m eta [36m0:00:00[0m
2024-12-25T07:18:23.830343835Z [?25hCollecting exceptiongroup>=1.0.0rc8
2024-12-25T07:18:23.847113682Z   Downloading /packages/exceptiongroup/exceptiongroup-1.2.2-py3-none-any.whl (16 kB)
2024-12-25T07:18:23.889689663Z Collecting pluggy<2,>=1.5
2024-12-25T07:18:23.916036235Z   Downloading /packages/pluggy/pluggy-1.5.0-py3-none-any.whl (20 kB)
2024-12-25T07:18:23.942652271Z Collecting iniconfig
2024-12-25T07:18:23.960251370Z   Downloading /packages/iniconfig/iniconfig-2.0.0-py3-none-any.whl (5.9 kB)
2024-12-25T07:18:24.017602406Z Collecting tomli>=1
2024-12-25T07:18:24.034213767Z   Downloading /packages/tomli/tomli-2.2.1-py3-none-any.whl (14 kB)
2024-12-25T07:18:24.122016905Z Installing collected packages: tomli, pluggy, packaging, iniconfig, exceptiongroup, pytest
2024-12-25T07:18:24.442082055Z Successfully installed exceptiongroup-1.2.2 iniconfig-2.0.0 packaging-24.2 pluggy-1.5.0 pytest-8.3.4 tomli-2.2.1
2024-12-25T07:18:24.442236527Z [33mWARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv[0m[33m
2024-12-25T07:18:24.544822416Z [0m
2024-12-25T07:18:24.544848448Z [1m[[0m[34;49mnotice[0m[1;39;49m][0m[39;49m A new release of pip is available: [0m[31;49m23.0.1[0m[39;49m -> [0m[32;49m24.3.1[0m
2024-12-25T07:18:24.544852116Z [1m[[0m[34;49mnotice[0m[1;39;49m][0m[39;49m To update, run: [0m[32;49mpip install --upgrade pip[0m
2024-12-25T07:18:29.231797270Z [?2004hroot@b3426fc537fa:/# pip install pytest-django
2024-12-25T07:18:29.590681660Z [?2004l
Looking in indexes: /simple/
2024-12-25T07:18:29.660716924Z Collecting pytest-django
2024-12-25T07:18:29.719853107Z   Downloading /packages/pytest-django/pytest_django-4.9.0-py3-none-any.whl (23 kB)
2024-12-25T07:18:29.734056946Z Requirement already satisfied: pytest>=7.0.0 in /usr/local/lib/python3.10/site-packages (from pytest-django) (8.3.4)
2024-12-25T07:18:29.749543170Z Requirement already satisfied: pluggy<2,>=1.5 in /usr/local/lib/python3.10/site-packages (from pytest>=7.0.0->pytest-django) (1.5.0)
2024-12-25T07:18:29.749906333Z Requirement already satisfied: packaging in /usr/local/lib/python3.10/site-packages (from pytest>=7.0.0->pytest-django) (24.2)
2024-12-25T07:18:29.751240404Z Requirement already satisfied: tomli>=1 in /usr/local/lib/python3.10/site-packages (from pytest>=7.0.0->pytest-django) (2.2.1)
2024-12-25T07:18:29.752797147Z Requirement already satisfied: exceptiongroup>=1.0.0rc8 in /usr/local/lib/python3.10/site-packages (from pytest>=7.0.0->pytest-django) (1.2.2)
2024-12-25T07:18:29.753149016Z Requirement already satisfied: iniconfig in /usr/local/lib/python3.10/site-packages (from pytest>=7.0.0->pytest-django) (2.0.0)
2024-12-25T07:18:29.813711251Z Installing collected packages: pytest-django
2024-12-25T07:18:29.836336378Z Successfully installed pytest-django-4.9.0
2024-12-25T07:18:29.836641686Z [33mWARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv[0m[33m
2024-12-25T07:18:29.843343607Z [0m
2024-12-25T07:18:29.843358535Z [1m[[0m[34;49mnotice[0m[1;39;49m][0m[39;49m A new release of pip is available: [0m[31;49m23.0.1[0m[39;49m -> [0m[32;49m24.3.1[0m
2024-12-25T07:18:29.843362607Z [1m[[0m[34;49mnotice[0m[1;39;49m][0m[39;49m To update, run: [0m[32;49mpip install --upgrade pip[0m
2024-12-25T07:18:39.043305798Z [?2004hroot@b3426fc537fa:/# cd [K[K[Kgit clone [7mhttps://github.com/RealOrangeOne/django-tasks.git[27m
[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[Chttps://github.com/RealOrangeOne/django-tasks.git
2024-12-25T07:18:39.048391849Z [?2004l
Cloning into 'django-tasks'...
2024-12-25T07:18:40.598173439Z remote: Enumerating objects: 1450, done.[K
2024-12-25T07:18:40.616637052Z remote: Counting objects:   0% (1/550)[K
remote: Counting objects:   1% (6/550)[K
remote: Counting objects:   2% (11/550)[K
remote: Counting objects:   3% (17/550)[K
remote: Counting objects:   4% (22/550)[K
remote: Counting objects:   5% (28/550)[K
remote: Counting objects:   6% (33/550)[K
remote: Counting objects:   7% (39/550)[K
remote: Counting objects:   8% (44/550)[K
remote: Counting objects:   9% (50/550)[K
remote: Counting objects:  10% (55/550)[K
remote: Counting objects:  11% (61/550)[K
remote: Counting objects:  12% (66/550)[K
remote: Counting objects:  13% (72/550)[K
remote: Counting objects:  14% (77/550)[K
remote: Counting objects:  15% (83/550)[K
remote: Counting objects:  16% (88/550)[K
remote: Counting objects:  17% (94/550)[K
remote: Counting objects:  18% (99/550)[K
remote: Counting objects:  19% (105/550)[K
remote: Counting objects:  20% (110/550)[K
remote: Counting objects:  21% (116/550)[K
remote: Counting objects:  22% (121/550)[K
remote: Counting objects:  23% (127/550)[K
remote: Counting objects:  24% (132/550)[K
remote: Counting objects:  25% (138/550)[K
remote: Counting objects:  26% (143/550)[K
remote: Counting objects:  27% (149/550)[K
remote: Counting objects:  28% (154/550)[K
remote: Counting objects:  29% (160/550)[K
remote: Counting objects:  30% (165/550)[K
remote: Counting objects:  31% (171/550)[K
remote: Counting objects:  32% (176/550)[K
remote: Counting objects:  33% (182/550)[K
remote: Counting objects:  34% (187/550)[K
remote: Counting objects:  35% (193/550)[K
remote: Counting objects:  36% (198/550)[K
remote: Counting objects:  37% (204/550)[K
remote: Counting objects:  38% (209/550)[K
remote: Counting objects:  39% (215/550)[K
remote: Counting objects:  40% (220/550)[K
remote: Counting objects:  41% (226/550)[K
remote: Counting objects:  42% (231/550)[K
remote: Counting objects:  43% (237/550)[K
remote: Counting objects:  44% (242/550)[K
remote: Counting objects:  45% (248/550)[K
remote: Counting objects:  46% (253/550)[K
remote: Counting objects:  47% (259/550)[K
remote: Counting objects:  48% (264/550)[K
remote: Counting objects:  49% (270/550)[K
remote: Counting objects:  50% (275/550)[K
remote: Counting objects:  51% (281/550)[K
remote: Counting objects:  52% (286/550)[K
remote: Counting objects:  53% (292/550)[K
remote: Counting objects:  54% (297/550)[K
remote: Counting objects:  55% (303/550)[K
remote: Counting objects:  56% (308/550)[K
remote: Counting objects:  57% (314/550)[K
remote: Counting objects:  58% (319/550)[K
remote: Counting objects:  59% (325/550)[K
remote: Counting objects:  60% (330/550)[K
remote: Counting objects:  61% (336/550)[K
remote: Counting objects:  62% (341/550)[K
remote: Counting objects:  63% (347/550)[K
remote: Counting objects:  64% (352/550)[K
remote: Counting objects:  65% (358/550)[K
remote: Counting objects:  66% (363/550)[K
remote: Counting objects:  67% (369/550)[K
remote: Counting objects:  68% (374/550)[K
remote: Counting objects:  69% (380/550)[K
remote: Counting objects:  70% (385/550)[K
remote: Counting objects:  71% (391/550)[K
remote: Counting objects:  72% (396/550)[K
remote: Counting objects:  73% (402/550)[K
remote: Counting objects:  74% (407/550)[K
remote: Counting objects:  75% (413/550)[K
remote: Counting objects:  76% (418/550)[K
remote: Counting objects:  77% (424/550)[K
remote: Counting objects:  78% (429/550)[K
remote: Counting objects:  79% (435/550)[K
remote: Counting objects:  80% (440/550)[K
remote: Counting objects:  81% (446/550)[K
remote: Counting objects:  82% (451/550)[K
remote: Counting objects:  83% (457/550)[K
remote: Counting objects:  84% (462/550)[K
remote: Counting objects:  85% (468/550)[K
remote: Counting objects:  86% (473/550)[K
remote: Counting objects:  87% (479/550)[K
remote: Counting objects:  88% (484/550)[K
remote: Counting objects:  89% (490/550)[K
remote: Counting objects:  90% (495/550)[K
remote: Counting objects:  91% (501/550)[K
remote: Counting objects:  92% (506/550)[K
remote: Counting objects:  93% (512/550)[K
remote: Counting objects:  94% (517/550)[K
remote: Counting objects:  95% (523/550)[K
remote: Counting objects:  96% (528/550)[K
remote: Counting objects:  97% (534/550)[K
remote: Counting objects:  98% (539/550)[K
remote: Counting objects:  99% (545/550)[K
remote: Counting objects: 100% (550/550)[K
remote: Counting objects: 100% (550/550), done.[K
2024-12-25T07:18:40.626894431Z remote: Compressing objects:   0% (1/193)[K
remote: Compressing objects:   1% (2/193)[K
remote: Compressing objects:   2% (4/193)[K
remote: Compressing objects:   3% (6/193)[K
remote: Compressing objects:   4% (8/193)[K
remote: Compressing objects:   5% (10/193)[K
remote: Compressing objects:   6% (12/193)[K
remote: Compressing objects:   7% (14/193)[K
remote: Compressing objects:   8% (16/193)[K
remote: Compressing objects:   9% (18/193)[K
remote: Compressing objects:  10% (20/193)[K
remote: Compressing objects:  11% (22/193)[K
remote: Compressing objects:  12% (24/193)[K
remote: Compressing objects:  13% (26/193)[K
remote: Compressing objects:  14% (28/193)[K
remote: Compressing objects:  15% (29/193)[K
remote: Compressing objects:  16% (31/193)[K
remote: Compressing objects:  17% (33/193)[K
remote: Compressing objects:  18% (35/193)[K
remote: Compressing objects:  19% (37/193)[K
remote: Compressing objects:  20% (39/193)[K
remote: Compressing objects:  21% (41/193)[K
remote: Compressing objects:  22% (43/193)[K
remote: Compressing objects:  23% (45/193)[K
remote: Compressing objects:  24% (47/193)[K
remote: Compressing objects:  25% (49/193)[K
remote: Compressing objects:  26% (51/193)[K
remote: Compressing objects:  27% (53/193)[K
remote: Compressing objects:  28% (55/193)[K
remote: Compressing objects:  29% (56/193)[K
remote: Compressing objects:  30% (58/193)[K
remote: Compressing objects:  31% (60/193)[K
remote: Compressing objects:  32% (62/193)[K
remote: Compressing objects:  33% (64/193)[K
remote: Compressing objects:  34% (66/193)[K
remote: Compressing objects:  35% (68/193)[K
remote: Compressing objects:  36% (70/193)[K
remote: Compressing objects:  37% (72/193)[K
remote: Compressing objects:  38% (74/193)[K
remote: Compressing objects:  39% (76/193)[K
remote: Compressing objects:  40% (78/193)[K
remote: Compressing objects:  41% (80/193)[K
remote: Compressing objects:  42% (82/193)[K
remote: Compressing objects:  43% (83/193)[K
remote: Compressing objects:  44% (85/193)[K
remote: Compressing objects:  45% (87/193)[K
remote: Compressing objects:  46% (89/193)[K
remote: Compressing objects:  47% (91/193)[K
remote: Compressing objects:  48% (93/193)[K
remote: Compressing objects:  49% (95/193)[K
remote: Compressing objects:  50% (97/193)[K
remote: Compressing objects:  51% (99/193)[K
remote: Compressing objects:  52% (101/193)[K
remote: Compressing objects:  53% (103/193)[K
remote: Compressing objects:  54% (105/193)[K
remote: Compressing objects:  55% (107/193)[K
remote: Compressing objects:  56% (109/193)[K
remote: Compressing objects:  57% (111/193)[K
remote: Compressing objects:  58% (112/193)[K
remote: Compressing objects:  59% (114/193)[K
remote: Compressing objects:  60% (116/193)[K
remote: Compressing objects:  61% (118/193)[K
remote: Compressing objects:  62% (120/193)[K
remote: Compressing objects:  63% (122/193)[K
remote: Compressing objects:  64% (124/193)[K
remote: Compressing objects:  65% (126/193)[K
remote: Compressing objects:  66% (128/193)[K
remote: Compressing objects:  67% (130/193)[K
remote: Compressing objects:  68% (132/193)[K
remote: Compressing objects:  69% (134/193)[K
remote: Compressing objects:  70% (136/193)[K
remote: Compressing objects:  71% (138/193)[K
remote: Compressing objects:  72% (139/193)[K
remote: Compressing objects:  73% (141/193)[K
remote: Compressing objects:  74% (143/193)[K
remote: Compressing objects:  75% (145/193)[K
remote: Compressing objects:  76% (147/193)[K
remote: Compressing objects:  77% (149/193)[K
remote: Compressing objects:  78% (151/193)[K
remote: Compressing objects:  79% (153/193)[K
remote: Compressing objects:  80% (155/193)[K
remote: Compressing objects:  81% (157/193)[K
remote: Compressing objects:  82% (159/193)[K
remote: Compressing objects:  83% (161/193)[K
remote: Compressing objects:  84% (163/193)[K
remote: Compressing objects:  85% (165/193)[K
remote: Compressing objects:  86% (166/193)[K
remote: Compressing objects:  87% (168/193)[K
remote: Compressing objects:  88% (170/193)[K
remote: Compressing objects:  89% (172/193)[K
remote: Compressing objects:  90% (174/193)[K
remote: Compressing objects:  91% (176/193)[K
remote: Compressing objects:  92% (178/193)[K
remote: Compressing objects:  93% (180/193)[K
remote: Compressing objects:  94% (182/193)[K
remote: Compressing objects:  95% (184/193)[K
remote: Compressing objects:  96% (186/193)[K
remote: Compressing objects:  97% (188/193)[K
remote: Compressing objects:  98% (190/193)[K
remote: Compressing objects:  99% (192/193)[K
remote: Compressing objects: 100% (193/193)[K
remote: Compressing objects: 100% (193/193), done.[K
2024-12-25T07:18:40.929754176Z Receiving objects:   0% (1/1450)
Receiving objects:   1% (15/1450)
Receiving objects:   2% (29/1450)
Receiving objects:   3% (44/1450)
Receiving objects:   4% (58/1450)
Receiving objects:   5% (73/1450)
Receiving objects:   6% (87/1450)
Receiving objects:   7% (102/1450)
Receiving objects:   8% (116/1450)
Receiving objects:   9% (131/1450)
Receiving objects:  10% (145/1450)
Receiving objects:  11% (160/1450)
Receiving objects:  12% (174/1450)
Receiving objects:  13% (189/1450)
Receiving objects:  14% (203/1450)
Receiving objects:  15% (218/1450)
Receiving objects:  16% (232/1450)
Receiving objects:  17% (247/1450)
Receiving objects:  18% (261/1450)
Receiving objects:  19% (276/1450)
Receiving objects:  20% (290/1450)
Receiving objects:  21% (305/1450)
Receiving objects:  22% (319/1450)
Receiving objects:  23% (334/1450)
Receiving objects:  24% (348/1450)
Receiving objects:  25% (363/1450)
Receiving objects:  26% (377/1450)
Receiving objects:  27% (392/1450)
Receiving objects:  28% (406/1450)
Receiving objects:  29% (421/1450)
Receiving objects:  30% (435/1450)
Receiving objects:  31% (450/1450)
Receiving objects:  32% (464/1450)
Receiving objects:  33% (479/1450)
Receiving objects:  34% (493/1450)
Receiving objects:  35% (508/1450)
Receiving objects:  36% (522/1450)
Receiving objects:  37% (537/1450)
Receiving objects:  38% (551/1450)
Receiving objects:  39% (566/1450)
Receiving objects:  40% (580/1450)
Receiving objects:  41% (595/1450)
Receiving objects:  42% (609/1450)
Receiving objects:  43% (624/1450)
Receiving objects:  44% (638/1450)
Receiving objects:  45% (653/1450)
Receiving objects:  46% (667/1450)
Receiving objects:  47% (682/1450)
Receiving objects:  48% (696/1450)
Receiving objects:  49% (711/1450)
Receiving objects:  50% (725/1450)
Receiving objects:  51% (740/1450)
Receiving objects:  52% (754/1450)
Receiving objects:  53% (769/1450)
Receiving objects:  54% (783/1450)
Receiving objects:  55% (798/1450)
Receiving objects:  56% (812/1450)
Receiving objects:  57% (827/1450)
Receiving objects:  58% (841/1450)
Receiving objects:  59% (856/1450)
Receiving objects:  60% (870/1450)
Receiving objects:  61% (885/1450)
Receiving objects:  62% (899/1450)
Receiving objects:  63% (914/1450)
Receiving objects:  64% (928/1450)
Receiving objects:  65% (943/1450)
Receiving objects:  66% (957/1450)
Receiving objects:  67% (972/1450)
Receiving objects:  68% (986/1450)
Receiving objects:  69% (1001/1450)
Receiving objects:  70% (1015/1450)
Receiving objects:  71% (1030/1450)
Receiving objects:  72% (1044/1450)
Receiving objects:  73% (1059/1450)
Receiving objects:  74% (1073/1450)
Receiving objects:  75% (1088/1450)
Receiving objects:  76% (1102/1450)
Receiving objects:  77% (1117/1450)
Receiving objects:  78% (1131/1450)
Receiving objects:  79% (1146/1450)
Receiving objects:  80% (1160/1450)
Receiving objects:  81% (1175/1450)
Receiving objects:  82% (1189/1450)
Receiving objects:  83% (1204/1450)
Receiving objects:  84% (1218/1450)
Receiving objects:  85% (1233/1450)
Receiving objects:  86% (1247/1450)
Receiving objects:  87% (1262/1450)
Receiving objects:  88% (1276/1450)
Receiving objects:  89% (1291/1450)
Receiving objects:  90% (1305/1450)
Receiving objects:  91% (1320/1450)
Receiving objects:  92% (1334/1450)
Receiving objects:  93% (1349/1450)
Receiving objects:  94% (1363/1450)
Receiving objects:  95% (1378/1450)
Receiving objects:  96% (1392/1450)
Receiving objects:  97% (1407/1450)
Receiving objects:  98% (1421/1450)
Receiving objects:  99% (1436/1450)
remote: Total 1450 (delta 476), reused 357 (delta 357), pack-reused 900 (from 2)[K
2024-12-25T07:18:40.929787605Z Receiving objects: 100% (1450/1450)
Receiving objects: 100% (1450/1450), 321.25 KiB | 1.09 MiB/s, done.
2024-12-25T07:18:40.939445338Z Resolving deltas:   0% (0/958)
Resolving deltas:   1% (11/958)
Resolving deltas:   2% (20/958)
Resolving deltas:   3% (30/958)
Resolving deltas:   4% (40/958)
Resolving deltas:   5% (48/958)
Resolving deltas:   6% (59/958)
Resolving deltas:   7% (69/958)
Resolving deltas:   8% (78/958)
Resolving deltas:   9% (89/958)
Resolving deltas:  10% (96/958)
Resolving deltas:  11% (109/958)
Resolving deltas:  12% (117/958)
Resolving deltas:  13% (125/958)
Resolving deltas:  14% (135/958)
Resolving deltas:  15% (145/958)
Resolving deltas:  16% (154/958)
Resolving deltas:  17% (164/958)
Resolving deltas:  18% (173/958)
Resolving deltas:  19% (184/958)
Resolving deltas:  20% (193/958)
Resolving deltas:  21% (202/958)
Resolving deltas:  22% (213/958)
Resolving deltas:  23% (221/958)
Resolving deltas:  24% (231/958)
Resolving deltas:  25% (240/958)
Resolving deltas:  26% (254/958)
Resolving deltas:  27% (259/958)
Resolving deltas:  28% (269/958)
Resolving deltas:  29% (278/958)
Resolving deltas:  30% (288/958)
Resolving deltas:  31% (297/958)
Resolving deltas:  32% (307/958)
Resolving deltas:  33% (319/958)
Resolving deltas:  34% (326/958)
Resolving deltas:  35% (336/958)
Resolving deltas:  36% (345/958)
Resolving deltas:  37% (355/958)
Resolving deltas:  38% (365/958)
Resolving deltas:  39% (374/958)
Resolving deltas:  40% (384/958)
Resolving deltas:  41% (393/958)
Resolving deltas:  42% (404/958)
Resolving deltas:  43% (412/958)
Resolving deltas:  44% (422/958)
Resolving deltas:  45% (432/958)
Resolving deltas:  46% (441/958)
Resolving deltas:  47% (452/958)
Resolving deltas:  48% (461/958)
Resolving deltas:  49% (471/958)
Resolving deltas:  50% (479/958)
Resolving deltas:  51% (489/958)
Resolving deltas:  52% (500/958)
Resolving deltas:  53% (508/958)
Resolving deltas:  54% (518/958)
Resolving deltas:  55% (527/958)
Resolving deltas:  56% (539/958)
Resolving deltas:  57% (547/958)
Resolving deltas:  58% (556/958)
Resolving deltas:  59% (568/958)
Resolving deltas:  60% (575/958)
Resolving deltas:  61% (585/958)
Resolving deltas:  62% (601/958)
Resolving deltas:  63% (605/958)
Resolving deltas:  64% (614/958)
Resolving deltas:  65% (624/958)
Resolving deltas:  66% (633/958)
Resolving deltas:  67% (646/958)
Resolving deltas:  68% (653/958)
Resolving deltas:  69% (662/958)
Resolving deltas:  70% (671/958)
Resolving deltas:  71% (684/958)
Resolving deltas:  72% (690/958)
Resolving deltas:  73% (700/958)
Resolving deltas:  74% (711/958)
Resolving deltas:  75% (719/958)
Resolving deltas:  76% (731/958)
Resolving deltas:  77% (738/958)
Resolving deltas:  78% (748/958)
Resolving deltas:  79% (757/958)
Resolving deltas:  80% (768/958)
Resolving deltas:  81% (780/958)
Resolving deltas:  82% (788/958)
Resolving deltas:  83% (798/958)
Resolving deltas:  84% (805/958)
Resolving deltas:  85% (815/958)
Resolving deltas:  86% (826/958)
Resolving deltas:  87% (834/958)
Resolving deltas:  88% (846/958)
Resolving deltas:  89% (854/958)
Resolving deltas:  90% (863/958)
Resolving deltas:  91% (872/958)
Resolving deltas:  92% (882/958)
Resolving deltas:  93% (891/958)
Resolving deltas:  94% (901/958)
Resolving deltas:  95% (915/958)
Resolving deltas:  96% (920/958)
Resolving deltas:  97% (931/958)
Resolving deltas:  98% (939/958)
Resolving deltas:  99% (949/958)
Resolving deltas: 100% (958/958)
Resolving deltas: 100% (958/958), done.
2024-12-25T07:18:43.152030898Z [?2004hroot@b3426fc537fa:/# cd django-tasks/
2024-12-25T07:18:53.347855264Z [?2004l
[?2004hroot@b3426fc537fa:/django-tasks# git chek[Kckout [7me6d26ca2a233e86681b87c357d30af39f648dd9c[27me6d26ca2a233e86681b87c357d30af39f648dd9c
2024-12-25T07:18:53.352369685Z [?2004l
Note: switching to 'e6d26ca2a233e86681b87c357d30af39f648dd9c'.
2024-12-25T07:18:53.352395398Z 
2024-12-25T07:18:53.352399173Z You are in 'detached HEAD' state. You can look around, make experimental
2024-12-25T07:18:53.352402221Z changes and commit them, and you can discard any commits you make in this
2024-12-25T07:18:53.352405384Z state without impacting any branches by switching back to a branch.
2024-12-25T07:18:53.352408848Z 
2024-12-25T07:18:53.352411847Z If you want to create a new branch to retain commits you create, you may
2024-12-25T07:18:53.352416210Z do so (now or later) by using -c with the switch command. Example:
2024-12-25T07:18:53.352418449Z 
2024-12-25T07:18:53.352420388Z   git switch -c <new-branch-name>
2024-12-25T07:18:53.352422575Z 
2024-12-25T07:18:53.352424394Z Or undo this operation with:
2024-12-25T07:18:53.352426255Z 
2024-12-25T07:18:53.352427988Z   git switch -
2024-12-25T07:18:53.352430224Z 
2024-12-25T07:18:53.352432181Z Turn off this advice by setting config variable advice.detachedHead to false
2024-12-25T07:18:53.352434142Z 
2024-12-25T07:18:53.352435907Z HEAD is now at e6d26ca Version 0.6.0
2024-12-25T07:19:02.675099969Z [?2004hroot@b3426fc537fa:/django-tasks# [7mpytest --collect-only -q[27mpytest --collect-only -q
2024-12-25T07:19:03.217602283Z [?2004l

2024-12-25T07:19:03.217632822Z ==================================================================== ERRORS =====================================================================
2024-12-25T07:19:03.217636952Z [31m[1m_____________________________________________ ERROR collecting tests/tests/test_database_backend.py _____________________________________________[0m
2024-12-25T07:19:03.217641023Z [31mImportError while importing test module '/django-tasks/tests/tests/test_database_backend.py'.
2024-12-25T07:19:03.217645092Z Hint: make sure your test modules/packages have valid Python names.
2024-12-25T07:19:03.217648335Z Traceback:
2024-12-25T07:19:03.217651420Z /usr/local/lib/python3.10/importlib/__init__.py:126: in import_module
2024-12-25T07:19:03.217654796Z     return _bootstrap._gcd_import(name[level:], package, level)
2024-12-25T07:19:03.217658431Z tests/tests/test_database_backend.py:16: in <module>
2024-12-25T07:19:03.217661960Z     import django
2024-12-25T07:19:03.217664915Z E   ModuleNotFoundError: No module named 'django'[0m
2024-12-25T07:19:03.217668058Z [31m[1m______________________________________________ ERROR collecting tests/tests/test_dummy_backend.py _______________________________________________[0m
2024-12-25T07:19:03.217689052Z [31mImportError while importing test module '/django-tasks/tests/tests/test_dummy_backend.py'.
2024-12-25T07:19:03.217692690Z Hint: make sure your test modules/packages have valid Python names.
2024-12-25T07:19:03.217696236Z Traceback:
2024-12-25T07:19:03.217700018Z /usr/local/lib/python3.10/importlib/__init__.py:126: in import_module
2024-12-25T07:19:03.217702232Z     return _bootstrap._gcd_import(name[level:], package, level)
2024-12-25T07:19:03.217704143Z tests/tests/test_dummy_backend.py:4: in <module>
2024-12-25T07:19:03.217706105Z     from django.db import transaction
2024-12-25T07:19:03.217707974Z E   ModuleNotFoundError: No module named 'django'[0m
2024-12-25T07:19:03.217710036Z [31m[1m____________________________________________ ERROR collecting tests/tests/test_immediate_backend.py _____________________________________________[0m
2024-12-25T07:19:03.217712147Z [31mImportError while importing test module '/django-tasks/tests/tests/test_immediate_backend.py'.
2024-12-25T07:19:03.217714095Z Hint: make sure your test modules/packages have valid Python names.
2024-12-25T07:19:03.217715977Z Traceback:
2024-12-25T07:19:03.217717918Z /usr/local/lib/python3.10/importlib/__init__.py:126: in import_module
2024-12-25T07:19:03.217720071Z     return _bootstrap._gcd_import(name[level:], package, level)
2024-12-25T07:19:03.217723021Z tests/tests/test_immediate_backend.py:4: in <module>
2024-12-25T07:19:03.217726197Z     from django.db import transaction
2024-12-25T07:19:03.217736475Z E   ModuleNotFoundError: No module named 'django'[0m
2024-12-25T07:19:03.217739977Z [31m[1m__________________________________________________ ERROR collecting tests/tests/test_tasks.py ___________________________________________________[0m
2024-12-25T07:19:03.217743762Z [31mImportError while importing test module '/django-tasks/tests/tests/test_tasks.py'.
2024-12-25T07:19:03.217747358Z Hint: make sure your test modules/packages have valid Python names.
2024-12-25T07:19:03.217750600Z Traceback:
2024-12-25T07:19:03.217753506Z /usr/local/lib/python3.10/importlib/__init__.py:126: in import_module
2024-12-25T07:19:03.217756517Z     return _bootstrap._gcd_import(name[level:], package, level)
2024-12-25T07:19:03.217759530Z tests/tests/test_tasks.py:4: in <module>
2024-12-25T07:19:03.217762771Z     from django.test import SimpleTestCase, override_settings
2024-12-25T07:19:03.217766120Z E   ModuleNotFoundError: No module named 'django'[0m
2024-12-25T07:19:03.217769156Z [31m[1m__________________________________________________ ERROR collecting tests/tests/test_utils.py ___________________________________________________[0m
2024-12-25T07:19:03.217772523Z [31mImportError while importing test module '/django-tasks/tests/tests/test_utils.py'.
2024-12-25T07:19:03.217779863Z Hint: make sure your test modules/packages have valid Python names.
2024-12-25T07:19:03.217782950Z Traceback:
2024-12-25T07:19:03.217785892Z /usr/local/lib/python3.10/importlib/__init__.py:126: in import_module
2024-12-25T07:19:03.217788962Z     return _bootstrap._gcd_import(name[level:], package, level)
2024-12-25T07:19:03.217792065Z tests/tests/test_utils.py:5: in <module>
2024-12-25T07:19:03.217795070Z     from django.test import SimpleTestCase
2024-12-25T07:19:03.217798066Z E   ModuleNotFoundError: No module named 'django'[0m
2024-12-25T07:19:03.217965492Z [36m[1m============================================================ short test summary info ============================================================[0m
2024-12-25T07:19:03.217987429Z [31mERROR[0m tests/tests/test_database_backend.py
2024-12-25T07:19:03.217990058Z [31mERROR[0m tests/tests/test_dummy_backend.py
2024-12-25T07:19:03.217992198Z [31mERROR[0m tests/tests/test_immediate_backend.py
2024-12-25T07:19:03.217994186Z [31mERROR[0m tests/tests/test_tasks.py
2024-12-25T07:19:03.217996231Z [31mERROR[0m tests/tests/test_utils.py
2024-12-25T07:19:03.218023716Z !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 5 errors during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
2024-12-25T07:19:03.218080505Z [31m[33mno tests collected[0m, [31m5 errors[0m[31m in 0.27s[0m[0m
2024-12-25T07:19:19.214404390Z [?2004hroot@b3426fc537fa:/django-tasks# export [7mDJANGO_SETTINGS_MODULE[27mDJANGO_SETTINGS_MODULE=tests.settings
2024-12-25T07:19:20.084845748Z [?2004l
[?2004hroot@b3426fc537fa:/django-tasks# export DJANGO_SETTINGS_MODULE=tests.settings
[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[20Ppytest --collect-only -q
2024-12-25T07:19:20.253515169Z [?2004l
Traceback (most recent call last):
2024-12-25T07:19:20.253538268Z   File "/usr/local/bin/pytest", line 8, in <module>
2024-12-25T07:19:20.253541297Z     sys.exit(console_main())
2024-12-25T07:19:20.253543459Z   File "/usr/local/lib/python3.10/site-packages/_pytest/config/__init__.py", line 201, in console_main
2024-12-25T07:19:20.253545817Z     code = main()
2024-12-25T07:19:20.253547848Z   File "/usr/local/lib/python3.10/site-packages/_pytest/config/__init__.py", line 156, in main
2024-12-25T07:19:20.253549887Z     config = _prepareconfig(args, plugins)
2024-12-25T07:19:20.253552052Z   File "/usr/local/lib/python3.10/site-packages/_pytest/config/__init__.py", line 341, in _prepareconfig
2024-12-25T07:19:20.253554201Z     config = pluginmanager.hook.pytest_cmdline_parse(
2024-12-25T07:19:20.253566213Z   File "/usr/local/lib/python3.10/site-packages/pluggy/_hooks.py", line 513, in __call__
2024-12-25T07:19:20.253568436Z     return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
2024-12-25T07:19:20.253570479Z   File "/usr/local/lib/python3.10/site-packages/pluggy/_manager.py", line 120, in _hookexec
2024-12-25T07:19:20.253572552Z     return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
2024-12-25T07:19:20.253574564Z   File "/usr/local/lib/python3.10/site-packages/pluggy/_callers.py", line 139, in _multicall
2024-12-25T07:19:20.253576630Z     raise exception.with_traceback(exception.__traceback__)
2024-12-25T07:19:20.253578734Z   File "/usr/local/lib/python3.10/site-packages/pluggy/_callers.py", line 122, in _multicall
2024-12-25T07:19:20.253580765Z     teardown.throw(exception)  # type: ignore[union-attr]
2024-12-25T07:19:20.253582664Z   File "/usr/local/lib/python3.10/site-packages/_pytest/helpconfig.py", line 105, in pytest_cmdline_parse
2024-12-25T07:19:20.253584723Z     config = yield
2024-12-25T07:19:20.253586555Z   File "/usr/local/lib/python3.10/site-packages/pluggy/_callers.py", line 103, in _multicall
2024-12-25T07:19:20.253588575Z     res = hook_impl.function(*args)
2024-12-25T07:19:20.253590433Z   File "/usr/local/lib/python3.10/site-packages/_pytest/config/__init__.py", line 1140, in pytest_cmdline_parse
2024-12-25T07:19:20.253592530Z     self.parse(args)
2024-12-25T07:19:20.253594412Z   File "/usr/local/lib/python3.10/site-packages/_pytest/config/__init__.py", line 1494, in parse
2024-12-25T07:19:20.253596377Z     self._preparse(args, addopts=addopts)
2024-12-25T07:19:20.253598236Z   File "/usr/local/lib/python3.10/site-packages/_pytest/config/__init__.py", line 1398, in _preparse
2024-12-25T07:19:20.253600285Z     self.hook.pytest_load_initial_conftests(
2024-12-25T07:19:20.253602215Z   File "/usr/local/lib/python3.10/site-packages/pluggy/_hooks.py", line 513, in __call__
2024-12-25T07:19:20.253604218Z     return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
2024-12-25T07:19:20.253607145Z   File "/usr/local/lib/python3.10/site-packages/pluggy/_manager.py", line 120, in _hookexec
2024-12-25T07:19:20.253609267Z     return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
2024-12-25T07:19:20.253611207Z   File "/usr/local/lib/python3.10/site-packages/pluggy/_callers.py", line 139, in _multicall
2024-12-25T07:19:20.253613187Z     raise exception.with_traceback(exception.__traceback__)
2024-12-25T07:19:20.253615066Z   File "/usr/local/lib/python3.10/site-packages/pluggy/_callers.py", line 122, in _multicall
2024-12-25T07:19:20.253617001Z     teardown.throw(exception)  # type: ignore[union-attr]
2024-12-25T07:19:20.253618887Z   File "/usr/local/lib/python3.10/site-packages/_pytest/warnings.py", line 151, in pytest_load_initial_conftests
2024-12-25T07:19:20.253623239Z     return (yield)
2024-12-25T07:19:20.253625100Z   File "/usr/local/lib/python3.10/site-packages/pluggy/_callers.py", line 122, in _multicall
2024-12-25T07:19:20.253632347Z     teardown.throw(exception)  # type: ignore[union-attr]
2024-12-25T07:19:20.253634326Z   File "/usr/local/lib/python3.10/site-packages/_pytest/capture.py", line 154, in pytest_load_initial_conftests
2024-12-25T07:19:20.253636350Z     yield
2024-12-25T07:19:20.253638246Z   File "/usr/local/lib/python3.10/site-packages/pluggy/_callers.py", line 103, in _multicall
2024-12-25T07:19:20.253640309Z     res = hook_impl.function(*args)
2024-12-25T07:19:20.253642187Z   File "/usr/local/lib/python3.10/site-packages/pytest_django/plugin.py", line 354, in pytest_load_initial_conftests
2024-12-25T07:19:20.253644262Z     from django.conf import settings as dj_settings
2024-12-25T07:19:20.253646286Z ModuleNotFoundError: No module named 'django'
2024-12-25T07:19:25.633326500Z [?2004hroot@b3426fc537fa:/django-tasks# ls
2024-12-25T07:19:25.634684303Z [?2004l
CONTRIBUTING.md  LICENSE  README.md  django_tasks  docker-compose.yml  justfile  manage.py  pyproject.toml  tests
2024-12-25T07:19:53.055515287Z [?2004hroot@b3426fc537fa:/django-tasks# pip install [K[K[K[K[K[K[K[K[K[K[K[Kvim [K[K[K[K[7mpython -m pip install django-tasks[27mpython -m pip install django-tasks
2024-12-25T07:19:53.408224316Z [?2004l
Looking in indexes: /simple/
2024-12-25T07:19:53.556724174Z Collecting django-tasks
2024-12-25T07:19:53.683977204Z   Downloading /packages/django-tasks/django_tasks-0.6.0-py3-none-any.whl (36 kB)
2024-12-25T07:19:53.738499621Z Collecting django-stubs-ext
2024-12-25T07:19:53.829497604Z   Downloading /packages/django-stubs-ext/django_stubs_ext-5.1.1-py3-none-any.whl (9.0 kB)
2024-12-25T07:19:53.880175922Z Collecting typing_extensions
2024-12-25T07:19:53.896700505Z   Downloading /packages/typing-extensions/typing_extensions-4.12.2-py3-none-any.whl (37 kB)
2024-12-25T07:19:54.101313545Z Collecting Django>=4.2
2024-12-25T07:19:54.120737767Z   Downloading /packages/django/Django-5.1.4-py3-none-any.whl (8.3 MB)
2024-12-25T07:19:54.203135304Z [?25l     [90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━[0m [32m0.0/8.3 MB[0m [31m?[0m eta [36m-:--:--[0m
[2K     [91m━━━━━━━━━━━━━━━━━[0m[90m╺[0m[90m━━━━━━━━━━━━━━━━━━━━━━[0m [32m3.6/8.3 MB[0m [31m107.5 MB/s[0m eta [36m0:00:01[0m
[2K     [91m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━[0m[91m╸[0m [32m8.3/8.3 MB[0m [31m158.7 MB/s[0m eta [36m0:00:01[0m
[2K     [90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━[0m [32m8.3/8.3 MB[0m [31m106.3 MB/s[0m eta [36m0:00:00[0m
2024-12-25T07:19:54.299046264Z [?25hCollecting asgiref<4,>=3.8.1
2024-12-25T07:19:54.314973083Z   Downloading /packages/asgiref/asgiref-3.8.1-py3-none-any.whl (23 kB)
2024-12-25T07:19:54.352255196Z Collecting sqlparse>=0.3.1
2024-12-25T07:19:54.374490042Z   Downloading /packages/sqlparse/sqlparse-0.5.3-py3-none-any.whl (44 kB)
2024-12-25T07:19:54.384313769Z [?25l     [90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━[0m [32m0.0/44.4 kB[0m [31m?[0m eta [36m-:--:--[0m
[2K     [90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━[0m [32m44.4/44.4 kB[0m [31m6.1 MB/s[0m eta [36m0:00:00[0m
2024-12-25T07:19:54.540227787Z [?25hInstalling collected packages: typing_extensions, sqlparse, asgiref, Django, django-stubs-ext, django-tasks
2024-12-25T07:19:56.415784799Z Successfully installed Django-5.1.4 asgiref-3.8.1 django-stubs-ext-5.1.1 django-tasks-0.6.0 sqlparse-0.5.3 typing_extensions-4.12.2
2024-12-25T07:19:56.415953969Z [33mWARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv[0m[33m
2024-12-25T07:19:56.419618340Z [0m
2024-12-25T07:19:56.419642620Z [1m[[0m[34;49mnotice[0m[1;39;49m][0m[39;49m A new release of pip is available: [0m[31;49m23.0.1[0m[39;49m -> [0m[32;49m24.3.1[0m
2024-12-25T07:19:56.419646625Z [1m[[0m[34;49mnotice[0m[1;39;49m][0m[39;49m To update, run: [0m[32;49mpip install --upgrade pip[0m
2024-12-25T07:19:57.978672742Z [?2004hroot@b3426fc537fa:/django-tasks# python -m pip install django-tasksls[K
2024-12-25T07:19:57.979994067Z [?2004l
CONTRIBUTING.md  LICENSE  README.md  django_tasks  docker-compose.yml  justfile  manage.py  pyproject.toml  tests
2024-12-25T07:20:00.065038394Z [?2004hroot@b3426fc537fa:/django-tasks# lspython -m pip install django-tasksls[Kpytest --collect-only -q
2024-12-25T07:20:00.277397962Z [?2004l
Traceback (most recent call last):
2024-12-25T07:20:00.277428773Z   File "/usr/local/bin/pytest", line 8, in <module>
2024-12-25T07:20:00.277431883Z     sys.exit(console_main())
2024-12-25T07:20:00.277434320Z   File "/usr/local/lib/python3.10/site-packages/_pytest/config/__init__.py", line 201, in console_main
2024-12-25T07:20:00.277436651Z     code = main()
2024-12-25T07:20:00.277438737Z   File "/usr/local/lib/python3.10/site-packages/_pytest/config/__init__.py", line 156, in main
2024-12-25T07:20:00.277441108Z     config = _prepareconfig(args, plugins)
2024-12-25T07:20:00.277443102Z   File "/usr/local/lib/python3.10/site-packages/_pytest/config/__init__.py", line 341, in _prepareconfig
2024-12-25T07:20:00.277445179Z     config = pluginmanager.hook.pytest_cmdline_parse(
2024-12-25T07:20:00.277447462Z   File "/usr/local/lib/python3.10/site-packages/pluggy/_hooks.py", line 513, in __call__
2024-12-25T07:20:00.277460206Z     return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
2024-12-25T07:20:00.277462541Z   File "/usr/local/lib/python3.10/site-packages/pluggy/_manager.py", line 120, in _hookexec
2024-12-25T07:20:00.277464589Z     return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
2024-12-25T07:20:00.277466651Z   File "/usr/local/lib/python3.10/site-packages/pluggy/_callers.py", line 139, in _multicall
2024-12-25T07:20:00.277468662Z     raise exception.with_traceback(exception.__traceback__)
2024-12-25T07:20:00.277470956Z   File "/usr/local/lib/python3.10/site-packages/pluggy/_callers.py", line 122, in _multicall
2024-12-25T07:20:00.277472938Z     teardown.throw(exception)  # type: ignore[union-attr]
2024-12-25T07:20:00.277475054Z   File "/usr/local/lib/python3.10/site-packages/_pytest/helpconfig.py", line 105, in pytest_cmdline_parse
2024-12-25T07:20:00.277477305Z     config = yield
2024-12-25T07:20:00.277479165Z   File "/usr/local/lib/python3.10/site-packages/pluggy/_callers.py", line 103, in _multicall
2024-12-25T07:20:00.277481161Z     res = hook_impl.function(*args)
2024-12-25T07:20:00.277483128Z   File "/usr/local/lib/python3.10/site-packages/_pytest/config/__init__.py", line 1140, in pytest_cmdline_parse
2024-12-25T07:20:00.277485173Z     self.parse(args)
2024-12-25T07:20:00.277487098Z   File "/usr/local/lib/python3.10/site-packages/_pytest/config/__init__.py", line 1494, in parse
2024-12-25T07:20:00.277489083Z     self._preparse(args, addopts=addopts)
2024-12-25T07:20:00.277491026Z   File "/usr/local/lib/python3.10/site-packages/_pytest/config/__init__.py", line 1398, in _preparse
2024-12-25T07:20:00.277493018Z     self.hook.pytest_load_initial_conftests(
2024-12-25T07:20:00.277494924Z   File "/usr/local/lib/python3.10/site-packages/pluggy/_hooks.py", line 513, in __call__
2024-12-25T07:20:00.277496919Z     return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
2024-12-25T07:20:00.277513565Z   File "/usr/local/lib/python3.10/site-packages/pluggy/_manager.py", line 120, in _hookexec
2024-12-25T07:20:00.277515734Z     return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
2024-12-25T07:20:00.277517677Z   File "/usr/local/lib/python3.10/site-packages/pluggy/_callers.py", line 139, in _multicall
2024-12-25T07:20:00.277519657Z     raise exception.with_traceback(exception.__traceback__)
2024-12-25T07:20:00.277521711Z   File "/usr/local/lib/python3.10/site-packages/pluggy/_callers.py", line 122, in _multicall
2024-12-25T07:20:00.277523802Z     teardown.throw(exception)  # type: ignore[union-attr]
2024-12-25T07:20:00.277525737Z   File "/usr/local/lib/python3.10/site-packages/_pytest/warnings.py", line 151, in pytest_load_initial_conftests
2024-12-25T07:20:00.277528490Z     return (yield)
2024-12-25T07:20:00.277530684Z   File "/usr/local/lib/python3.10/site-packages/pluggy/_callers.py", line 122, in _multicall
2024-12-25T07:20:00.277532664Z     teardown.throw(exception)  # type: ignore[union-attr]
2024-12-25T07:20:00.277534615Z   File "/usr/local/lib/python3.10/site-packages/_pytest/capture.py", line 154, in pytest_load_initial_conftests
2024-12-25T07:20:00.277536647Z     yield
2024-12-25T07:20:00.277538600Z   File "/usr/local/lib/python3.10/site-packages/pluggy/_callers.py", line 103, in _multicall
2024-12-25T07:20:00.277540698Z     res = hook_impl.function(*args)
2024-12-25T07:20:00.277542603Z   File "/usr/local/lib/python3.10/site-packages/pytest_django/plugin.py", line 356, in pytest_load_initial_conftests
2024-12-25T07:20:00.277544665Z     with _handle_import_error(_django_project_scan_outcome):
2024-12-25T07:20:00.277546651Z   File "/usr/local/lib/python3.10/contextlib.py", line 153, in __exit__
2024-12-25T07:20:00.277548599Z     self.gen.throw(typ, value, traceback)
2024-12-25T07:20:00.277550487Z   File "/usr/local/lib/python3.10/site-packages/pytest_django/plugin.py", line 184, in _handle_import_error
2024-12-25T07:20:00.277552492Z     raise ImportError(msg) from None
2024-12-25T07:20:00.277554421Z ImportError: No module named 'dj_database_url'
2024-12-25T07:20:00.277556332Z 
2024-12-25T07:20:00.277558189Z pytest-django found a Django project in /django-tasks (it contains manage.py) and added it to the Python path.
2024-12-25T07:20:00.277560963Z If this is wrong, add "django_find_project = false" to pytest.ini and explicitly manage your Python path.
2024-12-25T07:20:20.657003571Z [?2004hroot@b3426fc537fa:/django-tasks# python3 [K[K[K[K[K[K[K[Kpython3 manage.py 
2024-12-25T07:20:20.759231929Z [?2004l

2024-12-25T07:20:20.759279568Z Type 'manage.py help <subcommand>' for help on a specific subcommand.
2024-12-25T07:20:20.759283695Z 
2024-12-25T07:20:20.759296368Z Available subcommands:
2024-12-25T07:20:20.759298556Z 
2024-12-25T07:20:20.759300650Z [31m[django][0m
2024-12-25T07:20:20.759302734Z     check
2024-12-25T07:20:20.759304674Z     compilemessages
2024-12-25T07:20:20.759306565Z     createcachetable
2024-12-25T07:20:20.759308393Z     dbshell
2024-12-25T07:20:20.759310226Z     diffsettings
2024-12-25T07:20:20.759312137Z     dumpdata
2024-12-25T07:20:20.759313956Z     flush
2024-12-25T07:20:20.759315774Z     inspectdb
2024-12-25T07:20:20.759317599Z     loaddata
2024-12-25T07:20:20.759319467Z     makemessages
2024-12-25T07:20:20.759321361Z     makemigrations
2024-12-25T07:20:20.759323196Z     migrate
2024-12-25T07:20:20.759325016Z     optimizemigration
2024-12-25T07:20:20.759326874Z     runserver
2024-12-25T07:20:20.759328699Z     sendtestemail
2024-12-25T07:20:20.759330536Z     shell
2024-12-25T07:20:20.759332349Z     showmigrations
2024-12-25T07:20:20.759334183Z     sqlflush
2024-12-25T07:20:20.759335993Z     sqlmigrate
2024-12-25T07:20:20.759337828Z     sqlsequencereset
2024-12-25T07:20:20.759339765Z     squashmigrations
2024-12-25T07:20:20.759341619Z     startapp
2024-12-25T07:20:20.759343402Z     startproject
2024-12-25T07:20:20.759345252Z     test
2024-12-25T07:20:20.759347113Z     testserver
2024-12-25T07:20:20.759349030Z [31mNote that only Django core commands are listed as settings are not properly configured (error: No module named 'dj_database_url').[0m
2024-12-25T07:20:21.953055173Z [?2004hroot@b3426fc537fa:/django-tasks# python3 manage.py est --collect-only -q
2024-12-25T07:20:22.147408534Z [?2004l
Traceback (most recent call last):
2024-12-25T07:20:22.147433986Z   File "/usr/local/bin/pytest", line 8, in <module>
2024-12-25T07:20:22.147437042Z     sys.exit(console_main())
2024-12-25T07:20:22.147439206Z   File "/usr/local/lib/python3.10/site-packages/_pytest/config/__init__.py", line 201, in console_main
2024-12-25T07:20:22.147441452Z     code = main()
2024-12-25T07:20:22.147443520Z   File "/usr/local/lib/python3.10/site-packages/_pytest/config/__init__.py", line 156, in main
2024-12-25T07:20:22.147445609Z     config = _prepareconfig(args, plugins)
2024-12-25T07:20:22.147447623Z   File "/usr/local/lib/python3.10/site-packages/_pytest/config/__init__.py", line 341, in _prepareconfig
2024-12-25T07:20:22.147458491Z     config = pluginmanager.hook.pytest_cmdline_parse(
2024-12-25T07:20:22.147471377Z   File "/usr/local/lib/python3.10/site-packages/pluggy/_hooks.py", line 513, in __call__
2024-12-25T07:20:22.147473720Z     return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
2024-12-25T07:20:22.147475823Z   File "/usr/local/lib/python3.10/site-packages/pluggy/_manager.py", line 120, in _hookexec
2024-12-25T07:20:22.147477851Z     return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
2024-12-25T07:20:22.147479892Z   File "/usr/local/lib/python3.10/site-packages/pluggy/_callers.py", line 139, in _multicall
2024-12-25T07:20:22.147481920Z     raise exception.with_traceback(exception.__traceback__)
2024-12-25T07:20:22.147483896Z   File "/usr/local/lib/python3.10/site-packages/pluggy/_callers.py", line 122, in _multicall
2024-12-25T07:20:22.147485861Z     teardown.throw(exception)  # type: ignore[union-attr]
2024-12-25T07:20:22.147487840Z   File "/usr/local/lib/python3.10/site-packages/_pytest/helpconfig.py", line 105, in pytest_cmdline_parse
2024-12-25T07:20:22.147489881Z     config = yield
2024-12-25T07:20:22.147491718Z   File "/usr/local/lib/python3.10/site-packages/pluggy/_callers.py", line 103, in _multicall
2024-12-25T07:20:22.147493667Z     res = hook_impl.function(*args)
2024-12-25T07:20:22.147495631Z   File "/usr/local/lib/python3.10/site-packages/_pytest/config/__init__.py", line 1140, in pytest_cmdline_parse
2024-12-25T07:20:22.147497674Z     self.parse(args)
2024-12-25T07:20:22.147499554Z   File "/usr/local/lib/python3.10/site-packages/_pytest/config/__init__.py", line 1494, in parse
2024-12-25T07:20:22.147501604Z     self._preparse(args, addopts=addopts)
2024-12-25T07:20:22.147503599Z   File "/usr/local/lib/python3.10/site-packages/_pytest/config/__init__.py", line 1398, in _preparse
2024-12-25T07:20:22.147505888Z     self.hook.pytest_load_initial_conftests(
2024-12-25T07:20:22.147507789Z   File "/usr/local/lib/python3.10/site-packages/pluggy/_hooks.py", line 513, in __call__
2024-12-25T07:20:22.147509783Z     return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
2024-12-25T07:20:22.147512521Z   File "/usr/local/lib/python3.10/site-packages/pluggy/_manager.py", line 120, in _hookexec
2024-12-25T07:20:22.147514535Z     return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
2024-12-25T07:20:22.147516597Z   File "/usr/local/lib/python3.10/site-packages/pluggy/_callers.py", line 139, in _multicall
2024-12-25T07:20:22.147518560Z     raise exception.with_traceback(exception.__traceback__)
2024-12-25T07:20:22.147520465Z   File "/usr/local/lib/python3.10/site-packages/pluggy/_callers.py", line 122, in _multicall
2024-12-25T07:20:22.147522415Z     teardown.throw(exception)  # type: ignore[union-attr]
2024-12-25T07:20:22.147524304Z   File "/usr/local/lib/python3.10/site-packages/_pytest/warnings.py", line 151, in pytest_load_initial_conftests
2024-12-25T07:20:22.147528446Z     return (yield)
2024-12-25T07:20:22.147530318Z   File "/usr/local/lib/python3.10/site-packages/pluggy/_callers.py", line 122, in _multicall
2024-12-25T07:20:22.147532281Z     teardown.throw(exception)  # type: ignore[union-attr]
2024-12-25T07:20:22.147534202Z   File "/usr/local/lib/python3.10/site-packages/_pytest/capture.py", line 154, in pytest_load_initial_conftests
2024-12-25T07:20:22.147536214Z     yield
2024-12-25T07:20:22.147538055Z   File "/usr/local/lib/python3.10/site-packages/pluggy/_callers.py", line 103, in _multicall
2024-12-25T07:20:22.147540019Z     res = hook_impl.function(*args)
2024-12-25T07:20:22.147541889Z   File "/usr/local/lib/python3.10/site-packages/pytest_django/plugin.py", line 356, in pytest_load_initial_conftests
2024-12-25T07:20:22.147543948Z     with _handle_import_error(_django_project_scan_outcome):
2024-12-25T07:20:22.147545852Z   File "/usr/local/lib/python3.10/contextlib.py", line 153, in __exit__
2024-12-25T07:20:22.147547791Z     self.gen.throw(typ, value, traceback)
2024-12-25T07:20:22.147549695Z   File "/usr/local/lib/python3.10/site-packages/pytest_django/plugin.py", line 184, in _handle_import_error
2024-12-25T07:20:22.147551718Z     raise ImportError(msg) from None
2024-12-25T07:20:22.147553584Z ImportError: No module named 'dj_database_url'
2024-12-25T07:20:22.147555470Z 
2024-12-25T07:20:22.147557280Z pytest-django found a Django project in /django-tasks (it contains manage.py) and added it to the Python path.
2024-12-25T07:20:22.147559327Z If this is wrong, add "django_find_project = false" to pytest.ini and explicitly manage your Python path.
2024-12-25T07:20:34.590754172Z [?2004hroot@b3426fc537fa:/django-tasks# pytest --collect-only -q[6Phon3 manage.py est --collect-only -qls[Kpytest --collect-only -qls[Kpython -m pip install django-tasksls[Kpytest --collect-only -qexport DJANGO_SETTINGS_MODULE=tests.settings
2024-12-25T07:20:56.355206867Z [?2004l
[?2004hroot@b3426fc537fa:/django-tasks# export [7mINSTALLED_APPS[27mINSTALLED_APPS=tests
2024-12-25T07:20:58.987014815Z [?2004l
[?2004hroot@b3426fc537fa:/django-tasks# export INSTALLED_APPS=testsDJANGO_SETTINGS_MODULE=tests.settings
[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[20Ppytest --collect-only -q
2024-12-25T07:20:59.193371486Z [?2004l
Traceback (most recent call last):
2024-12-25T07:20:59.193396356Z   File "/usr/local/bin/pytest", line 8, in <module>
2024-12-25T07:20:59.193399547Z     sys.exit(console_main())
2024-12-25T07:20:59.193401843Z   File "/usr/local/lib/python3.10/site-packages/_pytest/config/__init__.py", line 201, in console_main
2024-12-25T07:20:59.193404384Z     code = main()
2024-12-25T07:20:59.193406830Z   File "/usr/local/lib/python3.10/site-packages/_pytest/config/__init__.py", line 156, in main
2024-12-25T07:20:59.193409085Z     config = _prepareconfig(args, plugins)
2024-12-25T07:20:59.193411192Z   File "/usr/local/lib/python3.10/site-packages/_pytest/config/__init__.py", line 341, in _prepareconfig
2024-12-25T07:20:59.193413411Z     config = pluginmanager.hook.pytest_cmdline_parse(
2024-12-25T07:20:59.193415340Z   File "/usr/local/lib/python3.10/site-packages/pluggy/_hooks.py", line 513, in __call__
2024-12-25T07:20:59.193417441Z     return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
2024-12-25T07:20:59.193419474Z   File "/usr/local/lib/python3.10/site-packages/pluggy/_manager.py", line 120, in _hookexec
2024-12-25T07:20:59.193421634Z     return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
2024-12-25T07:20:59.193423686Z   File "/usr/local/lib/python3.10/site-packages/pluggy/_callers.py", line 139, in _multicall
2024-12-25T07:20:59.193425724Z     raise exception.with_traceback(exception.__traceback__)
2024-12-25T07:20:59.193427664Z   File "/usr/local/lib/python3.10/site-packages/pluggy/_callers.py", line 122, in _multicall
2024-12-25T07:20:59.193429793Z     teardown.throw(exception)  # type: ignore[union-attr]
2024-12-25T07:20:59.193431684Z   File "/usr/local/lib/python3.10/site-packages/_pytest/helpconfig.py", line 105, in pytest_cmdline_parse
2024-12-25T07:20:59.193433756Z     config = yield
2024-12-25T07:20:59.193435636Z   File "/usr/local/lib/python3.10/site-packages/pluggy/_callers.py", line 103, in _multicall
2024-12-25T07:20:59.193437796Z     res = hook_impl.function(*args)
2024-12-25T07:20:59.193439710Z   File "/usr/local/lib/python3.10/site-packages/_pytest/config/__init__.py", line 1140, in pytest_cmdline_parse
2024-12-25T07:20:59.193441772Z     self.parse(args)
2024-12-25T07:20:59.193443619Z   File "/usr/local/lib/python3.10/site-packages/_pytest/config/__init__.py", line 1494, in parse
2024-12-25T07:20:59.193445616Z     self._preparse(args, addopts=addopts)
2024-12-25T07:20:59.193466704Z   File "/usr/local/lib/python3.10/site-packages/_pytest/config/__init__.py", line 1398, in _preparse
2024-12-25T07:20:59.193480586Z     self.hook.pytest_load_initial_conftests(
2024-12-25T07:20:59.193482701Z   File "/usr/local/lib/python3.10/site-packages/pluggy/_hooks.py", line 513, in __call__
2024-12-25T07:20:59.193484755Z     return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
2024-12-25T07:20:59.193487657Z   File "/usr/local/lib/python3.10/site-packages/pluggy/_manager.py", line 120, in _hookexec
2024-12-25T07:20:59.193489746Z     return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
2024-12-25T07:20:59.193491707Z   File "/usr/local/lib/python3.10/site-packages/pluggy/_callers.py", line 139, in _multicall
2024-12-25T07:20:59.193493729Z     raise exception.with_traceback(exception.__traceback__)
2024-12-25T07:20:59.193495621Z   File "/usr/local/lib/python3.10/site-packages/pluggy/_callers.py", line 122, in _multicall
2024-12-25T07:20:59.193497601Z     teardown.throw(exception)  # type: ignore[union-attr]
2024-12-25T07:20:59.193499547Z   File "/usr/local/lib/python3.10/site-packages/_pytest/warnings.py", line 151, in pytest_load_initial_conftests
2024-12-25T07:20:59.193501806Z     return (yield)
2024-12-25T07:20:59.193503738Z   File "/usr/local/lib/python3.10/site-packages/pluggy/_callers.py", line 122, in _multicall
2024-12-25T07:20:59.193505713Z     teardown.throw(exception)  # type: ignore[union-attr]
2024-12-25T07:20:59.193507625Z   File "/usr/local/lib/python3.10/site-packages/_pytest/capture.py", line 154, in pytest_load_initial_conftests
2024-12-25T07:20:59.193509762Z     yield
2024-12-25T07:20:59.193511653Z   File "/usr/local/lib/python3.10/site-packages/pluggy/_callers.py", line 103, in _multicall
2024-12-25T07:20:59.193513653Z     res = hook_impl.function(*args)
2024-12-25T07:20:59.193515532Z   File "/usr/local/lib/python3.10/site-packages/pytest_django/plugin.py", line 356, in pytest_load_initial_conftests
2024-12-25T07:20:59.193517596Z     with _handle_import_error(_django_project_scan_outcome):
2024-12-25T07:20:59.193520484Z   File "/usr/local/lib/python3.10/contextlib.py", line 153, in __exit__
2024-12-25T07:20:59.193523612Z     self.gen.throw(typ, value, traceback)
2024-12-25T07:20:59.193526644Z   File "/usr/local/lib/python3.10/site-packages/pytest_django/plugin.py", line 184, in _handle_import_error
2024-12-25T07:20:59.193529947Z     raise ImportError(msg) from None
2024-12-25T07:20:59.193533013Z ImportError: No module named 'dj_database_url'
2024-12-25T07:20:59.193535617Z 
2024-12-25T07:20:59.193538110Z pytest-django found a Django project in /django-tasks (it contains manage.py) and added it to the Python path.
2024-12-25T07:20:59.193541178Z If this is wrong, add "django_find_project = false" to pytest.ini and explicitly manage your Python path.
2024-12-25T07:21:09.915622149Z [?2004hroot@b3426fc537fa:/django-tasks# vim pytest,.[K[K.ini
2024-12-25T07:21:09.916064014Z [?2004l
bash: vim: command not found
2024-12-25T07:21:17.144908735Z [?2004hroot@b3426fc537fa:/django-tasks# [7mapt-get install -y vim[27m
2024-12-25T07:21:21.102022165Z 
[A[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[Capt-get install -y vim
2024-12-25T07:21:21.102050910Z 
[A
2024-12-25T07:21:21.663753170Z [?2004l

Reading package lists... 0%

Reading package lists... 0%

Reading package lists... 0%

Reading package lists... 96%

Reading package lists... 96%

Reading package lists... 96%

Reading package lists... 96%

Reading package lists... 99%

Reading package lists... 99%

Reading package lists... Done

2024-12-25T07:21:21.827606029Z 
Building dependency tree... 0%

Building dependency tree... 0%

Building dependency tree... 50%

Building dependency tree... 50%

Building dependency tree... Done

2024-12-25T07:21:21.827887512Z 
Reading state information... 0% 

Reading state information... 0%

Reading state information... Done

2024-12-25T07:21:21.967591131Z The following additional packages will be installed:
2024-12-25T07:21:21.968040482Z   libgpm2 libsodium23 vim-common vim-runtime xxd
2024-12-25T07:21:21.968761592Z Suggested packages:
2024-12-25T07:21:21.968766520Z   gpm ctags vim-doc vim-scripts
2024-12-25T07:21:22.052637692Z The following NEW packages will be installed:
2024-12-25T07:21:22.053128687Z   libgpm2 libsodium23 vim vim-common vim-runtime xxd
2024-12-25T07:21:22.058218082Z 0 upgraded, 6 newly installed, 0 to remove and 0 not upgraded.
2024-12-25T07:21:22.058240867Z Need to get 8976 kB of archives.
2024-12-25T07:21:22.058243711Z After this operation, 41.9 MB of additional disk space will be used.
2024-12-25T07:21:22.242409068Z 
0% [Working]
            
Get:1 http://deb.debian.org/debian bookworm/main amd64 vim-common all 2:9.0.1378-2 [124 kB]
2024-12-25T07:21:22.577850770Z 
0% [1 vim-common 1444 B/124 kB 1%]
                                  
4% [Working]
            
Get:2 http://deb.debian.org/debian bookworm/main amd64 libgpm2 amd64 1.20.7-10+b1 [14.2 kB]
2024-12-25T07:21:22.665362215Z 
4% [2 libgpm2 1997 B/14.2 kB 14%]
                                 
8% [Waiting for headers]
                        
Get:3 http://deb.debian.org/debian bookworm/main amd64 libsodium23 amd64 1.0.18-1 [161 kB]
2024-12-25T07:21:22.824859638Z 
8% [3 libsodium23 2676 B/161 kB 2%]
                                   
13% [Waiting for headers]
                         
Get:4 http://deb.debian.org/debian bookworm/main amd64 vim-runtime all 2:9.0.1378-2 [7025 kB]
2024-12-25T07:21:23.289075221Z 
13% [4 vim-runtime 5352 B/7025 kB 0%]
                                     
79% [Waiting for headers]
                         
Get:5 http://deb.debian.org/debian bookworm/main amd64 vim amd64 2:9.0.1378-2 [1567 kB]
2024-12-25T07:21:23.445128365Z 
79% [5 vim 64.9 kB/1567 kB 4%]
                              
96% [Waiting for headers]
                         
Get:6 http://deb.debian.org/debian bookworm/main amd64 xxd amd64 2:9.0.1378-2 [83.7 kB]
2024-12-25T07:21:23.518142720Z 
96% [6 xxd 21.9 kB/83.7 kB 26%]
                               
100% [Working]
              
Fetched 8976 kB in 1s (6151 kB/s)
2024-12-25T07:21:23.652541246Z debconf: delaying package configuration, since apt-utils is not installed
2024-12-25T07:21:23.700368947Z Selecting previously unselected package vim-common.
2024-12-25T07:21:23.711857332Z (Reading database ... 
(Reading database ... 5%
(Reading database ... 10%
(Reading database ... 15%
(Reading database ... 20%
(Reading database ... 25%
(Reading database ... 30%
(Reading database ... 35%
(Reading database ... 40%
(Reading database ... 45%
(Reading database ... 50%
(Reading database ... 55%
(Reading database ... 60%
(Reading database ... 65%
(Reading database ... 70%
(Reading database ... 75%
(Reading database ... 80%
(Reading database ... 85%
(Reading database ... 90%
(Reading database ... 95%
(Reading database ... 100%
(Reading database ... 23969 files and directories currently installed.)
2024-12-25T07:21:23.712832128Z Preparing to unpack .../0-vim-common_2%3a9.0.1378-2_all.deb ...
2024-12-25T07:21:23.715085706Z Unpacking vim-common (2:9.0.1378-2) ...
2024-12-25T07:21:23.756620171Z Selecting previously unselected package libgpm2:amd64.
2024-12-25T07:21:23.759006033Z Preparing to unpack .../1-libgpm2_1.20.7-10+b1_amd64.deb ...
2024-12-25T07:21:23.763373122Z Unpacking libgpm2:amd64 (1.20.7-10+b1) ...
2024-12-25T07:21:23.787948373Z Selecting previously unselected package libsodium23:amd64.
2024-12-25T07:21:23.789901223Z Preparing to unpack .../2-libsodium23_1.0.18-1_amd64.deb ...
2024-12-25T07:21:23.791810692Z Unpacking libsodium23:amd64 (1.0.18-1) ...
2024-12-25T07:21:23.832820318Z Selecting previously unselected package vim-runtime.
2024-12-25T07:21:23.834887105Z Preparing to unpack .../3-vim-runtime_2%3a9.0.1378-2_all.deb ...
2024-12-25T07:21:23.843741964Z Adding 'diversion of /usr/share/vim/vim90/doc/help.txt to /usr/share/vim/vim90/doc/help.txt.vim-tiny by vim-runtime'
2024-12-25T07:21:23.851773799Z Adding 'diversion of /usr/share/vim/vim90/doc/tags to /usr/share/vim/vim90/doc/tags.vim-tiny by vim-runtime'
2024-12-25T07:21:23.853934212Z Unpacking vim-runtime (2:9.0.1378-2) ...
2024-12-25T07:21:24.343744625Z Selecting previously unselected package vim.
2024-12-25T07:21:24.346207969Z Preparing to unpack .../4-vim_2%3a9.0.1378-2_amd64.deb ...
2024-12-25T07:21:24.348280745Z Unpacking vim (2:9.0.1378-2) ...
2024-12-25T07:21:24.491277851Z Selecting previously unselected package xxd.
2024-12-25T07:21:24.493352767Z Preparing to unpack .../5-xxd_2%3a9.0.1378-2_amd64.deb ...
2024-12-25T07:21:24.495392592Z Unpacking xxd (2:9.0.1378-2) ...
2024-12-25T07:21:24.531013751Z Setting up libsodium23:amd64 (1.0.18-1) ...
2024-12-25T07:21:24.536860214Z Setting up libgpm2:amd64 (1.20.7-10+b1) ...
2024-12-25T07:21:24.542497174Z Setting up xxd (2:9.0.1378-2) ...
2024-12-25T07:21:24.548360091Z Setting up vim-common (2:9.0.1378-2) ...
2024-12-25T07:21:24.557115511Z Setting up vim-runtime (2:9.0.1378-2) ...
2024-12-25T07:21:24.634435316Z Setting up vim (2:9.0.1378-2) ...
2024-12-25T07:21:24.642859037Z update-alternatives: using /usr/bin/vim.basic to provide /usr/bin/editor (editor) in auto mode
2024-12-25T07:21:24.646393292Z update-alternatives: using /usr/bin/vim.basic to provide /usr/bin/ex (ex) in auto mode
2024-12-25T07:21:24.649829152Z update-alternatives: using /usr/bin/vim.basic to provide /usr/bin/rview (rview) in auto mode
2024-12-25T07:21:24.652338476Z update-alternatives: using /usr/bin/vim.basic to provide /usr/bin/rvim (rvim) in auto mode
2024-12-25T07:21:24.654901860Z update-alternatives: using /usr/bin/vim.basic to provide /usr/bin/vi (vi) in auto mode
2024-12-25T07:21:24.658648093Z update-alternatives: using /usr/bin/vim.basic to provide /usr/bin/view (view) in auto mode
2024-12-25T07:21:24.662097650Z update-alternatives: using /usr/bin/vim.basic to provide /usr/bin/vim (vim) in auto mode
2024-12-25T07:21:24.664706926Z update-alternatives: using /usr/bin/vim.basic to provide /usr/bin/vimdiff (vimdiff) in auto mode
2024-12-25T07:21:24.668852696Z Processing triggers for libc-bin (2.36-9+deb12u9) ...
2024-12-25T07:21:24.691382814Z Processing triggers for hicolor-icon-theme (0.17-2) ...
2024-12-25T07:21:26.035353078Z [?2004hroot@b3426fc537fa:/django-tasks# apt-get install -y vim[8Pvim pytest.ini
2024-12-25T07:21:57.583932672Z [?2004l
[?1006;1000h[?1002h[?1049h[22;0;0t[>4;2m[?1h=[?2004h[?1004h[1;40r[?12h[?12l[22;2t[22;1t[27m[23m[29m[m[H[2J[?25l[40;1H"pytest.ini" [New][2;1H▽[6n[2;1H  [3;1HPzz\[0%m[6n[3;1H           [1;1H[>c]10;?]11;?[2;1H[1m[34m~                                                                                                                                                [3;1H~                                                                                                                                                [4;1H~                                                                                                                                                [5;1H~                                                                                                                                                [6;1H~                                                                                                                                                [7;1H~                                                                                                                                                [8;1H~                                                                                                                                                [9;1H~                                                                                                                                                [10;1H~                                                                                                                                                [11;1H~                                                                                                                                                [12;1H~                                                                                                                                                [13;1H~                                                                                                                                                [14;1H~                                                                                                                                                [15;1H~                                                                                                                                                [16;1H~                                                                                                                                                [17;1H~                                                                                                                                                [18;1H~                                                                                                                                                [19;1H~                                                                                                                                                [20;1H~                                                                                                                                                [21;1H~                                                                                                                                                [22;1H~                                                                                                                                                [23;1H~                                                                                                                                                [24;1H~                                                                                                                                                [25;1H~                                                                                                                                                [26;1H~                                                                                                                                                [27;1H~                                                                                                                                                [28;1H~                                                                                                                                                [29;1H~                                                                                                                                                [30;1H~                                                                                                                                                [31;1H~                                                                                                                                                [32;1H~                                                                                                                                                [33;1H~                                                                                                                                                [34;1H~                                                                                                                                                [35;1H~                                                                                                                                                [36;1H~                                                                                                                                                [37;1H~                                                                                                                                                [38;1H~                                                                                                                                                [39;1H~                                                                                                                                                [m[40;128H0,0-1[9CAll[1;1H[?25h[?4m[?25l[40;1H[1m-- INSERT --[m[40;14H[K[40;128H0,1[11CAll[1;1H[?25h[?25l[40;1H[K[1;1H[35m[46m[[m[35mpytest[m[35m[46m][m[40;128H1,8[11CAll[1;8H[?25h[?25l[40;118H~@k[1;8H[40;118H   [1;8H[?25h[?25l[40;118Hi[1;8H[40;118H [1;8H[40;1H[1m-- INSERT --[m[40;128H[K[40;128H1,8[11CAll[1;8H[?25h[?25l[40;130H9[1;9H[?25h[?25l[2;1H[K[1;1H[35m[pytest][m[40;128H2,1[2;1H[?25h[?25l[32mDJANGO_SETTINGS_MODULE[m =[31m your_project.settings[?25h[?25l[m[40;130H47[2;47H[?25h[?25l[40;131H6[2;46H[?25h[?25l[40;131H5[2;45H[?25h[?25l[40;131H4[2;44H[?25h[?25l[40;131H3[2;43H[?25h[?25l[40;131H2[2;42H[?25h[?25l[40;131H1[2;41H[?25h[?25l[40;131H0[2;40H[?25h[?25l[40;130H39[2;39H[?25h[?25l[40;131H8[2;38H[?25h[?25l[31m.settings[m[2;46H[K[40;131H7[2;37H[?25h[?25l[31m.settings[m[2;45H[K[40;131H6[2;36H[?25h[?25l[31m.settings[m[2;44H[K[40;131H5[2;35H[?25h[?25l[31m.settings[m[2;43H[K[40;131H4[2;34H[?25h[?25l[31m.settings[m[2;42H[K[40;131H3[2;33H[?25h[?25l[31m.settings[m[2;41H[K[40;131H2[2;32H[?25h[?25l[31m.settings[m[2;40H[K[40;131H1[2;31H[?25h[?25l[31m.settings[m[2;39H[K[40;131H0[2;30H[?25h[?25l[31m.settings[m[2;38H[K[40;130H29[2;29H[?25h[?25l[31m.settings[m[2;37H[K[40;131H8[2;28H[?25h[?25l[31m.settings[m[2;36H[K[40;131H7[2;27H[?25h[?25l[31m.settings[m[2;35H[K[40;131H6[2;26H[?25h[?25l[31mt.settings[m[40;131H7[2;27H[?25h[?25l[31me.settings[m[40;131H8[2;28H[?25h[?25l[31ms.settings[m[40;131H9[2;29H[?25h[?25l[31mt.settings[m[40;130H30[2;30H[?25h[?25l[31ms.settings[m[40;131H1[2;31H[?25h[40;1H[K[2;30H[?25l[40;118H^[[2;30H[40;118H  [2;31H[40;128H2,30[10CAll[2;30H[?25h[?25l[40;118H:[2;30H[40;118H[K[40;1H:[?25hwq
[?25l[?1006;1000l[?1002l[?2004l[>4;m"pytest.ini" [New] 2L, 49B written
[23;2t[23;1t

2024-12-25T07:22:00.699834688Z [?1004l[?2004l[?1l>[?1049l[23;0;0t[?25h[>4;m[?2004hroot@b3426fc537fa:/django-tasks# vim pytest.iniapt-get install -y vim[8Pvim pytest.inipytest --collect-only -q
2024-12-25T07:22:00.906561189Z [?2004l
Traceback (most recent call last):
2024-12-25T07:22:00.906589716Z   File "/usr/local/bin/pytest", line 8, in <module>
2024-12-25T07:22:00.906592608Z     sys.exit(console_main())
2024-12-25T07:22:00.906595120Z   File "/usr/local/lib/python3.10/site-packages/_pytest/config/__init__.py", line 201, in console_main
2024-12-25T07:22:00.906597534Z     code = main()
2024-12-25T07:22:00.906599571Z   File "/usr/local/lib/python3.10/site-packages/_pytest/config/__init__.py", line 156, in main
2024-12-25T07:22:00.906601614Z     config = _prepareconfig(args, plugins)
2024-12-25T07:22:00.906604176Z   File "/usr/local/lib/python3.10/site-packages/_pytest/config/__init__.py", line 341, in _prepareconfig
2024-12-25T07:22:00.906606251Z     config = pluginmanager.hook.pytest_cmdline_parse(
2024-12-25T07:22:00.906608204Z   File "/usr/local/lib/python3.10/site-packages/pluggy/_hooks.py", line 513, in __call__
2024-12-25T07:22:00.906610210Z     return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
2024-12-25T07:22:00.906612351Z   File "/usr/local/lib/python3.10/site-packages/pluggy/_manager.py", line 120, in _hookexec
2024-12-25T07:22:00.906614340Z     return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
2024-12-25T07:22:00.906616304Z   File "/usr/local/lib/python3.10/site-packages/pluggy/_callers.py", line 139, in _multicall
2024-12-25T07:22:00.906618297Z     raise exception.with_traceback(exception.__traceback__)
2024-12-25T07:22:00.906620404Z   File "/usr/local/lib/python3.10/site-packages/pluggy/_callers.py", line 122, in _multicall
2024-12-25T07:22:00.906622434Z     teardown.throw(exception)  # type: ignore[union-attr]
2024-12-25T07:22:00.906624311Z   File "/usr/local/lib/python3.10/site-packages/_pytest/helpconfig.py", line 105, in pytest_cmdline_parse
2024-12-25T07:22:00.906626330Z     config = yield
2024-12-25T07:22:00.906628244Z   File "/usr/local/lib/python3.10/site-packages/pluggy/_callers.py", line 103, in _multicall
2024-12-25T07:22:00.906630200Z     res = hook_impl.function(*args)
2024-12-25T07:22:00.906632095Z   File "/usr/local/lib/python3.10/site-packages/_pytest/config/__init__.py", line 1140, in pytest_cmdline_parse
2024-12-25T07:22:00.906634093Z     self.parse(args)
2024-12-25T07:22:00.906635957Z   File "/usr/local/lib/python3.10/site-packages/_pytest/config/__init__.py", line 1494, in parse
2024-12-25T07:22:00.906637925Z     self._preparse(args, addopts=addopts)
2024-12-25T07:22:00.906639803Z   File "/usr/local/lib/python3.10/site-packages/_pytest/config/__init__.py", line 1398, in _preparse
2024-12-25T07:22:00.906655029Z     self.hook.pytest_load_initial_conftests(
2024-12-25T07:22:00.906657164Z   File "/usr/local/lib/python3.10/site-packages/pluggy/_hooks.py", line 513, in __call__
2024-12-25T07:22:00.906659177Z     return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
2024-12-25T07:22:00.906662163Z   File "/usr/local/lib/python3.10/site-packages/pluggy/_manager.py", line 120, in _hookexec
2024-12-25T07:22:00.906664163Z     return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
2024-12-25T07:22:00.906666152Z   File "/usr/local/lib/python3.10/site-packages/pluggy/_callers.py", line 139, in _multicall
2024-12-25T07:22:00.906668127Z     raise exception.with_traceback(exception.__traceback__)
2024-12-25T07:22:00.906670008Z   File "/usr/local/lib/python3.10/site-packages/pluggy/_callers.py", line 122, in _multicall
2024-12-25T07:22:00.906671960Z     teardown.throw(exception)  # type: ignore[union-attr]
2024-12-25T07:22:00.906673975Z   File "/usr/local/lib/python3.10/site-packages/_pytest/warnings.py", line 151, in pytest_load_initial_conftests
2024-12-25T07:22:00.906676019Z     return (yield)
2024-12-25T07:22:00.906677841Z   File "/usr/local/lib/python3.10/site-packages/pluggy/_callers.py", line 122, in _multicall
2024-12-25T07:22:00.906679797Z     teardown.throw(exception)  # type: ignore[union-attr]
2024-12-25T07:22:00.906681699Z   File "/usr/local/lib/python3.10/site-packages/_pytest/capture.py", line 154, in pytest_load_initial_conftests
2024-12-25T07:22:00.906683715Z     yield
2024-12-25T07:22:00.906685569Z   File "/usr/local/lib/python3.10/site-packages/pluggy/_callers.py", line 103, in _multicall
2024-12-25T07:22:00.906687555Z     res = hook_impl.function(*args)
2024-12-25T07:22:00.906689448Z   File "/usr/local/lib/python3.10/site-packages/pytest_django/plugin.py", line 356, in pytest_load_initial_conftests
2024-12-25T07:22:00.906691491Z     with _handle_import_error(_django_project_scan_outcome):
2024-12-25T07:22:00.906693366Z   File "/usr/local/lib/python3.10/contextlib.py", line 153, in __exit__
2024-12-25T07:22:00.906695305Z     self.gen.throw(typ, value, traceback)
2024-12-25T07:22:00.906697316Z   File "/usr/local/lib/python3.10/site-packages/pytest_django/plugin.py", line 184, in _handle_import_error
2024-12-25T07:22:00.906699973Z     raise ImportError(msg) from None
2024-12-25T07:22:00.906702891Z ImportError: No module named 'dj_database_url'
2024-12-25T07:22:00.906705854Z 
2024-12-25T07:22:00.906709134Z pytest-django found a Django project in /django-tasks (it contains manage.py) and added it to the Python path.
2024-12-25T07:22:00.906712619Z If this is wrong, add "django_find_project = false" to pytest.ini and explicitly manage your Python path.
2024-12-25T07:22:19.309388966Z [?2004hroot@b3426fc537fa:/django-tasks# pytest
2024-12-25T07:22:19.501188258Z [?2004l
Traceback (most recent call last):
2024-12-25T07:22:19.501239066Z   File "/usr/local/bin/pytest", line 8, in <module>
2024-12-25T07:22:19.501242552Z     sys.exit(console_main())
2024-12-25T07:22:19.501244834Z   File "/usr/local/lib/python3.10/site-packages/_pytest/config/__init__.py", line 201, in console_main
2024-12-25T07:22:19.501247004Z     code = main()
2024-12-25T07:22:19.501248927Z   File "/usr/local/lib/python3.10/site-packages/_pytest/config/__init__.py", line 156, in main
2024-12-25T07:22:19.501251140Z     config = _prepareconfig(args, plugins)
2024-12-25T07:22:19.501253194Z   File "/usr/local/lib/python3.10/site-packages/_pytest/config/__init__.py", line 341, in _prepareconfig
2024-12-25T07:22:19.501270299Z     config = pluginmanager.hook.pytest_cmdline_parse(
2024-12-25T07:22:19.501272348Z   File "/usr/local/lib/python3.10/site-packages/pluggy/_hooks.py", line 513, in __call__
2024-12-25T07:22:19.501274383Z     return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
2024-12-25T07:22:19.501276389Z   File "/usr/local/lib/python3.10/site-packages/pluggy/_manager.py", line 120, in _hookexec
2024-12-25T07:22:19.501278528Z     return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
2024-12-25T07:22:19.501280486Z   File "/usr/local/lib/python3.10/site-packages/pluggy/_callers.py", line 139, in _multicall
2024-12-25T07:22:19.501282494Z     raise exception.with_traceback(exception.__traceback__)
2024-12-25T07:22:19.501284389Z   File "/usr/local/lib/python3.10/site-packages/pluggy/_callers.py", line 122, in _multicall
2024-12-25T07:22:19.501286512Z     teardown.throw(exception)  # type: ignore[union-attr]
2024-12-25T07:22:19.501288407Z   File "/usr/local/lib/python3.10/site-packages/_pytest/helpconfig.py", line 105, in pytest_cmdline_parse
2024-12-25T07:22:19.501290412Z     config = yield
2024-12-25T07:22:19.501292288Z   File "/usr/local/lib/python3.10/site-packages/pluggy/_callers.py", line 103, in _multicall
2024-12-25T07:22:19.501294388Z     res = hook_impl.function(*args)
2024-12-25T07:22:19.501296303Z   File "/usr/local/lib/python3.10/site-packages/_pytest/config/__init__.py", line 1140, in pytest_cmdline_parse
2024-12-25T07:22:19.501298443Z     self.parse(args)
2024-12-25T07:22:19.501300296Z   File "/usr/local/lib/python3.10/site-packages/_pytest/config/__init__.py", line 1494, in parse
2024-12-25T07:22:19.501302424Z     self._preparse(args, addopts=addopts)
2024-12-25T07:22:19.501304326Z   File "/usr/local/lib/python3.10/site-packages/_pytest/config/__init__.py", line 1398, in _preparse
2024-12-25T07:22:19.501306334Z     self.hook.pytest_load_initial_conftests(
2024-12-25T07:22:19.501308212Z   File "/usr/local/lib/python3.10/site-packages/pluggy/_hooks.py", line 513, in __call__
2024-12-25T07:22:19.501310353Z     return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
2024-12-25T07:22:19.501316472Z   File "/usr/local/lib/python3.10/site-packages/pluggy/_manager.py", line 120, in _hookexec
2024-12-25T07:22:19.501318535Z     return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
2024-12-25T07:22:19.501320454Z   File "/usr/local/lib/python3.10/site-packages/pluggy/_callers.py", line 139, in _multicall
2024-12-25T07:22:19.501322479Z     raise exception.with_traceback(exception.__traceback__)
2024-12-25T07:22:19.501324365Z   File "/usr/local/lib/python3.10/site-packages/pluggy/_callers.py", line 122, in _multicall
2024-12-25T07:22:19.501326353Z     teardown.throw(exception)  # type: ignore[union-attr]
2024-12-25T07:22:19.501328255Z   File "/usr/local/lib/python3.10/site-packages/_pytest/warnings.py", line 151, in pytest_load_initial_conftests
2024-12-25T07:22:19.501330283Z     return (yield)
2024-12-25T07:22:19.501332143Z   File "/usr/local/lib/python3.10/site-packages/pluggy/_callers.py", line 122, in _multicall
2024-12-25T07:22:19.501334109Z     teardown.throw(exception)  # type: ignore[union-attr]
2024-12-25T07:22:19.501336000Z   File "/usr/local/lib/python3.10/site-packages/_pytest/capture.py", line 154, in pytest_load_initial_conftests
2024-12-25T07:22:19.501338129Z     yield
2024-12-25T07:22:19.501340012Z   File "/usr/local/lib/python3.10/site-packages/pluggy/_callers.py", line 103, in _multicall
2024-12-25T07:22:19.501342013Z     res = hook_impl.function(*args)
2024-12-25T07:22:19.501344587Z   File "/usr/local/lib/python3.10/site-packages/pytest_django/plugin.py", line 356, in pytest_load_initial_conftests
2024-12-25T07:22:19.501346635Z     with _handle_import_error(_django_project_scan_outcome):
2024-12-25T07:22:19.501348537Z   File "/usr/local/lib/python3.10/contextlib.py", line 153, in __exit__
2024-12-25T07:22:19.501350491Z     self.gen.throw(typ, value, traceback)
2024-12-25T07:22:19.501352372Z   File "/usr/local/lib/python3.10/site-packages/pytest_django/plugin.py", line 184, in _handle_import_error
2024-12-25T07:22:19.501354423Z     raise ImportError(msg) from None
2024-12-25T07:22:19.501356296Z ImportError: No module named 'dj_database_url'
2024-12-25T07:22:19.501358208Z 
2024-12-25T07:22:19.501360037Z pytest-django found a Django project in /django-tasks (it contains manage.py) and added it to the Python path.
2024-12-25T07:22:19.501362057Z If this is wrong, add "django_find_project = false" to pytest.ini and explicitly manage your Python path.
2024-12-25T07:22:30.200710299Z [?2004hroot@b3426fc537fa:/django-tasks# pip install [7mdj_database_url[27mdj_database_url
2024-12-25T07:22:30.560566740Z [?2004l
Looking in indexes: /simple/
2024-12-25T07:22:30.596608970Z Collecting dj_database_url
2024-12-25T07:22:30.755888637Z   Downloading /packages/dj-database-url/dj_database_url-2.3.0-py3-none-any.whl (7.8 kB)
2024-12-25T07:22:30.764703922Z Requirement already satisfied: Django>=4.2 in /usr/local/lib/python3.10/site-packages (from dj_database_url) (5.1.4)
2024-12-25T07:22:30.765622191Z Requirement already satisfied: typing-extensions>=3.10.0.0 in /usr/local/lib/python3.10/site-packages (from dj_database_url) (4.12.2)
2024-12-25T07:22:30.772038967Z Requirement already satisfied: sqlparse>=0.3.1 in /usr/local/lib/python3.10/site-packages (from Django>=4.2->dj_database_url) (0.5.3)
2024-12-25T07:22:30.772777816Z Requirement already satisfied: asgiref<4,>=3.8.1 in /usr/local/lib/python3.10/site-packages (from Django>=4.2->dj_database_url) (3.8.1)
2024-12-25T07:22:30.864880367Z Installing collected packages: dj_database_url
2024-12-25T07:22:30.877894670Z Successfully installed dj_database_url-2.3.0
2024-12-25T07:22:30.878106756Z [33mWARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv[0m[33m
2024-12-25T07:22:30.882130373Z [0m
2024-12-25T07:22:30.882155174Z [1m[[0m[34;49mnotice[0m[1;39;49m][0m[39;49m A new release of pip is available: [0m[31;49m23.0.1[0m[39;49m -> [0m[32;49m24.3.1[0m
2024-12-25T07:22:30.882160697Z [1m[[0m[34;49mnotice[0m[1;39;49m][0m[39;49m To update, run: [0m[32;49mpip install --upgrade pip[0m
2024-12-25T07:22:31.970593663Z [?2004hroot@b3426fc537fa:/django-tasks# pip install dj_database_urlytest[K
2024-12-25T07:22:32.161745306Z [?2004l
Traceback (most recent call last):
2024-12-25T07:22:32.161776267Z   File "/usr/local/bin/pytest", line 8, in <module>
2024-12-25T07:22:32.161779786Z     sys.exit(console_main())
2024-12-25T07:22:32.161782155Z   File "/usr/local/lib/python3.10/site-packages/_pytest/config/__init__.py", line 201, in console_main
2024-12-25T07:22:32.161784724Z     code = main()
2024-12-25T07:22:32.161787570Z   File "/usr/local/lib/python3.10/site-packages/_pytest/config/__init__.py", line 156, in main
2024-12-25T07:22:32.161790144Z     config = _prepareconfig(args, plugins)
2024-12-25T07:22:32.161792344Z   File "/usr/local/lib/python3.10/site-packages/_pytest/config/__init__.py", line 341, in _prepareconfig
2024-12-25T07:22:32.161794907Z     config = pluginmanager.hook.pytest_cmdline_parse(
2024-12-25T07:22:32.161797154Z   File "/usr/local/lib/python3.10/site-packages/pluggy/_hooks.py", line 513, in __call__
2024-12-25T07:22:32.161800087Z     return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
2024-12-25T07:22:32.161803661Z   File "/usr/local/lib/python3.10/site-packages/pluggy/_manager.py", line 120, in _hookexec
2024-12-25T07:22:32.161807207Z     return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
2024-12-25T07:22:32.161820435Z   File "/usr/local/lib/python3.10/site-packages/pluggy/_callers.py", line 139, in _multicall
2024-12-25T07:22:32.161823535Z     raise exception.with_traceback(exception.__traceback__)
2024-12-25T07:22:32.161827170Z   File "/usr/local/lib/python3.10/site-packages/pluggy/_callers.py", line 122, in _multicall
2024-12-25T07:22:32.161830098Z     teardown.throw(exception)  # type: ignore[union-attr]
2024-12-25T07:22:32.161833350Z   File "/usr/local/lib/python3.10/site-packages/_pytest/helpconfig.py", line 105, in pytest_cmdline_parse
2024-12-25T07:22:32.161836419Z     config = yield
2024-12-25T07:22:32.161839343Z   File "/usr/local/lib/python3.10/site-packages/pluggy/_callers.py", line 103, in _multicall
2024-12-25T07:22:32.161843552Z     res = hook_impl.function(*args)
2024-12-25T07:22:32.161845745Z   File "/usr/local/lib/python3.10/site-packages/_pytest/config/__init__.py", line 1140, in pytest_cmdline_parse
2024-12-25T07:22:32.161847827Z     self.parse(args)
2024-12-25T07:22:32.161849839Z   File "/usr/local/lib/python3.10/site-packages/_pytest/config/__init__.py", line 1494, in parse
2024-12-25T07:22:32.161851881Z     self._preparse(args, addopts=addopts)
2024-12-25T07:22:32.161858677Z   File "/usr/local/lib/python3.10/site-packages/_pytest/config/__init__.py", line 1398, in _preparse
2024-12-25T07:22:32.161860781Z     self.hook.pytest_load_initial_conftests(
2024-12-25T07:22:32.161864807Z   File "/usr/local/lib/python3.10/site-packages/pluggy/_hooks.py", line 513, in __call__
2024-12-25T07:22:32.161866853Z     return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
2024-12-25T07:22:32.161870459Z   File "/usr/local/lib/python3.10/site-packages/pluggy/_manager.py", line 120, in _hookexec
2024-12-25T07:22:32.161872512Z     return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
2024-12-25T07:22:32.161874466Z   File "/usr/local/lib/python3.10/site-packages/pluggy/_callers.py", line 139, in _multicall
2024-12-25T07:22:32.161876472Z     raise exception.with_traceback(exception.__traceback__)
2024-12-25T07:22:32.161878460Z   File "/usr/local/lib/python3.10/site-packages/pluggy/_callers.py", line 122, in _multicall
2024-12-25T07:22:32.161880450Z     teardown.throw(exception)  # type: ignore[union-attr]
2024-12-25T07:22:32.161882381Z   File "/usr/local/lib/python3.10/site-packages/_pytest/warnings.py", line 151, in pytest_load_initial_conftests
2024-12-25T07:22:32.161884415Z     return (yield)
2024-12-25T07:22:32.161886634Z   File "/usr/local/lib/python3.10/site-packages/pluggy/_callers.py", line 122, in _multicall
2024-12-25T07:22:32.161888631Z     teardown.throw(exception)  # type: ignore[union-attr]
2024-12-25T07:22:32.161890527Z   File "/usr/local/lib/python3.10/site-packages/_pytest/capture.py", line 154, in pytest_load_initial_conftests
2024-12-25T07:22:32.161895827Z     yield
2024-12-25T07:22:32.161897787Z   File "/usr/local/lib/python3.10/site-packages/pluggy/_callers.py", line 103, in _multicall
2024-12-25T07:22:32.161899787Z     res = hook_impl.function(*args)
2024-12-25T07:22:32.161901676Z   File "/usr/local/lib/python3.10/site-packages/pytest_django/plugin.py", line 357, in pytest_load_initial_conftests
2024-12-25T07:22:32.161903716Z     dj_settings.DATABASES  # noqa: B018
2024-12-25T07:22:32.161905646Z   File "/usr/local/lib/python3.10/site-packages/django/conf/__init__.py", line 81, in __getattr__
2024-12-25T07:22:32.161907653Z     self._setup(name)
2024-12-25T07:22:32.161909585Z   File "/usr/local/lib/python3.10/site-packages/django/conf/__init__.py", line 68, in _setup
2024-12-25T07:22:32.161911604Z     self._wrapped = Settings(settings_module)
2024-12-25T07:22:32.161913510Z   File "/usr/local/lib/python3.10/site-packages/django/conf/__init__.py", line 166, in __init__
2024-12-25T07:22:32.161915514Z     mod = importlib.import_module(self.SETTINGS_MODULE)
2024-12-25T07:22:32.161917722Z   File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
2024-12-25T07:22:32.161919733Z     return _bootstrap._gcd_import(name[level:], package, level)
2024-12-25T07:22:32.161921711Z   File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
2024-12-25T07:22:32.161923820Z   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
2024-12-25T07:22:32.161925914Z   File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
2024-12-25T07:22:32.161927908Z   File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
2024-12-25T07:22:32.161930288Z   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
2024-12-25T07:22:32.161932904Z   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
2024-12-25T07:22:32.161934947Z   File "/django-tasks/tests/settings.py", line 9, in <module>
2024-12-25T07:22:32.161936987Z     IN_TEST = sys.argv[1] == "test"
2024-12-25T07:22:32.161939001Z IndexError: list index out of range
2024-12-25T07:22:35.637558670Z [?2004hroot@b3426fc537fa:/django-tasks# pytestip install dj_database_urlytest[K --collect-only -q[10Pvim pytest.inipytest --collect-only -q
2024-12-25T07:22:36.221955156Z [?2004l
tests/tests/test_database_backend.py::ConnectionExclusiveTranscationTestCase::test_explicit_transaction
2024-12-25T07:22:36.221984753Z tests/tests/test_database_backend.py::ConnectionExclusiveTranscationTestCase::test_non_sqlite
2024-12-25T07:22:36.222003033Z tests/tests/test_database_backend.py::ConnectionExclusiveTranscationTestCase::test_old_django_requires_manual_transaction
2024-12-25T07:22:36.222005345Z tests/tests/test_database_backend.py::DatabaseBackendTestCase::test_async_get_missing_result
2024-12-25T07:22:36.222007554Z tests/tests/test_database_backend.py::DatabaseBackendTestCase::test_async_invalid_uuid
2024-12-25T07:22:36.222010987Z tests/tests/test_database_backend.py::DatabaseBackendTestCase::test_check
2024-12-25T07:22:36.222014337Z tests/tests/test_database_backend.py::DatabaseBackendTestCase::test_database_backend_app_missing
2024-12-25T07:22:36.222017393Z tests/tests/test_database_backend.py::DatabaseBackendTestCase::test_doesnt_wait_until_transaction_commit
2024-12-25T07:22:36.222020508Z tests/tests/test_database_backend.py::DatabaseBackendTestCase::test_enqueue_logs
2024-12-25T07:22:36.222023690Z tests/tests/test_database_backend.py::DatabaseBackendTestCase::test_enqueue_task
2024-12-25T07:22:36.222027113Z tests/tests/test_database_backend.py::DatabaseBackendTestCase::test_enqueue_task_async
2024-12-25T07:22:36.222030424Z tests/tests/test_database_backend.py::DatabaseBackendTestCase::test_get_missing_result
2024-12-25T07:22:36.222033516Z tests/tests/test_database_backend.py::DatabaseBackendTestCase::test_get_result
2024-12-25T07:22:36.222036699Z tests/tests/test_database_backend.py::DatabaseBackendTestCase::test_get_result_async
2024-12-25T07:22:36.222040022Z tests/tests/test_database_backend.py::DatabaseBackendTestCase::test_get_result_from_different_request
2024-12-25T07:22:36.222043253Z tests/tests/test_database_backend.py::DatabaseBackendTestCase::test_invalid_task_path
2024-12-25T07:22:36.222045408Z tests/tests/test_database_backend.py::DatabaseBackendTestCase::test_invalid_uuid
2024-12-25T07:22:36.222047328Z tests/tests/test_database_backend.py::DatabaseBackendTestCase::test_meaning_of_life_view
2024-12-25T07:22:36.222049319Z tests/tests/test_database_backend.py::DatabaseBackendTestCase::test_missing_task_path
2024-12-25T07:22:36.222051217Z tests/tests/test_database_backend.py::DatabaseBackendTestCase::test_priority_range_check
2024-12-25T07:22:36.222053298Z tests/tests/test_database_backend.py::DatabaseBackendTestCase::test_refresh_result
2024-12-25T07:22:36.222055205Z tests/tests/test_database_backend.py::DatabaseBackendTestCase::test_refresh_result_async
2024-12-25T07:22:36.222058783Z tests/tests/test_database_backend.py::DatabaseBackendTestCase::test_task_specific_enqueue_on_commit
2024-12-25T07:22:36.222060846Z tests/tests/test_database_backend.py::DatabaseBackendTestCase::test_using_correct_backend
2024-12-25T07:22:36.222063091Z tests/tests/test_database_backend.py::DatabaseBackendTestCase::test_wait_until_transaction_by_default
2024-12-25T07:22:36.222065010Z tests/tests/test_database_backend.py::DatabaseBackendTestCase::test_wait_until_transaction_commit
2024-12-25T07:22:36.222066942Z tests/tests/test_database_backend.py::DatabaseBackendWorkerTestCase::test_batch_processes_all_tasks
2024-12-25T07:22:36.222068873Z tests/tests/test_database_backend.py::DatabaseBackendWorkerTestCase::test_complex_exception
2024-12-25T07:22:36.222073611Z tests/tests/test_database_backend.py::DatabaseBackendWorkerTestCase::test_doesnt_process_different_backend
2024-12-25T07:22:36.222075774Z tests/tests/test_database_backend.py::DatabaseBackendWorkerTestCase::test_doesnt_process_different_queue
2024-12-25T07:22:36.222077776Z tests/tests/test_database_backend.py::DatabaseBackendWorkerTestCase::test_failing_task
2024-12-25T07:22:36.222079702Z tests/tests/test_database_backend.py::DatabaseBackendWorkerTestCase::test_fractional_interval
2024-12-25T07:22:36.222082242Z tests/tests/test_database_backend.py::DatabaseBackendWorkerTestCase::test_incorrect_backend
2024-12-25T07:22:36.222084128Z tests/tests/test_database_backend.py::DatabaseBackendWorkerTestCase::test_infinite_interval
2024-12-25T07:22:36.222086013Z tests/tests/test_database_backend.py::DatabaseBackendWorkerTestCase::test_invalid_task_path
2024-12-25T07:22:36.222087873Z tests/tests/test_database_backend.py::DatabaseBackendWorkerTestCase::test_missing_task_path
2024-12-25T07:22:36.222089756Z tests/tests/test_database_backend.py::DatabaseBackendWorkerTestCase::test_negative_interval
2024-12-25T07:22:36.222091676Z tests/tests/test_database_backend.py::DatabaseBackendWorkerTestCase::test_no_tasks
2024-12-25T07:22:36.222093562Z tests/tests/test_database_backend.py::DatabaseBackendWorkerTestCase::test_process_all_queues
2024-12-25T07:22:36.222095476Z tests/tests/test_database_backend.py::DatabaseBackendWorkerTestCase::test_run_after
2024-12-25T07:22:36.222097351Z tests/tests/test_database_backend.py::DatabaseBackendWorkerTestCase::test_run_after_priority
2024-12-25T07:22:36.222099293Z tests/tests/test_database_backend.py::DatabaseBackendWorkerTestCase::test_run_enqueued_task
2024-12-25T07:22:36.222103936Z tests/tests/test_database_backend.py::DatabaseBackendWorkerTestCase::test_unknown_backend
2024-12-25T07:22:36.222107107Z tests/tests/test_database_backend.py::DatabaseBackendWorkerTestCase::test_verbose_logging
2024-12-25T07:22:36.222114033Z tests/tests/test_database_backend.py::DatabaseBackendWorkerTestCase::test_worker_doesnt_exit
2024-12-25T07:22:36.222119909Z tests/tests/test_database_backend.py::DatabaseBackendWorkerTestCase::test_worker_with_locked_rows
2024-12-25T07:22:36.222147211Z tests/tests/test_database_backend.py::DatabaseTaskResultTestCase::test_cross_connection
2024-12-25T07:22:36.222163469Z tests/tests/test_database_backend.py::DatabaseTaskResultTestCase::test_get_locked_with_locked_rows
2024-12-25T07:22:36.222166086Z tests/tests/test_database_backend.py::DatabaseTaskResultTestCase::test_lock_no_rows
2024-12-25T07:22:36.222168236Z tests/tests/test_database_backend.py::DatabaseTaskResultTestCase::test_locks_tasks
2024-12-25T07:22:36.222170302Z tests/tests/test_database_backend.py::DatabaseTaskResultTestCase::test_locks_tasks_filtered
2024-12-25T07:22:36.222172274Z tests/tests/test_database_backend.py::DatabaseTaskResultTestCase::test_locks_tasks_filtered_sqlite
2024-12-25T07:22:36.222236303Z tests/tests/test_database_backend.py::DatabaseTaskResultTestCase::test_locks_tasks_sqlite
2024-12-25T07:22:36.222278647Z tests/tests/test_database_backend.py::DatabaseBackendPruneTaskResultsTestCase::test_doesnt_prune_new_tasks
2024-12-25T07:22:36.222282912Z tests/tests/test_database_backend.py::DatabaseBackendPruneTaskResultsTestCase::test_doesnt_prune_running_tasks
2024-12-25T07:22:36.222285257Z tests/tests/test_database_backend.py::DatabaseBackendPruneTaskResultsTestCase::test_dry_run
2024-12-25T07:22:36.222287449Z tests/tests/test_database_backend.py::DatabaseBackendPruneTaskResultsTestCase::test_failed_min_age
2024-12-25T07:22:36.222289495Z tests/tests/test_database_backend.py::DatabaseBackendPruneTaskResultsTestCase::test_incorrect_backend
2024-12-25T07:22:36.222291556Z tests/tests/test_database_backend.py::DatabaseBackendPruneTaskResultsTestCase::test_min_age
2024-12-25T07:22:36.222293730Z tests/tests/test_database_backend.py::DatabaseBackendPruneTaskResultsTestCase::test_negative_age
2024-12-25T07:22:36.222295954Z tests/tests/test_database_backend.py::DatabaseBackendPruneTaskResultsTestCase::test_only_prunes_specified_queue
2024-12-25T07:22:36.222301161Z tests/tests/test_database_backend.py::DatabaseBackendPruneTaskResultsTestCase::test_prune_all_queues
2024-12-25T07:22:36.222303165Z tests/tests/test_database_backend.py::DatabaseBackendPruneTaskResultsTestCase::test_prunes_tasks
2024-12-25T07:22:36.222305119Z tests/tests/test_database_backend.py::DatabaseBackendPruneTaskResultsTestCase::test_unknown_backend
2024-12-25T07:22:36.222307244Z tests/tests/test_database_backend.py::DatabaseWorkerProcessTestCase::test_interrupt_no_tasks
2024-12-25T07:22:36.222309214Z tests/tests/test_database_backend.py::DatabaseWorkerProcessTestCase::test_interrupt_signals
2024-12-25T07:22:36.222311498Z tests/tests/test_database_backend.py::DatabaseWorkerProcessTestCase::test_keyboard_interrupt_task
2024-12-25T07:22:36.222313640Z tests/tests/test_database_backend.py::DatabaseWorkerProcessTestCase::test_kill
2024-12-25T07:22:36.222315754Z tests/tests/test_database_backend.py::DatabaseWorkerProcessTestCase::test_multiple_workers
2024-12-25T07:22:36.222317875Z tests/tests/test_database_backend.py::DatabaseWorkerProcessTestCase::test_repeat_ctrl_c
2024-12-25T07:22:36.222321080Z tests/tests/test_database_backend.py::DatabaseWorkerProcessTestCase::test_run_subprocess
2024-12-25T07:22:36.222323195Z tests/tests/test_database_backend.py::DatabaseWorkerProcessTestCase::test_system_exit_task
2024-12-25T07:22:36.222328974Z tests/tests/test_dummy_backend.py::DummyBackendTransactionTestCase::test_doesnt_wait_until_transaction_commit
2024-12-25T07:22:36.222331274Z tests/tests/test_dummy_backend.py::DummyBackendTransactionTestCase::test_task_specific_enqueue_on_commit
2024-12-25T07:22:36.222362384Z tests/tests/test_dummy_backend.py::DummyBackendTransactionTestCase::test_wait_until_transaction_by_default
2024-12-25T07:22:36.222371152Z tests/tests/test_dummy_backend.py::DummyBackendTransactionTestCase::test_wait_until_transaction_commit
2024-12-25T07:22:36.222373423Z tests/tests/test_immediate_backend.py::ImmediateBackendTransactionTestCase::test_doesnt_wait_until_transaction_commit
2024-12-25T07:22:36.222381312Z tests/tests/test_immediate_backend.py::ImmediateBackendTransactionTestCase::test_task_specific_enqueue_on_commit
2024-12-25T07:22:36.222383462Z tests/tests/test_immediate_backend.py::ImmediateBackendTransactionTestCase::test_wait_until_transaction_by_default
2024-12-25T07:22:36.222386401Z tests/tests/test_immediate_backend.py::ImmediateBackendTransactionTestCase::test_wait_until_transaction_commit
2024-12-25T07:22:36.222395617Z tests/tests/test_dummy_backend.py::DummyBackendTestCase::test_enqueue_logs
2024-12-25T07:22:36.222401513Z tests/tests/test_dummy_backend.py::DummyBackendTestCase::test_enqueue_on_commit
2024-12-25T07:22:36.222403584Z tests/tests/test_dummy_backend.py::DummyBackendTestCase::test_enqueue_task
2024-12-25T07:22:36.222435538Z tests/tests/test_dummy_backend.py::DummyBackendTestCase::test_enqueue_task_async
2024-12-25T07:22:36.222440340Z tests/tests/test_dummy_backend.py::DummyBackendTestCase::test_exceptions
2024-12-25T07:22:36.222443715Z tests/tests/test_dummy_backend.py::DummyBackendTestCase::test_get_missing_result
2024-12-25T07:22:36.222463974Z tests/tests/test_dummy_backend.py::DummyBackendTestCase::test_get_result
2024-12-25T07:22:36.222496735Z tests/tests/test_dummy_backend.py::DummyBackendTestCase::test_get_result_async
2024-12-25T07:22:36.222503284Z tests/tests/test_dummy_backend.py::DummyBackendTestCase::test_get_result_from_different_request
2024-12-25T07:22:36.222505325Z tests/tests/test_dummy_backend.py::DummyBackendTestCase::test_meaning_of_life_view
2024-12-25T07:22:36.222507334Z tests/tests/test_dummy_backend.py::DummyBackendTestCase::test_refresh_result
2024-12-25T07:22:36.222509500Z tests/tests/test_dummy_backend.py::DummyBackendTestCase::test_refresh_result_async
2024-12-25T07:22:36.222512230Z tests/tests/test_dummy_backend.py::DummyBackendTestCase::test_using_correct_backend
2024-12-25T07:22:36.222514211Z tests/tests/test_immediate_backend.py::ImmediateBackendTestCase::test_cannot_get_result
2024-12-25T07:22:36.222517617Z tests/tests/test_immediate_backend.py::ImmediateBackendTestCase::test_cannot_pass_run_after
2024-12-25T07:22:36.222519800Z tests/tests/test_immediate_backend.py::ImmediateBackendTestCase::test_cannot_refresh_result
2024-12-25T07:22:36.222561397Z tests/tests/test_immediate_backend.py::ImmediateBackendTestCase::test_catches_exception
2024-12-25T07:22:36.222584893Z tests/tests/test_immediate_backend.py::ImmediateBackendTestCase::test_complex_exception
2024-12-25T07:22:36.222589068Z tests/tests/test_immediate_backend.py::ImmediateBackendTestCase::test_enqueue_logs
2024-12-25T07:22:36.222592738Z tests/tests/test_immediate_backend.py::ImmediateBackendTestCase::test_enqueue_on_commit
2024-12-25T07:22:36.222595929Z tests/tests/test_immediate_backend.py::ImmediateBackendTestCase::test_enqueue_task
2024-12-25T07:22:36.222601357Z tests/tests/test_immediate_backend.py::ImmediateBackendTestCase::test_enqueue_task_async
2024-12-25T07:22:36.222618313Z tests/tests/test_immediate_backend.py::ImmediateBackendTestCase::test_get_result_from_different_request
2024-12-25T07:22:36.222621089Z tests/tests/test_immediate_backend.py::ImmediateBackendTestCase::test_meaning_of_life_view
2024-12-25T07:22:36.222623098Z tests/tests/test_immediate_backend.py::ImmediateBackendTestCase::test_result
2024-12-25T07:22:36.222630188Z tests/tests/test_immediate_backend.py::ImmediateBackendTestCase::test_result_async
2024-12-25T07:22:36.222632321Z tests/tests/test_immediate_backend.py::ImmediateBackendTestCase::test_throws_keyboard_interrupt
2024-12-25T07:22:36.222634319Z tests/tests/test_immediate_backend.py::ImmediateBackendTestCase::test_using_correct_backend
2024-12-25T07:22:36.222636214Z tests/tests/test_tasks.py::TaskTestCase::test_aenqueue_with_invalid_argument
2024-12-25T07:22:36.222638248Z tests/tests/test_tasks.py::TaskTestCase::test_call_async_task
2024-12-25T07:22:36.222640367Z tests/tests/test_tasks.py::TaskTestCase::test_call_async_task_sync
2024-12-25T07:22:36.222689378Z tests/tests/test_tasks.py::TaskTestCase::test_call_task
2024-12-25T07:22:36.222692927Z tests/tests/test_tasks.py::TaskTestCase::test_call_task_async
2024-12-25T07:22:36.222695340Z tests/tests/test_tasks.py::TaskTestCase::test_chained_using
2024-12-25T07:22:36.222697361Z tests/tests/test_tasks.py::TaskTestCase::test_enqueue_task
2024-12-25T07:22:36.222699274Z tests/tests/test_tasks.py::TaskTestCase::test_enqueue_task_async
2024-12-25T07:22:36.222701189Z tests/tests/test_tasks.py::TaskTestCase::test_enqueue_with_invalid_argument
2024-12-25T07:22:36.222703309Z tests/tests/test_tasks.py::TaskTestCase::test_get_backend
2024-12-25T07:22:36.222732448Z tests/tests/test_tasks.py::TaskTestCase::test_get_incorrect_result
2024-12-25T07:22:36.222739096Z tests/tests/test_tasks.py::TaskTestCase::test_get_incorrect_result_async
2024-12-25T07:22:36.222741947Z tests/tests/test_tasks.py::TaskTestCase::test_get_missing_result
2024-12-25T07:22:36.222744396Z tests/tests/test_tasks.py::TaskTestCase::test_get_result
2024-12-25T07:22:36.222746464Z tests/tests/test_tasks.py::TaskTestCase::test_get_result_async
2024-12-25T07:22:36.222748507Z tests/tests/test_tasks.py::TaskTestCase::test_invalid_function
2024-12-25T07:22:36.222750478Z tests/tests/test_tasks.py::TaskTestCase::test_invalid_priority
2024-12-25T07:22:36.222752864Z tests/tests/test_tasks.py::TaskTestCase::test_module_path
2024-12-25T07:22:36.222755584Z tests/tests/test_tasks.py::TaskTestCase::test_naive_datetime
2024-12-25T07:22:36.222768900Z tests/tests/test_tasks.py::TaskTestCase::test_name
2024-12-25T07:22:36.222775099Z tests/tests/test_tasks.py::TaskTestCase::test_no_backends
2024-12-25T07:22:36.222777359Z tests/tests/test_tasks.py::TaskTestCase::test_refresh_result
2024-12-25T07:22:36.222779664Z tests/tests/test_tasks.py::TaskTestCase::test_task_decorator
2024-12-25T07:22:36.222786665Z tests/tests/test_tasks.py::TaskTestCase::test_using_correct_backend
2024-12-25T07:22:36.222788654Z tests/tests/test_tasks.py::TaskTestCase::test_using_creates_new_instance
2024-12-25T07:22:36.222790577Z tests/tests/test_tasks.py::TaskTestCase::test_using_missing_backend
2024-12-25T07:22:36.222810970Z tests/tests/test_tasks.py::TaskTestCase::test_using_priority
2024-12-25T07:22:36.222814745Z tests/tests/test_tasks.py::TaskTestCase::test_using_queue_name
2024-12-25T07:22:36.222816760Z tests/tests/test_tasks.py::TaskTestCase::test_using_run_after
2024-12-25T07:22:36.222818720Z tests/tests/test_tasks.py::TaskTestCase::test_using_unknown_backend
2024-12-25T07:22:36.222835622Z tests/tests/test_utils.py::IsModuleLevelFunctionTestCase::test_builtin
2024-12-25T07:22:36.222837965Z tests/tests/test_utils.py::IsModuleLevelFunctionTestCase::test_coroutine
2024-12-25T07:22:36.222839892Z tests/tests/test_utils.py::IsModuleLevelFunctionTestCase::test_from_module
2024-12-25T07:22:36.222842005Z tests/tests/test_utils.py::IsModuleLevelFunctionTestCase::test_lambda
2024-12-25T07:22:36.222854528Z tests/tests/test_utils.py::IsModuleLevelFunctionTestCase::test_method
2024-12-25T07:22:36.222856823Z tests/tests/test_utils.py::IsModuleLevelFunctionTestCase::test_private_function
2024-12-25T07:22:36.222871499Z tests/tests/test_utils.py::IsModuleLevelFunctionTestCase::test_uninitialised_method
2024-12-25T07:22:36.222901016Z tests/tests/test_utils.py::JSONNormalizeTestCase::test_encode_error
2024-12-25T07:22:36.222904542Z tests/tests/test_utils.py::JSONNormalizeTestCase::test_round_trip
2024-12-25T07:22:36.222906563Z tests/tests/test_utils.py::RetryTestCase::test_keeps_return_value
2024-12-25T07:22:36.222908498Z tests/tests/test_utils.py::RetryTestCase::test_retry
2024-12-25T07:22:36.222910506Z tests/tests/test_utils.py::RandomIdTestCase::test_correct_length
2024-12-25T07:22:36.222912635Z tests/tests/test_utils.py::RandomIdTestCase::test_random_ish
2024-12-25T07:22:36.222924491Z tests/tests/test_utils.py::ExceptionTracebackTestCase::test_complex_exception
2024-12-25T07:22:36.222926701Z tests/tests/test_utils.py::ExceptionTracebackTestCase::test_exception
2024-12-25T07:22:36.222928603Z tests/tests/test_utils.py::ExceptionTracebackTestCase::test_literal_exception
2024-12-25T07:22:36.223681663Z 
2024-12-25T07:22:36.223850193Z [32m[32m154 tests collected[0m[32m in 0.12s[0m[0m
2024-12-25T07:22:38.249636857Z [?2004hroot@b3426fc537fa:/django-tasks# pytest --collect-only -q[Kip install dj_database_urlytest[K
2024-12-25T07:22:38.446678692Z [?2004l
Traceback (most recent call last):
2024-12-25T07:22:38.446703889Z   File "/usr/local/bin/pytest", line 8, in <module>
2024-12-25T07:22:38.446720249Z     sys.exit(console_main())
2024-12-25T07:22:38.446723815Z   File "/usr/local/lib/python3.10/site-packages/_pytest/config/__init__.py", line 201, in console_main
2024-12-25T07:22:38.446727248Z     code = main()
2024-12-25T07:22:38.446730267Z   File "/usr/local/lib/python3.10/site-packages/_pytest/config/__init__.py", line 156, in main
2024-12-25T07:22:38.446733757Z     config = _prepareconfig(args, plugins)
2024-12-25T07:22:38.446737348Z   File "/usr/local/lib/python3.10/site-packages/_pytest/config/__init__.py", line 341, in _prepareconfig
2024-12-25T07:22:38.446741710Z     config = pluginmanager.hook.pytest_cmdline_parse(
2024-12-25T07:22:38.446743993Z   File "/usr/local/lib/python3.10/site-packages/pluggy/_hooks.py", line 513, in __call__
2024-12-25T07:22:38.446746061Z     return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
2024-12-25T07:22:38.446748130Z   File "/usr/local/lib/python3.10/site-packages/pluggy/_manager.py", line 120, in _hookexec
2024-12-25T07:22:38.446750166Z     return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
2024-12-25T07:22:38.446752093Z   File "/usr/local/lib/python3.10/site-packages/pluggy/_callers.py", line 139, in _multicall
2024-12-25T07:22:38.446754075Z     raise exception.with_traceback(exception.__traceback__)
2024-12-25T07:22:38.446756085Z   File "/usr/local/lib/python3.10/site-packages/pluggy/_callers.py", line 122, in _multicall
2024-12-25T07:22:38.446758056Z     teardown.throw(exception)  # type: ignore[union-attr]
2024-12-25T07:22:38.446759955Z   File "/usr/local/lib/python3.10/site-packages/_pytest/helpconfig.py", line 105, in pytest_cmdline_parse
2024-12-25T07:22:38.446762004Z     config = yield
2024-12-25T07:22:38.446763915Z   File "/usr/local/lib/python3.10/site-packages/pluggy/_callers.py", line 103, in _multicall
2024-12-25T07:22:38.446765880Z     res = hook_impl.function(*args)
2024-12-25T07:22:38.446767750Z   File "/usr/local/lib/python3.10/site-packages/_pytest/config/__init__.py", line 1140, in pytest_cmdline_parse
2024-12-25T07:22:38.446769775Z     self.parse(args)
2024-12-25T07:22:38.446771631Z   File "/usr/local/lib/python3.10/site-packages/_pytest/config/__init__.py", line 1494, in parse
2024-12-25T07:22:38.446773595Z     self._preparse(args, addopts=addopts)
2024-12-25T07:22:38.446775492Z   File "/usr/local/lib/python3.10/site-packages/_pytest/config/__init__.py", line 1398, in _preparse
2024-12-25T07:22:38.446777470Z     self.hook.pytest_load_initial_conftests(
2024-12-25T07:22:38.446779363Z   File "/usr/local/lib/python3.10/site-packages/pluggy/_hooks.py", line 513, in __call__
2024-12-25T07:22:38.446781335Z     return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
2024-12-25T07:22:38.446784251Z   File "/usr/local/lib/python3.10/site-packages/pluggy/_manager.py", line 120, in _hookexec
2024-12-25T07:22:38.446789395Z     return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
2024-12-25T07:22:38.446791409Z   File "/usr/local/lib/python3.10/site-packages/pluggy/_callers.py", line 139, in _multicall
2024-12-25T07:22:38.446793392Z     raise exception.with_traceback(exception.__traceback__)
2024-12-25T07:22:38.446795265Z   File "/usr/local/lib/python3.10/site-packages/pluggy/_callers.py", line 122, in _multicall
2024-12-25T07:22:38.446797245Z     teardown.throw(exception)  # type: ignore[union-attr]
2024-12-25T07:22:38.446799136Z   File "/usr/local/lib/python3.10/site-packages/_pytest/warnings.py", line 151, in pytest_load_initial_conftests
2024-12-25T07:22:38.446801204Z     return (yield)
2024-12-25T07:22:38.446803042Z   File "/usr/local/lib/python3.10/site-packages/pluggy/_callers.py", line 122, in _multicall
2024-12-25T07:22:38.446805011Z     teardown.throw(exception)  # type: ignore[union-attr]
2024-12-25T07:22:38.446806927Z   File "/usr/local/lib/python3.10/site-packages/_pytest/capture.py", line 154, in pytest_load_initial_conftests
2024-12-25T07:22:38.446808989Z     yield
2024-12-25T07:22:38.446810840Z   File "/usr/local/lib/python3.10/site-packages/pluggy/_callers.py", line 103, in _multicall
2024-12-25T07:22:38.446812821Z     res = hook_impl.function(*args)
2024-12-25T07:22:38.446814689Z   File "/usr/local/lib/python3.10/site-packages/pytest_django/plugin.py", line 357, in pytest_load_initial_conftests
2024-12-25T07:22:38.446816766Z     dj_settings.DATABASES  # noqa: B018
2024-12-25T07:22:38.446818642Z   File "/usr/local/lib/python3.10/site-packages/django/conf/__init__.py", line 81, in __getattr__
2024-12-25T07:22:38.446820664Z     self._setup(name)
2024-12-25T07:22:38.446822556Z   File "/usr/local/lib/python3.10/site-packages/django/conf/__init__.py", line 68, in _setup
2024-12-25T07:22:38.446825553Z     self._wrapped = Settings(settings_module)
2024-12-25T07:22:38.446828493Z   File "/usr/local/lib/python3.10/site-packages/django/conf/__init__.py", line 166, in __init__
2024-12-25T07:22:38.446831479Z     mod = importlib.import_module(self.SETTINGS_MODULE)
2024-12-25T07:22:38.446838674Z   File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
2024-12-25T07:22:38.446841753Z     return _bootstrap._gcd_import(name[level:], package, level)
2024-12-25T07:22:38.446844647Z   File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
2024-12-25T07:22:38.446847553Z   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
2024-12-25T07:22:38.446850777Z   File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
2024-12-25T07:22:38.446853886Z   File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
2024-12-25T07:22:38.446857305Z   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
2024-12-25T07:22:38.446863396Z   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
2024-12-25T07:22:38.446865495Z   File "/django-tasks/tests/settings.py", line 9, in <module>
2024-12-25T07:22:38.446867571Z     IN_TEST = sys.argv[1] == "test"
2024-12-25T07:22:38.446869551Z IndexError: list index out of range
2024-12-25T07:22:40.947071006Z [?2004hroot@b3426fc537fa:/django-tasks# pytest tests
2024-12-25T07:22:41.364116406Z [?2004l
[1m============================================================== test session starts ==============================================================[0m
2024-12-25T07:22:41.364152663Z platform linux -- Python 3.10.16, pytest-8.3.4, pluggy-1.5.0
2024-12-25T07:22:41.365542968Z django: version: 5.1.4, settings: tests.settings (from env)
2024-12-25T07:22:41.365551742Z rootdir: /django-tasks
2024-12-25T07:22:41.365553987Z configfile: pytest.ini
2024-12-25T07:22:41.365556360Z plugins: django-4.9.0
2024-12-25T07:22:41.444280596Z [1mcollecting ... [0m[1m
collected 154 items                                                                                                                             [0m
2024-12-25T07:22:41.444632592Z 
2024-12-25T07:23:06.447913898Z tests/tests/test_database_backend.py [32m.[0m[33ms[0m[33ms[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[31mF[0m[32m.[0m[33ms[0m[32m.[0m[33ms[0m[32m.[0m[33ms[0m[33ms[0m[32m.[0m[32m.[0m[31mF[0m[32m.[0m[31mF[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[31mF[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[31m                             [ 46%][0m
2024-12-25T07:23:06.639094981Z tests/tests/test_dummy_backend.py [32m.[0m[32m.[0m[32m.[0m[32m.[0m[31m                                                                                                    [ 49%][0m
2024-12-25T07:23:06.821245928Z tests/tests/test_immediate_backend.py [32m.[0m[32m.[0m[32m.[0m[32m.[0m[31m                                                                                                [ 51%][0m
2024-12-25T07:23:06.853813544Z tests/tests/test_dummy_backend.py [32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[31m                                                                                           [ 60%][0m
2024-12-25T07:23:06.893498693Z tests/tests/test_immediate_backend.py [32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[31m                                                                                     [ 70%][0m
2024-12-25T07:23:06.949964860Z tests/tests/test_tasks.py [32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[31m                                                                                  [ 89%][0m
2024-12-25T07:23:07.185776352Z tests/tests/test_utils.py [32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[32m.[0m[31m                                                                                                [100%][0m
2024-12-25T07:23:07.185811043Z 
2024-12-25T07:23:07.185820685Z =================================================================== FAILURES ====================================================================
2024-12-25T07:23:07.185839866Z [31m[1m______________________________________________ DatabaseBackendWorkerTestCase.test_verbose_logging _______________________________________________[0m
2024-12-25T07:23:07.185860098Z 
2024-12-25T07:23:07.185874207Z self = <tests.tests.test_database_backend.DatabaseBackendWorkerTestCase testMethod=test_verbose_logging>
2024-12-25T07:23:07.185879688Z 
2024-12-25T07:23:07.186293779Z     def test_verbose_logging(self) -> None:
2024-12-25T07:23:07.186300038Z         result = test_tasks.noop_task.enqueue()
2024-12-25T07:23:07.186302188Z     
2024-12-25T07:23:07.186304278Z         stdout = StringIO()
2024-12-25T07:23:07.186306307Z         self.run_worker(verbosity=3, stdout=stdout, stderr=stdout)
2024-12-25T07:23:07.186308640Z     
2024-12-25T07:23:07.186310510Z >       self.assertEqual(
2024-12-25T07:23:07.186312872Z             stdout.getvalue().splitlines(),
2024-12-25T07:23:07.186379670Z             [
2024-12-25T07:23:07.186400681Z                 "Starting worker for queues=default",
2024-12-25T07:23:07.186403356Z                 f"Task id={result.id} path=tests.tasks.noop_task state=RUNNING",
2024-12-25T07:23:07.186405529Z                 f"Task id={result.id} path=tests.tasks.noop_task state=SUCCEEDED",
2024-12-25T07:23:07.186407526Z                 "No more tasks to run - exiting gracefully.",
2024-12-25T07:23:07.186409579Z             ],
2024-12-25T07:23:07.186411757Z         )
2024-12-25T07:23:07.186413587Z [1m[31mE       AssertionError: Lists differ: [] != ['Starting worker for queues=default', 'Ta[217 chars]ly.'][0m
2024-12-25T07:23:07.186416566Z [1m[31mE       [0m
2024-12-25T07:23:07.186445974Z [1m[31mE       Second list contains 4 additional elements.[0m
2024-12-25T07:23:07.186467625Z [1m[31mE       First extra element 0:[0m
2024-12-25T07:23:07.186469673Z [1m[31mE       'Starting worker for queues=default'[0m
2024-12-25T07:23:07.186471691Z [1m[31mE       [0m
2024-12-25T07:23:07.186473927Z [1m[31mE       - [][0m
2024-12-25T07:23:07.186475836Z [1m[31mE       + ['Starting worker for queues=default',[0m
2024-12-25T07:23:07.186478970Z [1m[31mE       +  'Task id=d5de45a2-58f5-469c-9e10-29af4f535c03 path=tests.tasks.noop_task '[0m
2024-12-25T07:23:07.186481076Z [1m[31mE       +  'state=RUNNING',[0m
2024-12-25T07:23:07.186493454Z [1m[31mE       +  'Task id=d5de45a2-58f5-469c-9e10-29af4f535c03 path=tests.tasks.noop_task '[0m
2024-12-25T07:23:07.186509219Z [1m[31mE       +  'state=SUCCEEDED',[0m
2024-12-25T07:23:07.186530690Z [1m[31mE       +  'No more tasks to run - exiting gracefully.'][0m
2024-12-25T07:23:07.186535245Z 
2024-12-25T07:23:07.186545856Z [1m[31mtests/tests/test_database_backend.py[0m:659: AssertionError
2024-12-25T07:23:07.186624033Z --------------------------------------------------------------- Captured log call ---------------------------------------------------------------
2024-12-25T07:23:07.186630610Z [32mINFO    [0m django_tasks.backends.database.db_worker:db_worker.py:75 Starting worker for queues=default
2024-12-25T07:23:07.186634558Z [32mINFO    [0m django_tasks.backends.database.db_worker:db_worker.py:133 Task id=d5de45a2-58f5-469c-9e10-29af4f535c03 path=tests.tasks.noop_task state=RUNNING
2024-12-25T07:23:07.186638372Z [32mINFO    [0m django_tasks:signal_handlers.py:49 Task id=d5de45a2-58f5-469c-9e10-29af4f535c03 path=tests.tasks.noop_task state=SUCCEEDED
2024-12-25T07:23:07.186641880Z [32mINFO    [0m django_tasks.backends.database.db_worker:db_worker.py:257 No more tasks to run - exiting gracefully.
2024-12-25T07:23:07.186834575Z [31m[1m______________________________________ DatabaseBackendPruneTaskResultsTestCase.test_doesnt_prune_new_tasks ______________________________________[0m
2024-12-25T07:23:07.186851725Z 
2024-12-25T07:23:07.186853801Z self = <tests.tests.test_database_backend.DatabaseBackendPruneTaskResultsTestCase testMethod=test_doesnt_prune_new_tasks>
2024-12-25T07:23:07.186855998Z 
2024-12-25T07:23:07.187092291Z     def test_doesnt_prune_new_tasks(self) -> None:
2024-12-25T07:23:07.187100334Z         result = test_tasks.noop_task.enqueue()
2024-12-25T07:23:07.187102652Z     
2024-12-25T07:23:07.187104713Z         self.assertEqual(DBTaskResult.objects.ready().count(), 1)
2024-12-25T07:23:07.187107138Z     
2024-12-25T07:23:07.187109224Z         stdout = StringIO()
2024-12-25T07:23:07.187111412Z         with self.assertNumQueries(3):
2024-12-25T07:23:07.187113370Z             self.prune_task_results(min_age_days=0, stdout=stdout, verbosity=3)
2024-12-25T07:23:07.187115508Z     
2024-12-25T07:23:07.187117340Z         self.assertEqual(DBTaskResult.objects.ready().count(), 1)
2024-12-25T07:23:07.187155102Z     
2024-12-25T07:23:07.187161755Z         result.refresh()
2024-12-25T07:23:07.187163968Z     
2024-12-25T07:23:07.187166090Z >       self.assertEqual(stdout.getvalue().strip(), "Deleted 0 task result(s)")
2024-12-25T07:23:07.187168624Z [1m[31mE       AssertionError: '' != 'Deleted 0 task result(s)'[0m
2024-12-25T07:23:07.187192555Z [1m[31mE       + Deleted 0 task result(s)[0m
2024-12-25T07:23:07.187199053Z 
2024-12-25T07:23:07.187200933Z [1m[31mtests/tests/test_database_backend.py[0m:1030: AssertionError
2024-12-25T07:23:07.187220742Z --------------------------------------------------------------- Captured log call ---------------------------------------------------------------
2024-12-25T07:23:07.187228904Z [32mINFO    [0m django_tasks.backends.database.prune_db_task_results:prune_db_task_results.py:126 Deleted 0 task result(s)
2024-12-25T07:23:07.187394688Z [31m[1m_____________________________________________ DatabaseBackendPruneTaskResultsTestCase.test_dry_run ______________________________________________[0m
2024-12-25T07:23:07.187400051Z 
2024-12-25T07:23:07.187401927Z self = <tests.tests.test_database_backend.DatabaseBackendPruneTaskResultsTestCase testMethod=test_dry_run>
2024-12-25T07:23:07.187404051Z 
2024-12-25T07:23:07.187619183Z     def test_dry_run(self) -> None:
2024-12-25T07:23:07.187623883Z         test_tasks.noop_task.enqueue()
2024-12-25T07:23:07.187625811Z     
2024-12-25T07:23:07.187627685Z         DBTaskResult.objects.all().update(
2024-12-25T07:23:07.187629643Z             status=ResultStatus.SUCCEEDED, finished_at=timezone.now()
2024-12-25T07:23:07.187636504Z         )
2024-12-25T07:23:07.187638384Z     
2024-12-25T07:23:07.187644573Z         self.assertEqual(DBTaskResult.objects.count(), 1)
2024-12-25T07:23:07.187646853Z     
2024-12-25T07:23:07.187648792Z         stdout = StringIO()
2024-12-25T07:23:07.187650789Z         with self.assertNumQueries(1):
2024-12-25T07:23:07.187687435Z             self.prune_task_results(
2024-12-25T07:23:07.187700708Z                 min_age_days=0, dry_run=True, stdout=stdout, verbosity=3
2024-12-25T07:23:07.187703555Z             )
2024-12-25T07:23:07.187706321Z     
2024-12-25T07:23:07.187708437Z         self.assertEqual(DBTaskResult.objects.count(), 1)
2024-12-25T07:23:07.187710440Z     
2024-12-25T07:23:07.187713072Z >       self.assertEqual(stdout.getvalue().strip(), "Would delete 1 task result(s)")
2024-12-25T07:23:07.187749043Z [1m[31mE       AssertionError: '' != 'Would delete 1 task result(s)'[0m
2024-12-25T07:23:07.187753340Z [1m[31mE       + Would delete 1 task result(s)[0m
2024-12-25T07:23:07.187755417Z 
2024-12-25T07:23:07.187795542Z [1m[31mtests/tests/test_database_backend.py[0m:1170: AssertionError
2024-12-25T07:23:07.187806150Z --------------------------------------------------------------- Captured log call ---------------------------------------------------------------
2024-12-25T07:23:07.187808892Z [32mINFO    [0m django_tasks.backends.database.prune_db_task_results:prune_db_task_results.py:123 Would delete 1 task result(s)
2024-12-25T07:23:07.187947009Z [31m[1m___________________________________________ DatabaseBackendPruneTaskResultsTestCase.test_prunes_tasks ___________________________________________[0m
2024-12-25T07:23:07.187960362Z 
2024-12-25T07:23:07.187962792Z self = <tests.tests.test_database_backend.DatabaseBackendPruneTaskResultsTestCase testMethod=test_prunes_tasks>
2024-12-25T07:23:07.187965219Z 
2024-12-25T07:23:07.188147656Z     def test_prunes_tasks(self) -> None:
2024-12-25T07:23:07.188151010Z         result = test_tasks.noop_task.enqueue()
2024-12-25T07:23:07.188153071Z     
2024-12-25T07:23:07.188154918Z         DBTaskResult.objects.all().update(
2024-12-25T07:23:07.188156969Z             status=ResultStatus.SUCCEEDED, finished_at=timezone.now()
2024-12-25T07:23:07.188159136Z         )
2024-12-25T07:23:07.188161071Z     
2024-12-25T07:23:07.188181300Z         self.assertEqual(DBTaskResult.objects.finished().count(), 1)
2024-12-25T07:23:07.188186416Z     
2024-12-25T07:23:07.188188571Z         stdout = StringIO()
2024-12-25T07:23:07.188196488Z     
2024-12-25T07:23:07.188202620Z         with self.assertNumQueries(3):
2024-12-25T07:23:07.188216199Z             self.prune_task_results(min_age_days=0, stdout=stdout, verbosity=3)
2024-12-25T07:23:07.188221268Z     
2024-12-25T07:23:07.188224031Z         self.assertEqual(DBTaskResult.objects.finished().count(), 0)
2024-12-25T07:23:07.188227513Z     
2024-12-25T07:23:07.188231623Z         with self.assertRaises(ResultDoesNotExist):
2024-12-25T07:23:07.188268692Z             result.refresh()
2024-12-25T07:23:07.188274759Z     
2024-12-25T07:23:07.188277743Z >       self.assertEqual(stdout.getvalue().strip(), "Deleted 1 task result(s)")
2024-12-25T07:23:07.188325346Z [1m[31mE       AssertionError: '' != 'Deleted 1 task result(s)'[0m
2024-12-25T07:23:07.188332688Z [1m[31mE       + Deleted 1 task result(s)[0m
2024-12-25T07:23:07.188335645Z 
2024-12-25T07:23:07.188356514Z [1m[31mtests/tests/test_database_backend.py[0m:1015: AssertionError
2024-12-25T07:23:07.188380958Z --------------------------------------------------------------- Captured log call ---------------------------------------------------------------
2024-12-25T07:23:07.188387063Z [32mINFO    [0m django_tasks.backends.database.prune_db_task_results:prune_db_task_results.py:126 Deleted 1 task result(s)
2024-12-25T07:23:07.188574513Z [33m=============================================================== warnings summary ================================================================[0m
2024-12-25T07:23:07.188578229Z tests/tests/test_database_backend.py::ConnectionExclusiveTranscationTestCase::test_explicit_transaction
2024-12-25T07:23:07.188580835Z   /django-tasks/django_tasks/backends/database/migrations/0005_alter_dbtaskresult_priority_and_more.py:19: RemovedInDjango60Warning: CheckConstraint.check is deprecated in favor of `.condition`.
2024-12-25T07:23:07.188583593Z     constraint=models.CheckConstraint(
2024-12-25T07:23:07.188585508Z 
2024-12-25T07:23:07.188587338Z -- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
2024-12-25T07:23:07.189079809Z [36m[1m============================================================ short test summary info ============================================================[0m
2024-12-25T07:23:07.189084223Z [31mFAILED[0m tests/tests/test_database_backend.py::[1mDatabaseBackendWorkerTestCase::test_verbose_logging[0m - AssertionError: Lists differ: [] != ['Starting worker for queues=default', 'Ta[217 chars]ly.']
2024-12-25T07:23:07.189086626Z [31mFAILED[0m tests/tests/test_database_backend.py::[1mDatabaseBackendPruneTaskResultsTestCase::test_doesnt_prune_new_tasks[0m - AssertionError: '' != 'Deleted 0 task result(s)'
2024-12-25T07:23:07.189089043Z [31mFAILED[0m tests/tests/test_database_backend.py::[1mDatabaseBackendPruneTaskResultsTestCase::test_dry_run[0m - AssertionError: '' != 'Would delete 1 task result(s)'
2024-12-25T07:23:07.189091418Z [31mFAILED[0m tests/tests/test_database_backend.py::[1mDatabaseBackendPruneTaskResultsTestCase::test_prunes_tasks[0m - AssertionError: '' != 'Deleted 1 task result(s)'
2024-12-25T07:23:07.189098840Z [31m============================================= [31m[1m4 failed[0m, [32m144 passed[0m, [33m6 skipped[0m, [33m1 warning[0m[31m in 25.83s[0m[31m ==============================================[0m
2024-12-25T07:23:11.216181224Z [?2004hroot@b3426fc537fa:/django-tasks# exit
2024-12-25T07:23:11.216224372Z [?2004l
exit
