#0 building with "default" instance using docker driver

#1 [internal] load build definition from Dockerfile
#1 transferring dockerfile: 1.08kB done
#1 DONE 0.0s

#2 [internal] load metadata for docker.io/library/python:3.11
#2 DONE 0.0s

#3 [internal] load .dockerignore
#3 transferring context: 2B done
#3 DONE 0.0s

#4 [1/5] FROM docker.io/library/python:3.11
#4 DONE 0.0s

#5 [2/5] RUN mkdir -p ~/.pip && touch ~/.pip/pip.conf &&     echo "[global]" >> ~/.pip/pip.conf && echo "index-url=http://simple/" >> ~/.pip/pip.conf && echo "[install]" >> ~/.pip/pip.conf && echo "trusted-host=pypi..org" >> ~/.pip/pip.conf &&     apt-get update && apt-get install -y curl &&     curl -sSL https://install.python-poetry.org | python -
#5 CACHED

#6 [3/5] RUN pip install pytest pytest-xdist &&     pip install pipdeptree &&     git clone https://github.com/tahnok/colmi_r02_client.git &&     mkdir /repo &&     git config --global --add safe.directory /repo &&     cp -r /colmi_r02_client/. /repo && rm -rf /colmi_r02_client/ &&     rm -rf /colmi_r02_client &&     cd /repo && git checkout 84d3a6d9bd50cbac531d217ba1ff1cc7debe838d &&     cd /repo && poetry install
#6 1.980 Looking in indexes: http://simple/
#6 2.088 Collecting pytest
#6 2.139   Downloading http://packages/pytest/pytest-8.3.4-py3-none-any.whl (343 kB)
#6 2.227      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 343.1/343.1 kB 4.0 MB/s eta 0:00:00
#6 2.330 Collecting pytest-xdist
#6 2.447   Downloading http://packages/pytest-xdist/pytest_xdist-3.6.1-py3-none-any.whl (46 kB)
#6 2.459      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 46.1/46.1 kB 4.6 MB/s eta 0:00:00
#6 2.661 Collecting iniconfig (from pytest)
#6 2.836   Downloading http://packages/iniconfig/iniconfig-2.0.0-py3-none-any.whl (5.9 kB)
#6 2.953 Collecting packaging (from pytest)
#6 2.973   Using cached http://packages/packaging/packaging-24.2-py3-none-any.whl (65 kB)
#6 3.018 Collecting pluggy<2,>=1.5 (from pytest)
#6 3.033   Downloading http://packages/pluggy/pluggy-1.5.0-py3-none-any.whl (20 kB)
#6 3.082 Collecting execnet>=2.1 (from pytest-xdist)
#6 3.116   Downloading http://packages/execnet/execnet-2.1.1-py3-none-any.whl (40 kB)
#6 3.128      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 40.6/40.6 kB 3.8 MB/s eta 0:00:00
#6 3.242 Installing collected packages: pluggy, packaging, iniconfig, execnet, pytest, pytest-xdist
#6 3.794 Successfully installed execnet-2.1.1 iniconfig-2.0.0 packaging-24.2 pluggy-1.5.0 pytest-8.3.4 pytest-xdist-3.6.1
#6 3.794 WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
#6 3.889 
#6 3.889 [notice] A new release of pip is available: 24.0 -> 25.0
#6 3.889 [notice] To update, run: pip install --upgrade pip
#6 4.610 Looking in indexes: http://simple/
#6 4.668 Collecting pipdeptree
#6 4.683   Downloading http://packages/pipdeptree/pipdeptree-2.25.0-py3-none-any.whl (32 kB)
#6 4.707 Requirement already satisfied: packaging>=24.1 in /usr/local/lib/python3.11/site-packages (from pipdeptree) (24.2)
#6 4.785 Collecting pip>=24.2 (from pipdeptree)
#6 4.800   Downloading http://packages/pip/pip-25.0-py3-none-any.whl (1.8 MB)
#6 4.829      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.8/1.8 MB 74.0 MB/s eta 0:00:00
#6 4.934 Installing collected packages: pip, pipdeptree
#6 4.934   Attempting uninstall: pip
#6 4.938     Found existing installation: pip 24.0
#6 4.991     Uninstalling pip-24.0:
#6 5.309       Successfully uninstalled pip-24.0
#6 6.659 Successfully installed pip-25.0 pipdeptree-2.25.0
#6 6.659 WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
#6 6.844 Cloning into 'colmi_r02_client'...
#6 10.09 Note: switching to '84d3a6d9bd50cbac531d217ba1ff1cc7debe838d'.
#6 10.09 
#6 10.09 You are in 'detached HEAD' state. You can look around, make experimental
#6 10.09 changes and commit them, and you can discard any commits you make in this
#6 10.09 state without impacting any branches by switching back to a branch.
#6 10.09 
#6 10.09 If you want to create a new branch to retain commits you create, you may
#6 10.09 do so (now or later) by using -c with the switch command. Example:
#6 10.09 
#6 10.09   git switch -c <new-branch-name>
#6 10.09 
#6 10.09 Or undo this operation with:
#6 10.09 
#6 10.09   git switch -
#6 10.09 
#6 10.09 Turn off this advice by setting config variable advice.detachedHead to false
#6 10.09 
#6 10.09 HEAD is now at 84d3a6d fix: use last sync of current ring, not all rings
#6 11.35 Creating virtualenv colmi-r02-client-gW_DSdP6-py3.11 in /root/.cache/pypoetry/virtualenvs
#6 11.91 Installing dependencies from lock file
#6 12.15 
#6 12.15 Package operations: 29 installs, 0 updates, 0 removals
#6 12.15 
#6 12.16   - Installing idna (3.10)
#6 12.16   - Installing iniconfig (2.0.0)
#6 12.16   - Installing markupsafe (3.0.2)
#6 12.16   - Installing packaging (24.1)
#6 12.16   - Installing pluggy (1.5.0)
#6 12.16   - Installing six (1.16.0)
#6 12.16   - Installing sniffio (1.3.1)
#6 13.74   - Installing anyio (4.6.2.post1)
#6 13.74   - Installing attrs (24.2.0)
#6 13.75   - Installing dbus-fast (2.24.3)
#6 13.75   - Installing jinja2 (3.1.4)
#6 13.75   - Installing greenlet (3.1.1)
#6 13.76   - Installing pygments (2.18.0)
#6 13.76   - Installing nodeenv (1.9.1)
#6 13.76   - Installing pytest (8.3.3)
#6 13.76   - Installing python-dateutil (2.9.0.post0)
#6 13.77   - Installing sortedcontainers (2.4.0)
#6 13.77   - Installing typing-extensions (4.12.2)
#6 13.77   - Installing mypy-extensions (1.0.0)
#6 15.84   - Installing asyncclick (8.1.7.2)
#6 15.84   - Installing bleak (0.22.3)
#6 15.84   - Installing freezegun (1.5.1)
#6 15.85   - Installing hypothesis (6.116.0)
#6 15.85   - Installing mypy (1.13.0)
#6 15.85   - Installing pdoc (14.7.0)
#6 15.85   - Installing pyright (1.1.388)
#6 15.85   - Installing ruff (0.6.9)
#6 15.86   - Installing sqlalchemy (2.0.36)
#6 15.86   - Installing pytest-asyncio (0.24.0)
#6 20.72 
#6 20.72 Installing the current project: colmi-r02-client (0.1.0)
#6 DONE 21.6s

#7 [4/5] RUN cd /repo && pytest --collect-only -q
#7 1.271 tests/test_battery.py::test_parse_battery
#7 1.271 tests/test_pretty_print.py::test_print_lists_simple
#7 1.271 tests/test_pretty_print.py::test_print_lists_header
#7 1.271 tests/test_pretty_print.py::test_print_dicts
#7 1.271 tests/test_pretty_print.py::test_print_dataclasses
#7 1.271 tests/test_real_time.py::test_real_time_generation[1]
#7 1.271 tests/test_real_time.py::test_real_time_generation[2]
#7 1.271 tests/test_real_time.py::test_real_time_generation[3]
#7 1.271 tests/test_real_time.py::test_real_time_generation[4]
#7 1.271 tests/test_real_time.py::test_real_time_generation[5]
#7 1.271 tests/test_real_time.py::test_real_time_generation[7]
#7 1.271 tests/test_real_time.py::test_real_time_generation[8]
#7 1.271 tests/test_real_time.py::test_real_time_generation[9]
#7 1.271 tests/test_real_time.py::test_real_time_generation[10]
#7 1.271 tests/test_real_time.py::test_parse_real_time_reading_success
#7 1.271 tests/test_real_time.py::test_parse_real_time_reading_fail
#7 1.271 tests/test_set_time.py::test_byte_to_bcd[0-0]
#7 1.271 tests/test_set_time.py::test_byte_to_bcd[10-16]
#7 1.271 tests/test_set_time.py::test_byte_to_bcd[99-153]
#7 1.271 tests/test_set_time.py::test_byte_to_bcd_bad[-1]
#7 1.271 tests/test_set_time.py::test_byte_to_bcd_bad[100]
#7 1.271 tests/test_set_time.py::test_byte_to_bcd_bad[1000]
#7 1.271 tests/test_set_time.py::test_set_time_packet
#7 1.271 tests/test_set_time.py::test_set_time_1999
#7 1.271 tests/test_set_time.py::test_set_time_with_timezone
#7 1.271 tests/test_set_time.py::test_parse_set_time_response
#7 1.271 tests/test_steps.py::test_parse_simple
#7 1.271 tests/test_steps.py::test_parse_multi
#7 1.271 tests/test_steps.py::test_no_data_parse
#7 1.271 
#7 1.271 ==================================== ERRORS ====================================
#7 1.271 ______________________ ERROR collecting tests/test_cli.py ______________________
#7 1.271 ImportError while importing test module '/repo/tests/test_cli.py'.
#7 1.271 Hint: make sure your test modules/packages have valid Python names.
#7 1.271 Traceback:
#7 1.271 /usr/local/lib/python3.11/importlib/__init__.py:126: in import_module
#7 1.271     return _bootstrap._gcd_import(name[level:], package, level)
#7 1.271 tests/test_cli.py:3: in <module>
#7 1.271     from asyncclick.testing import CliRunner
#7 1.271 E   ModuleNotFoundError: No module named 'asyncclick'
#7 1.271 ____________________ ERROR collecting tests/test_client.py _____________________
#7 1.271 ImportError while importing test module '/repo/tests/test_client.py'.
#7 1.271 Hint: make sure your test modules/packages have valid Python names.
#7 1.271 Traceback:
#7 1.271 /usr/local/lib/python3.11/importlib/__init__.py:126: in import_module
#7 1.271     return _bootstrap._gcd_import(name[level:], package, level)
#7 1.271 tests/test_client.py:4: in <module>
#7 1.271     from bleak.backends.characteristic import BleakGATTCharacteristic
#7 1.271 E   ModuleNotFoundError: No module named 'bleak'
#7 1.271 __________________ ERROR collecting tests/test_date_utils.py ___________________
#7 1.271 ImportError while importing test module '/repo/tests/test_date_utils.py'.
#7 1.271 Hint: make sure your test modules/packages have valid Python names.
#7 1.271 Traceback:
#7 1.271 /usr/local/lib/python3.11/importlib/__init__.py:126: in import_module
#7 1.271     return _bootstrap._gcd_import(name[level:], package, level)
#7 1.271 tests/test_date_utils.py:3: in <module>
#7 1.271     from freezegun import freeze_time
#7 1.271 E   ModuleNotFoundError: No module named 'freezegun'
#7 1.271 ______________________ ERROR collecting tests/test_db.py _______________________
#7 1.271 ImportError while importing test module '/repo/tests/test_db.py'.
#7 1.271 Hint: make sure your test modules/packages have valid Python names.
#7 1.271 Traceback:
#7 1.271 /usr/local/lib/python3.11/importlib/__init__.py:126: in import_module
#7 1.271     return _bootstrap._gcd_import(name[level:], package, level)
#7 1.271 tests/test_db.py:6: in <module>
#7 1.271     from hypothesis import given, strategies as st
#7 1.271 E   ModuleNotFoundError: No module named 'hypothesis'
#7 1.271 ______________________ ERROR collecting tests/test_hr.py _______________________
#7 1.271 ImportError while importing test module '/repo/tests/test_hr.py'.
#7 1.271 Hint: make sure your test modules/packages have valid Python names.
#7 1.271 Traceback:
#7 1.271 /usr/local/lib/python3.11/importlib/__init__.py:126: in import_module
#7 1.271     return _bootstrap._gcd_import(name[level:], package, level)
#7 1.271 tests/test_hr.py:3: in <module>
#7 1.271     from freezegun import freeze_time
#7 1.271 E   ModuleNotFoundError: No module named 'freezegun'
#7 1.271 __________________ ERROR collecting tests/test_hr_settings.py __________________
#7 1.271 ImportError while importing test module '/repo/tests/test_hr_settings.py'.
#7 1.271 Hint: make sure your test modules/packages have valid Python names.
#7 1.271 Traceback:
#7 1.271 /usr/local/lib/python3.11/importlib/__init__.py:126: in import_module
#7 1.271     return _bootstrap._gcd_import(name[level:], package, level)
#7 1.271 tests/test_hr_settings.py:1: in <module>
#7 1.271     from hypothesis import given, strategies as st
#7 1.271 E   ModuleNotFoundError: No module named 'hypothesis'
#7 1.271 ____________________ ERROR collecting tests/test_packet.py _____________________
#7 1.271 ImportError while importing test module '/repo/tests/test_packet.py'.
#7 1.271 Hint: make sure your test modules/packages have valid Python names.
#7 1.271 Traceback:
#7 1.271 /usr/local/lib/python3.11/importlib/__init__.py:126: in import_module
#7 1.271     return _bootstrap._gcd_import(name[level:], package, level)
#7 1.271 tests/test_packet.py:3: in <module>
#7 1.271     from hypothesis import given
#7 1.271 E   ModuleNotFoundError: No module named 'hypothesis'
#7 1.271 =============================== warnings summary ===============================
#7 1.271 ../usr/local/lib/python3.11/site-packages/_pytest/config/__init__.py:1441
#7 1.271   /usr/local/lib/python3.11/site-packages/_pytest/config/__init__.py:1441: PytestConfigWarning: Unknown config option: asyncio_default_fixture_loop_scope
#7 1.271   
#7 1.271     self._warn_or_fail_if_strict(f"Unknown config option: {key}\n")
#7 1.271 
#7 1.271 ../usr/local/lib/python3.11/site-packages/_pytest/config/__init__.py:1441
#7 1.271   /usr/local/lib/python3.11/site-packages/_pytest/config/__init__.py:1441: PytestConfigWarning: Unknown config option: asyncio_mode
#7 1.271   
#7 1.271     self._warn_or_fail_if_strict(f"Unknown config option: {key}\n")
#7 1.271 
#7 1.271 -- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
#7 1.271 =========================== short test summary info ============================
#7 1.271 ERROR tests/test_cli.py
#7 1.271 ERROR tests/test_client.py
#7 1.271 ERROR tests/test_date_utils.py
#7 1.271 ERROR tests/test_db.py
#7 1.271 ERROR tests/test_hr.py
#7 1.271 ERROR tests/test_hr_settings.py
#7 1.271 ERROR tests/test_packet.py
#7 1.271 !!!!!!!!!!!!!!!!!!! Interrupted: 7 errors during collection !!!!!!!!!!!!!!!!!!!!
#7 1.271 29 tests collected, 7 errors in 0.44s
#7 ERROR: process "/bin/sh -c cd /repo && pytest --collect-only -q" did not complete successfully: exit code: 2
------
 > [4/5] RUN cd /repo && pytest --collect-only -q:
1.271 =========================== short test summary info ============================
1.271 ERROR tests/test_cli.py
1.271 ERROR tests/test_client.py
1.271 ERROR tests/test_date_utils.py
1.271 ERROR tests/test_db.py
1.271 ERROR tests/test_hr.py
1.271 ERROR tests/test_hr_settings.py
1.271 ERROR tests/test_packet.py
1.271 !!!!!!!!!!!!!!!!!!! Interrupted: 7 errors during collection !!!!!!!!!!!!!!!!!!!!
1.271 29 tests collected, 7 errors in 0.44s
------
Dockerfile:20
--------------------
  18 |         cd /repo && git checkout 84d3a6d9bd50cbac531d217ba1ff1cc7debe838d && \
  19 |         cd /repo && poetry install
  20 | >>> RUN cd /repo && pytest --collect-only -q
--------------------
ERROR: failed to solve: process "/bin/sh -c cd /repo && pytest --collect-only -q" did not complete successfully: exit code: 2
